import { createClient } from 'npm:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Client-Info, Apikey',
};

interface DocRaptorRequest {
  document_content: string;
  document_type: 'pdf';
  name: string;
  test: boolean;
  prince_options?: {
    profile?: string;
    pdf_title?: string;
    http_timeout?: number;
  };
}

interface DocRaptorResponse {
  status_id: string;
  download_url?: string;
  download_id?: string;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const docRaptorApiKey = Deno.env.get('DOCRAPTOR_API_KEY');
    const supabase = createClient(supabaseUrl, supabaseKey);

    if (!docRaptorApiKey) {
      throw new Error('DOCRAPTOR_API_KEY environment variable not set');
    }

    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('No authorization header');
    }

    const {
      htmlContent,
      filename,
      projectName,
      contractNumber,
      reportType,
      useTestMode
    } = await req.json();

    if (!htmlContent) {
      throw new Error('htmlContent is required');
    }

    if (!filename) {
      throw new Error('filename is required');
    }

    const today = new Date().toISOString().split('T')[0];
    const pdfFilename = `${filename}_${today}.pdf`;

    const leftHeader = contractNumber
      ? `${projectName || 'Project'} | ${contractNumber}`
      : projectName || 'Project';

    const htmlWithHeaderFooter = `
<!DOCTYPE html>
<html>
<head>
  <style>
    @page {
      size: A4;
      margin: 12mm 12mm 14mm 12mm;

      @top-left {
        content: "${leftHeader}";
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        font-size: 9pt;
        color: #6b7280;
      }

      @top-right {
        content: "${today} | Page " counter(page) " of " counter(pages);
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        font-size: 9pt;
        color: #6b7280;
      }

      @bottom-center {
        content: "Generated by VerifyTrade";
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        font-size: 8pt;
        color: #9ca3af;
      }
    }

    /* Print-safe CSS */
    * {
      print-color-adjust: exact;
      -webkit-print-color-adjust: exact;
    }

    .avoid-break {
      break-inside: avoid;
      page-break-inside: avoid;
    }

    .page-break {
      break-before: page;
      page-break-before: always;
    }

    img {
      max-width: 100%;
      height: auto;
    }

    table {
      break-inside: auto;
    }

    tr {
      break-inside: avoid;
      break-after: auto;
    }

    thead {
      display: table-header-group;
    }

    tfoot {
      display: table-footer-group;
    }
  </style>
</head>
<body>
${htmlContent}
</body>
</html>
`;

    const docRaptorRequest: DocRaptorRequest = {
      document_content: htmlWithHeaderFooter,
      document_type: 'pdf',
      name: pdfFilename,
      test: useTestMode !== false,
      prince_options: {
        profile: 'PDF/UA-1',
        pdf_title: `${reportType || 'Report'} - ${projectName || 'Project'}`,
        http_timeout: 300
      }
    };

    console.log('Calling DocRaptor API...');

    const docRaptorResponse = await fetch('https://docraptor.com/docs', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Basic ${btoa(`${docRaptorApiKey}:`)}`,
      },
      body: JSON.stringify(docRaptorRequest),
    });

    if (!docRaptorResponse.ok) {
      const errorText = await docRaptorResponse.text();
      console.error('DocRaptor error:', errorText);
      throw new Error(`DocRaptor API error: ${docRaptorResponse.status} - ${errorText}`);
    }

    const contentType = docRaptorResponse.headers.get('Content-Type');

    if (contentType?.includes('application/pdf')) {
      const pdfBuffer = await docRaptorResponse.arrayBuffer();

      return new Response(pdfBuffer, {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="${pdfFilename}"`,
        },
      });
    } else {
      const responseData = await docRaptorResponse.json();
      console.error('Unexpected DocRaptor response:', responseData);
      throw new Error('DocRaptor did not return a PDF');
    }

  } catch (error) {
    console.error('PDF generation error:', error);

    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : 'PDF generation failed',
        fallback: 'htm_export',
        message: 'DocRaptor service unavailable. Please use HTM export as fallback.'
      }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json'
        }
      }
    );
  }
});
