import type { TradeSpec } from '../types';

export const activeFireSpec: TradeSpec = {
  tradeModule: 'active_fire',
  name: 'Active Fire',
  color: 'red',
  accentHex: '#ef4444',
  description: 'Sprinkler systems and active fire protection',
  normalizationStrategy: 'system_based',

  scopeCategories: [
    'Sprinkler Systems',
    'Fire Detection & Alarms',
    'EWIS Systems',
    'Fire Hydrants & Hose Reels',
    'Fire Pumps & Tanks',
    'Suppression Systems',
    'Other Systems',
  ],

  groupingRules: [
    { groupName: 'Sprinkler Systems', keywords: ['sprinkler', 'suppression', 'deluge', 'mist'] },
    { groupName: 'Fire Detection & Alarms', keywords: ['detection', 'alarm', 'fip', 'detector', 'mcp', 'sounder', 'beacon'] },
    { groupName: 'EWIS Systems', keywords: ['ewis', 'emergency warning', 'intercommunication', 'warden'] },
    { groupName: 'Fire Hydrants & Hose Reels', keywords: ['hydrant', 'hose reel', 'landing valve', 'booster'] },
    { groupName: 'Fire Pumps & Tanks', keywords: ['pump', 'tank', 'jockey', 'duty', 'standby', 'reservoir'] },
    { groupName: 'Suppression Systems', keywords: ['gaseous', 'co2', 'fm200', 'novec', 'kitchen suppression'] },
  ],

  contractClauses: [
    {
      id: 'af-001',
      title: 'Scope of Works (Active Fire & Alarms)',
      category: 'scope',
      mandatory: true,
      body: `The Subcontractor shall supply, install, test, commission and hand over the Active Fire Protection and Fire Alarm works in accordance with the contract drawings, specifications, fire engineering report, and applicable standards current at the date of subcontract.\n\nThe scope includes all labour, materials, equipment, supervision and incidental items necessary to deliver a compliant, operable and certifiable active fire system within the defined scope.\n\n**Included (unless expressly excluded):**\n• Fire sprinkler / suppression systems as specified\n• Fire detection and alarm systems (FIP, detectors, MCPs, sounders)\n• Emergency warning and intercommunication systems (EWIS), where specified\n• Fire hydrants, hose reels and associated valves where specified\n• Pumps, tanks, and plant items within the defined fire scope\n• Commissioning, functional testing and defect rectification within scope\n• Attendance during inspections as specified in the contract`,
    },
    {
      id: 'af-002',
      title: 'Exclusions & By-Others',
      category: 'exclusions',
      mandatory: true,
      body: `The following are excluded unless expressly included in the Subcontract Particulars or scope schedule:\n\n• Builder's works including structural penetrations, coring, trenching, plinths, and making good\n• Fire engineering design or amendments unless expressly included\n• Authority or council fees, witnessing fees, or off-site works\n• Power supply and control wiring by electrical trades (unless clearly included)\n• BMS integration beyond dry contacts / interface points defined in the specification\n• Passive fire stopping of penetrations (by others unless included)\n• Ongoing maintenance beyond defects liability period\n\n**Balanced Clarification Principle:**\nWhere responsibilities overlap, interface responsibilities shall be confirmed in writing prior to works proceeding.`,
    },
    {
      id: 'af-003',
      title: 'Interfaces & Responsibility Matrix',
      category: 'interfaces',
      mandatory: true,
      body: `The Subcontractor shall coordinate interfaces with:\n\n• Electrical (power supplies, FIP feeds, isolators)\n• Mechanical (smoke control interfaces, dampers, plant shutdown)\n• Plumbing/Hydraulics (water supply, pumps, tanks)\n• Passive Fire (fire stopping at penetrations)\n• BMS / Security (monitoring and signal interfaces)\n\n**Responsibility Clarity:**\n• Active Fire contractor responsible for system functionality and compliance within their scope\n• Other trades remain responsible for their own works and certifications\n• Interfaces are limited to those defined in the fire engineering report and specification`,
    },
    {
      id: 'af-004',
      title: 'Testing, Commissioning & Certification',
      category: 'testing',
      mandatory: true,
      body: `The Subcontractor shall complete testing and commissioning in accordance with:\n\n• Fire engineering report\n• Applicable standards (AS 2118, AS 1670, AS 2441, AS 1851 where applicable)\n• Authority and insurer requirements where defined\n\n**Commissioning includes (where applicable):**\n• Functional testing of detection, alarm and suppression systems\n• Cause & effect testing\n• Pump testing and flow verification\n• Interface testing (shutdowns, alerts, signals)\n• Rectification of defects identified during commissioning\n\n**Balanced Limitation:**\nThe Subcontractor's responsibility is limited to testing and commissioning of systems within their contracted scope.`,
    },
    {
      id: 'af-005',
      title: 'Documentation, PS3 & Compliance (Critical)',
      category: 'documentation',
      mandatory: true,
      body: `The Subcontractor shall provide documentation required by the contract, including:\n\n• Test and commissioning records\n• Cause & effect matrices (as tested)\n• As-built drawings\n• Operation & Maintenance manuals\n• Product data sheets and warranties\n• Certificates and statements required for compliance\n\n**Producer Statements (NZ – where required):**\n• PS3 (Construction) issued for Active Fire works within subcontract scope\n• PS4 (Construction Review) only where expressly contracted`,
    },
    {
      id: 'af-006',
      title: 'Variations & Provisional Sums',
      category: 'variations',
      mandatory: true,
      body: `Any changes to fire engineering requirements, authority directives, scope boundaries, or access/programme constraints that affect time or cost shall constitute a variation, provided notice is given prior to works proceeding.\n\nProvisional sums or allowances shall be drawn down only with reasonable evidence and prior approval.`,
    },
    {
      id: 'af-007',
      title: 'Programme, Access & Inspections',
      category: 'programme',
      mandatory: true,
      body: `• The Main Contractor will coordinate access and inspection bookings\n• The Subcontractor shall attend inspections reasonably required under the contract\n• Delays caused by authority availability or third-party dependencies are not deemed Subcontractor default where reasonable cooperation is demonstrated`,
    },
    {
      id: 'af-008',
      title: 'Quality, Defects & Close-Out',
      category: 'quality',
      mandatory: true,
      body: `Works shall be completed in accordance with the approved documentation. Defects attributable to the Subcontractor shall be rectified within a reasonable timeframe. Defects caused by design changes, builder's works, or other trades shall be treated as coordination issues or variations where applicable.`,
    },
  ],

  checklistPhases: [
    {
      id: 'af-pre-start',
      title: 'Pre-Start Checklist',
      items: [
        { id: 'af-pre-001', text: 'Site induction completed (fire systems hazards)', mandatory: true },
        { id: 'af-pre-002', text: 'SWMS approved', mandatory: true },
        { id: 'af-pre-003', text: 'Supervisor competency verified', mandatory: true },
        { id: 'af-pre-004', text: 'Latest fire drawings & fire engineering report available', mandatory: true },
        { id: 'af-pre-005', text: 'Inspection regime agreed with Main Contractor', mandatory: true },
        { id: 'af-pre-006', text: 'Interface responsibilities confirmed', mandatory: true },
        { id: 'af-pre-007', text: 'Authority requirements understood', mandatory: true },
      ],
    },
    {
      id: 'af-installation',
      title: 'Installation Checklist',
      items: [
        { id: 'af-inst-001', text: 'Systems installed to drawings/specs and fire engineering report', mandatory: true },
        { id: 'af-inst-002', text: 'Devices, pipework, and equipment correctly located', mandatory: true },
        { id: 'af-inst-003', text: 'Supports and fixings compliant', mandatory: true },
        { id: 'af-inst-004', text: 'Penetrations coordinated with passive fire trade', mandatory: true },
        { id: 'af-inst-005', text: 'Power and interface connections coordinated with electrical', mandatory: true },
      ],
    },
    {
      id: 'af-quality',
      title: 'Quality Control & Testing',
      items: [
        { id: 'af-qc-001', text: 'Visual inspections completed', mandatory: true },
        { id: 'af-qc-002', text: 'Functional testing completed', mandatory: true },
        { id: 'af-qc-003', text: 'Cause & effect testing completed and matrices recorded', mandatory: true },
        { id: 'af-qc-004', text: 'Interface testing completed (shutdowns, alarms, signals)', mandatory: true },
        { id: 'af-qc-005', text: 'Pump testing and flow verification completed', mandatory: false },
        { id: 'af-qc-006', text: 'Defects logged and closed', mandatory: true },
      ],
    },
    {
      id: 'af-documentation',
      title: 'Documentation & Certification (Critical)',
      items: [
        { id: 'af-doc-001', text: 'Commissioning records complete', mandatory: true },
        { id: 'af-doc-002', text: 'Cause & effect matrices (as tested) issued', mandatory: true },
        { id: 'af-doc-003', text: 'As-built drawings issued', mandatory: true },
        { id: 'af-doc-004', text: 'O&M manuals compiled', mandatory: true },
        { id: 'af-doc-005', text: 'PS3 (Construction Statement) prepared where required (NZ)', mandatory: false, notes: 'Required for NZ consented buildings — Active Fire is typically a specified system' },
        { id: 'af-doc-006', text: 'Compliance certificates prepared', mandatory: true },
      ],
    },
    {
      id: 'af-handover',
      title: 'Final Handover & Close-Out',
      items: [
        { id: 'af-ho-001', text: 'All systems operational and demonstrated', mandatory: true },
        { id: 'af-ho-002', text: 'Training provided to FM/client', mandatory: true },
        { id: 'af-ho-003', text: 'Authority inspections passed', mandatory: true },
        { id: 'af-ho-004', text: 'Final documentation accepted', mandatory: true },
        { id: 'af-ho-005', text: 'PC sign-off obtained', mandatory: true },
      ],
    },
  ],

  riskRegister: [
    {
      id: 'rr-af-001',
      category: 'Compliance',
      risk: 'Failure to meet fire engineer and authority requirements',
      cause: 'Scope misinterpretation, design changes, specification gaps',
      consequence: 'Failed inspections, remediation, certification delays',
      likelihood: 'medium',
      impact: 'critical',
      mitigation: 'Early fire engineer review, staged inspections, compliant commissioning plan',
      owner: 'Fire Engineer / Site Manager',
    },
    {
      id: 'rr-af-002',
      category: 'Inspections',
      risk: 'Delayed or failed authority inspections',
      cause: 'Authority scheduling, inadequate preparation, incomplete works',
      consequence: 'Programme delays, certificate delays, occupation impact',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Advance booking, pre-inspection checks, commissioning plan',
      owner: 'Project Manager',
    },
    {
      id: 'rr-af-003',
      category: 'Interface Risk',
      risk: 'Electrical/mechanical boundary disputes',
      cause: 'Unclear scope for power supply, control wiring, smoke interfaces',
      consequence: 'Scope gaps, variation claims, commissioning delays',
      likelihood: 'high',
      impact: 'high',
      mitigation: 'Interface matrix agreed pre-start. Written confirmation of all interface points.',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-af-004',
      category: 'Documentation',
      risk: 'Missing PS3 and commissioning records',
      cause: 'Inadequate documentation regime, rushed programme',
      consequence: 'PS3 not issuable, code compliance certificate delayed',
      likelihood: 'medium',
      impact: 'critical',
      mitigation: 'Documentation tracker + hold points at each commissioning stage',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-af-005',
      category: 'Programme',
      risk: 'Authority dependency delays',
      cause: 'Authority availability, third-party witnessing requirements',
      consequence: 'Programme delay, occupation delay',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Programme float included for authority items. Early engagement with authority.',
      owner: 'Project Manager',
    },
    {
      id: 'rr-af-006',
      category: 'Testing & Commissioning',
      risk: 'Cause & effect test failures and IST delays',
      cause: 'Interface coordination gaps, control wiring issues, equipment faults',
      consequence: 'Extended commissioning, remediation, PC delay',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Commissioning plan + staged testing + IST coordination',
      owner: 'Site Manager',
    },
    {
      id: 'rr-af-007',
      category: 'Supply Chain',
      risk: 'Fire panel, detection devices, sprinkler heads on long lead',
      cause: 'Supply chain disruption, specialist requirements, late design',
      consequence: 'Installation delays, programme impact',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Early procurement + approved product list + supply monitoring',
      owner: 'Procurement Manager',
    },
    {
      id: 'rr-af-008',
      category: 'Certification',
      risk: 'Fire engineer PS3 sign-off delayed or not accepted',
      cause: 'Non-compliant installation, documentation gaps, third-party issues',
      consequence: 'Occupation certificate delayed, commercial exposure',
      likelihood: 'low',
      impact: 'critical',
      mitigation: 'Early fire engineer engagement + compliant installation + documentation readiness',
      owner: 'Fire Engineer',
    },
  ],

  complianceRequirements: [
    { id: 'af-comp-001', label: 'Fire Engineering Report Compliance', description: 'All systems comply with fire engineering report', mandatory: true, region: 'both' },
    { id: 'af-comp-002', label: 'AS 2118 / AS 1670 Compliance', description: 'Applicable Australian standards for sprinkler and detection systems', mandatory: true, region: 'both' },
    { id: 'af-comp-003', label: 'PS3 (Active Fire — NZ)', description: 'Producer Statement Construction for active fire works', mandatory: false, region: 'NZ' },
    { id: 'af-comp-004', label: 'Cause & Effect Matrix (As Tested)', description: 'Signed cause & effect matrix issued', mandatory: true, region: 'both' },
    { id: 'af-comp-005', label: 'Authority Inspection Sign-off', description: 'Authority inspection passed and signed off', mandatory: true, region: 'both' },
  ],

  validationRules: [
    { id: 'val-af-001', check: 'cause_effect_testing_present', message: 'Cause & effect testing must be included in scope', severity: 'error' },
    { id: 'val-af-002', check: 'ps3_clause_present', message: 'PS3 documentation clause should be included for NZ projects', severity: 'warning' },
    { id: 'val-af-003', check: 'fire_engineer_engagement', message: 'Fire engineering report compliance clause must be included', severity: 'error' },
  ],

  awardWording: {
    approved: {
      status: 'Approved / Recommended for Award',
      template: `**Recommendation: APPROVED FOR AWARD**\n\nThis Active Fire & Alarms submission demonstrates:\n• Strong compliance readiness with fire engineering requirements\n• Clear documentation and certification pathway\n• Appropriate interface management provisions\n• Reasonable risk allocation and testing protocols\n• Experience with similar life-safety critical installations\n\nThe submission is recommended for award subject to standard commercial clarifications and interface coordination pre-commencement.`,
    },
    clarificationRequired: {
      status: 'Clarification Required Prior to Award',
      template: `**Recommendation: CLARIFICATION REQUIRED**\n\nThis Active Fire & Alarms submission requires clarification on:\n• Compliance certification pathway and PS3 scope\n• Interface responsibilities (electrical/mechanical/BMS)\n• Testing and commissioning scope and timing\n• Authority inspection attendance and documentation deliverables\n• [Specific commercial or technical clarifications]\n\nSubject to satisfactory clarification, the submission may be suitable for award.`,
    },
    notRecommended: {
      status: 'Not Recommended for Award',
      template: `**Recommendation: NOT RECOMMENDED FOR AWARD**\n\nThis Active Fire & Alarms submission presents material compliance and delivery risks:\n• Insufficient compliance certification or PS3 scope definition\n• Unclear interface responsibilities creating coordination risk\n• Inadequate testing and commissioning provisions\n• Documentation and authority inspection gaps\n• [Specific deficiencies]\n\nThe submission is not recommended for award without material scope and commercial amendments.`,
    },
  },
};
