import type { TradeSpec } from '../types';

export const carpentrySpec: TradeSpec = {
  tradeModule: 'carpentry',
  name: 'Carpentry',
  color: 'amber',
  accentHex: '#f59e0b',
  description: 'Carpentry, plasterboard and insulation works',
  normalizationStrategy: 'section_based',

  scopeCategories: [
    'Wall Framing',
    'Ceiling Framing',
    'Plasterboard (GIB)',
    'Insulation',
    'Doors & Hardware',
    'Finishing',
    'Miscellaneous',
  ],

  groupingRules: [
    { groupName: 'Wall Framing', keywords: ['wall framing', 'external wall', 'internal wall', 'partition', 'fire rated wall', 'intertenancy wall', 'shaft wall', 'concrete lining', 'stud'] },
    { groupName: 'Ceiling Framing', keywords: ['ceiling framing', 'suspended ceiling', 'rondo', 'bulkhead', 'soffit', 'batten'] },
    { groupName: 'Plasterboard (GIB)', keywords: ['plasterboard', 'gib', 'board supply', 'fixing', 'stopping', 'aqualine', 'fyreline', 'lining'] },
    { groupName: 'Insulation', keywords: ['insulation', 'pink batt', 'kooltherm', 'rigid insulation', 'silencer', 'acoustic', 'thermal', 'r2.2', 'r3'] },
    { groupName: 'Doors & Hardware', keywords: ['door', 'handle', 'hinge', 'hardware', 'wardrobe', 'frame', 'jamb'] },
    { groupName: 'Finishing', keywords: ['architrave', 'skirting', 'trim', 'timber trim', 'reveal', 'window stool'] },
    { groupName: 'Miscellaneous', keywords: ['nogging', 'blocking', 'backing', 'nog', 'preliminaries', 'p&g', 'villaboard', 'rab board', 'joinery', 'canopy', 'gutter'] },
  ],

  contractClauses: [
    {
      id: 'carp-001',
      title: 'Scope of Works — Carpentry',
      category: 'scope',
      mandatory: true,
      body: `The subcontractor shall supply all labour, materials, plant, and equipment necessary to complete the carpentry works in strict accordance with the contract documents. This includes, but is not limited to, external and internal wall framing, ceiling framing, door installation, finishing carpentry, and all associated fixings and hardware.`,
    },
    {
      id: 'carp-002',
      title: 'Scope of Works — Plasterboard (GIB)',
      category: 'scope',
      mandatory: true,
      body: `The subcontractor shall supply and install all plasterboard (GIB board) works as specified, including supply, fixing, stopping, and sanding to the required finish levels. Works shall include all GIB Standard, GIB Aqualine, and GIB Fyreline as indicated on the drawings. All stopping shall be to Level 4 unless otherwise specified.`,
    },
    {
      id: 'carp-003',
      title: 'Scope of Works — Insulation',
      category: 'scope',
      mandatory: true,
      body: `The subcontractor shall supply and install all thermal and acoustic insulation as specified, including wall batts (minimum R2.2 Pink Batts or approved equivalent) and mid-floor acoustic insulation (Silencer or approved equivalent). Installation shall be in accordance with the manufacturer's specifications and all applicable building codes.`,
    },
    {
      id: 'carp-004',
      title: 'Wall Types and Specifications',
      category: 'technical',
      mandatory: true,
      body: `All wall framing shall be constructed in accordance with the wall type schedule contained in the contract documents. Wall types W30 through W36 (as defined in the drawings) shall be built to the specified stud sizes, spacings, and performance requirements. Any conflicts between the wall type schedule and drawings shall be referred to the contract administrator prior to proceeding.`,
    },
    {
      id: 'carp-005',
      title: 'Fire-Rated Assemblies',
      category: 'technical',
      mandatory: true,
      body: `Fire-rated wall and ceiling assemblies shall be constructed strictly in accordance with the specified fire rating. GIB Fyreline and other fire-rated boards shall be installed in compliance with the manufacturer's tested assembly instructions. No substitutions to fire-rated assemblies are permitted without written approval from the fire engineer.`,
    },
    {
      id: 'carp-006',
      title: 'Co-ordination with Other Trades',
      category: 'coordination',
      mandatory: true,
      body: `The subcontractor shall co-ordinate with all relevant trades prior to closing walls and ceilings to ensure that all mechanical, electrical, plumbing, and fire services penetrations are properly accommodated. The subcontractor shall not close any wall or ceiling until written approval is received from the contract administrator.`,
    },
    {
      id: 'carp-007',
      title: 'Moisture Management and Wet Area Boards',
      category: 'technical',
      mandatory: false,
      body: `All wet area substrates shall be constructed using moisture-resistant boards (GIB Aqualine or approved equivalent). The subcontractor shall ensure adequate sealing at all wall-to-floor junctions in wet areas prior to the application of any waterproofing membrane by others.`,
    },
    {
      id: 'carp-008',
      title: 'Acoustic Requirements',
      category: 'technical',
      mandatory: false,
      body: `All intertenancy walls and mid-floor assemblies shall achieve the specified acoustic performance ratings (Rw + Ctr) as noted on the drawings. The subcontractor shall ensure that all acoustic sealing, resilient mounts, and specified insulation products are installed in accordance with the tested assembly to achieve the design rating.`,
    },
    {
      id: 'carp-009',
      title: 'Defects and Workmanship',
      category: 'quality',
      mandatory: true,
      body: `All carpentry and plasterboard works shall be completed to a standard consistent with first-class workmanship. Plasterboard stopping shall be free from ridges, tool marks, shadows, and blistering. All framing shall be plumb, level, and true within tolerances specified in NZS 3604 or as otherwise noted. Defects identified at practical completion shall be rectified within the defects liability period at no additional cost.`,
    },
    {
      id: 'carp-010',
      title: 'Variations to Scope',
      category: 'commercial',
      mandatory: true,
      body: `No variations to the scope of works shall be executed without a written variation order issued by the contract administrator prior to the works being carried out. Verbal instructions do not constitute an instruction to vary the works. Day-work rates applicable to variations shall be agreed in writing at the time of contract execution.`,
    },
  ],

  checklistPhases: [
    {
      id: 'carp-framing',
      title: 'Framing',
      items: [
        { id: 'hc-carp-001', text: 'All wall framing complete and inspected (plumb, level, and true to specified wall types)', mandatory: true },
        { id: 'hc-carp-002', text: 'Ceiling framing complete and inspected at all levels', mandatory: true },
        { id: 'hc-carp-003', text: 'Door frames installed, plumb, and square to all openings', mandatory: true },
        { id: 'hc-carp-004', text: 'Canopy and balcony framing complete as per drawings', mandatory: false },
        { id: 'hc-carp-005', text: 'All blocking, nogs, and backing installed for fixtures (handrails, kitchens, bathrooms)', mandatory: true },
      ],
    },
    {
      id: 'carp-insulation',
      title: 'Insulation',
      items: [
        { id: 'hc-carp-006', text: 'Wall insulation (Pink Batts R2.2 or specified equivalent) installed to all external and intertenancy walls', mandatory: true },
        { id: 'hc-carp-007', text: 'Mid-floor acoustic insulation (Silencer or specified equivalent) installed at all intertenancy floors', mandatory: true },
        { id: 'hc-carp-008', text: 'Ceiling insulation installed at top-floor ceiling level', mandatory: false },
        { id: 'hc-carp-009', text: 'Insulation inspection sign-off obtained prior to close-in', mandatory: true, notes: 'Council or third-party inspection may be required' },
      ],
    },
    {
      id: 'carp-plasterboard',
      title: 'Plasterboard',
      items: [
        { id: 'hc-carp-010', text: 'All GIB board fixed to walls and ceilings — correct board type per location (Aqualine, Fyreline, Standard)', mandatory: true },
        { id: 'hc-carp-011', text: 'All fire-rated assemblies completed using correct Fyreline boards and tested assembly details', mandatory: true },
        { id: 'hc-carp-012', text: 'GIB stopping complete to specified level (minimum Level 4 unless noted otherwise)', mandatory: true },
        { id: 'hc-carp-013', text: 'All GIB corners, reveals, and architraves installed and stopped', mandatory: true },
        { id: 'hc-carp-014', text: 'Wet area GIB (Aqualine) installed and sealed at wall-to-floor junctions prior to waterproofing', mandatory: true },
      ],
    },
    {
      id: 'carp-doors-finishing',
      title: 'Doors & Finishing',
      items: [
        { id: 'hc-carp-015', text: 'All interior timber doors hung, adjusted, and hardware fitted', mandatory: true },
        { id: 'hc-carp-016', text: 'All skirting, architraves, and trims installed and fixed', mandatory: true },
        { id: 'hc-carp-017', text: 'All doors operate correctly without binding', mandatory: true },
      ],
    },
    {
      id: 'carp-documentation',
      title: 'Documentation',
      items: [
        { id: 'hc-carp-018', text: 'As-built mark-ups provided for all wall type changes or deviations', mandatory: true },
        { id: 'hc-carp-019', text: "Manufacturer's data sheets and installation certificates provided for all insulation products", mandatory: true },
        { id: 'hc-carp-020', text: 'GIB system certificates (Gib EzyBrace, Fyreline assembly records) provided', mandatory: false },
      ],
    },
    {
      id: 'carp-quality',
      title: 'Quality & Site Clean',
      items: [
        { id: 'hc-carp-021', text: 'All trade penetrations through fire walls correctly sealed in coordination with passive fire subcontractor', mandatory: true },
        { id: 'hc-carp-022', text: 'Defects register reviewed and all defects rectified prior to handover', mandatory: true },
        { id: 'hc-carp-023', text: 'Site clean — all off-cuts, waste, and packaging removed from all levels', mandatory: true },
      ],
    },
  ],

  riskRegister: [
    {
      id: 'rr-carp-001',
      category: 'Scope',
      risk: 'Wall type scope omissions',
      cause: 'Incorrect or incomplete wall schedule at tender',
      consequence: 'Variation claims post-award, programme delays',
      likelihood: 'high',
      impact: 'high',
      mitigation: 'Issue full wall type schedule with tender. Require tenderer confirmation of all wall types.',
      owner: 'Quantity Surveyor / Contract Administrator',
    },
    {
      id: 'rr-carp-002',
      category: 'Scope',
      risk: 'Lump sum pricing without floor-by-floor breakdown',
      cause: 'Tenderer prices a global lump sum without itemisation',
      consequence: 'Difficulty assessing variations, no basis for progress claims',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Require level-by-level pricing schedule as mandatory tender requirement',
      owner: 'Quantity Surveyor',
    },
    {
      id: 'rr-carp-003',
      category: 'Scope',
      risk: 'Plasterboard scope excluded from carpentry tender',
      cause: 'GIB priced separately or excluded from trade package',
      consequence: 'Interface risk, duplication or gaps in scope',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Define in tender whether GIB is included. Confirm no scope gaps at tender review.',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-carp-004',
      category: 'Quality',
      risk: 'Acoustic performance failure of intertenancy assemblies',
      cause: 'Incorrect insulation, inadequate acoustic sealing, framing defects',
      consequence: 'Failed acoustic testing, costly remediation, programme delays',
      likelihood: 'medium',
      impact: 'critical',
      mitigation: 'Specify tested assembly details. Acoustic consultant sign-off. Hold point before close-in.',
      owner: 'Site Manager / Acoustic Consultant',
    },
    {
      id: 'rr-carp-005',
      category: 'Quality',
      risk: 'Fire-rated assembly non-compliance',
      cause: 'Incorrect board type, incorrect assembly, unauthorized substitutions',
      consequence: 'Failed fire engineering assessment, code compliance failure, liability',
      likelihood: 'low',
      impact: 'critical',
      mitigation: 'Issue fire-rated assembly schedule. Fire engineer inspection sign-off. No substitutions without written approval.',
      owner: 'Fire Engineer / Site Manager',
    },
    {
      id: 'rr-carp-006',
      category: 'Programme',
      risk: 'Carpentry programme delay impacting follow-on trades',
      cause: 'Labour shortages, slow framing, wet weather',
      consequence: 'Delayed plasterboard, delayed finishing trades, critical path impact',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Confirm resource plan at contract. Monitor weekly progress. Identify acceleration options.',
      owner: 'Project Manager',
    },
    {
      id: 'rr-carp-007',
      category: 'Commercial',
      risk: 'Day-work rate disputes on variations',
      cause: 'No agreed day-work schedule at contract execution',
      consequence: 'Commercial disputes, delayed variation resolution',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Include agreed day-work schedule in the executed contract.',
      owner: 'Quantity Surveyor',
    },
    {
      id: 'rr-carp-008',
      category: 'Commercial',
      risk: 'Material cost escalation (timber, GIB, insulation)',
      cause: 'Supply chain disruption, commodity price increases',
      consequence: 'Subcontractor loss, claims for cost relief',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Fixed-price materials clauses or agreed fluctuation provisions for 12+ month projects.',
      owner: 'Commercial Manager',
    },
    {
      id: 'rr-carp-009',
      category: 'Interface',
      risk: 'Premature wall close-in before services rough-in complete',
      cause: 'Pressure on carpentry programme, inadequate hold points',
      consequence: 'Rework, cost dispute, programme delay',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Formal hold-point approval before close-in. Services contractor sign-off before GIB fixing.',
      owner: 'Site Manager',
    },
    {
      id: 'rr-carp-010',
      category: 'Health & Safety',
      risk: 'Manual handling injuries (heavy GIB, framing)',
      cause: 'Heavy materials, repetitive lifting, working at heights',
      consequence: 'Worker injury, LTI, H&S enforcement',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Subcontractor SSSP for carpentry works. Mechanical handling aids (board lifters, jigging).',
      owner: 'H&S Manager / Subcontractor',
    },
  ],

  complianceRequirements: [
    { id: 'carp-comp-001', label: 'Fire-Rated Assembly Documentation', description: 'Fire engineer inspection sign-off for all fire-rated assemblies', mandatory: true, region: 'both' },
    { id: 'carp-comp-002', label: 'Acoustic Testing Certification', description: 'Acoustic consultant sign-off for intertenancy assemblies (Rw + Ctr)', mandatory: false, region: 'both' },
    { id: 'carp-comp-003', label: 'NZS 3604 Framing Compliance', description: 'Framing tolerances per NZS 3604 or specified standard', mandatory: true, region: 'NZ' },
    { id: 'carp-comp-004', label: 'Insulation Inspection Sign-off', description: 'Pre-close-in inspection sign-off for insulation', mandatory: true, region: 'both' },
    { id: 'carp-comp-005', label: 'GIB System Certificates', description: 'Manufacturer certificates for Fyreline and EzyBrace systems', mandatory: false, region: 'both' },
  ],

  validationRules: [
    { id: 'val-carp-001', check: 'fire_rated_clause_present', message: 'Fire-rated assembly clause must be included', severity: 'error' },
    { id: 'val-carp-002', check: 'close_in_hold_point', message: 'Co-ordination with other trades clause (close-in hold point) must be included', severity: 'error' },
    { id: 'val-carp-003', check: 'acoustic_risk_acknowledged', message: 'Acoustic performance risk should be noted if intertenancy walls are in scope', severity: 'warning' },
    { id: 'val-carp-004', check: 'day_work_rates_agreed', message: 'Day-work rates should be agreed in the contract to reduce variation disputes', severity: 'warning' },
  ],

  awardWording: {
    approved: {
      status: 'Approved / Recommended for Award',
      template: `**Recommendation: APPROVED FOR AWARD**\n\nThis Carpentry/GIB submission demonstrates:\n• Comprehensive scope coverage of framing, plasterboard, insulation and finishing\n• Clear fire-rated assembly compliance approach\n• Appropriate acoustic and moisture management provisions\n• Suitable coordination with services trades and close-in hold points\n• Adequate documentation and defect rectification provisions\n\nThe submission is recommended for award subject to confirmation of day-work rates and resource plan.`,
    },
    clarificationRequired: {
      status: 'Clarification Required Prior to Award',
      template: `**Recommendation: CLARIFICATION REQUIRED**\n\nThis Carpentry/GIB submission requires clarification on:\n• Fire-rated assembly compliance approach and documentation\n• Acoustic performance provisions for intertenancy assemblies\n• Close-in hold point process\n• GIB scope inclusions/exclusions\n• [Specific clarifications]\n\nSubject to satisfactory clarification, the submission may be suitable for award.`,
    },
    notRecommended: {
      status: 'Not Recommended for Award',
      template: `**Recommendation: NOT RECOMMENDED FOR AWARD**\n\nThis Carpentry/GIB submission presents quality and compliance risks:\n• Insufficient fire-rated assembly provisions\n• Acoustic performance gaps\n• Scope exclusions relative to drawings and specification\n• [Specific deficiencies]\n\nNot recommended for award without material amendments.`,
    },
  },
};
