import type { TradeSpec } from '../types';

export const electricalSpec: TradeSpec = {
  tradeModule: 'electrical',
  name: 'Electrical',
  color: 'yellow',
  accentHex: '#eab308',
  description: 'Electrical systems and installations',
  normalizationStrategy: 'system_based',

  scopeCategories: [
    'Switchboards & Distribution',
    'Cable Containment',
    'Power Cabling',
    'Lighting Systems',
    'Emergency & Exit Lighting',
    'Small Power & Fitout',
    'Data & Communications',
    'Security & Access Control',
    'ELV Systems',
    'Earthing & Bonding',
    'Seismic & Structural',
    'Other Systems',
  ],

  groupingRules: [
    { groupName: 'Switchboards & Distribution', keywords: ['switchboard', 'msb', 'db', 'distribution board', 'mcc', 'panel'] },
    { groupName: 'Cable Containment', keywords: ['cable tray', 'conduit', 'trunking', 'cable ladder', 'containment'] },
    { groupName: 'Power Cabling', keywords: ['power cable', 'hv cable', 'lv cable', 'sub-main', 'feeder'] },
    { groupName: 'Lighting Systems', keywords: ['lighting', 'luminaire', 'light fitting', 'downlight', 'batten'] },
    { groupName: 'Emergency & Exit Lighting', keywords: ['emergency', 'exit', 'emergency lighting', 'exit sign'] },
    { groupName: 'Small Power & Fitout', keywords: ['gpo', 'outlet', 'power point', 'socket', 'fitout'] },
    { groupName: 'Data & Communications', keywords: ['data', 'comms', 'cat6', 'fibre', 'patch', 'telecommunications'] },
    { groupName: 'Security & Access Control', keywords: ['security', 'access control', 'cctv', 'intercom', 'door access'] },
    { groupName: 'ELV Systems', keywords: ['elv', 'extra low voltage', 'av', 'audio visual', 'nurse call'] },
    { groupName: 'Earthing & Bonding', keywords: ['earth', 'earthing', 'bonding', 'equipotential'] },
    { groupName: 'Seismic & Structural', keywords: ['seismic', 'restraint', 'bracing', 'structural support'] },
  ],

  contractClauses: [
    {
      id: 'elec-001',
      title: 'Scope & Deliverables (Electrical)',
      category: 'scope',
      mandatory: true,
      body: `The Subcontractor shall supply, install, test, commission and hand over all electrical works as shown on the contract drawings, specifications, and coordinated services layouts current at the date of subcontract, including all necessary labour, materials, plant, supervision and incidentals for a complete and compliant installation.\n\n**Included (unless expressly excluded):**\n• Main switchboards and distribution boards\n• Cable containment (trays, ladders, conduit, trunking)\n• Sub-mains and feeder cables as shown\n• Lighting installations including controls and dimming\n• Emergency and exit lighting systems\n• Small power, GPOs and fitout items as scheduled\n• Data and communications cabling and outlets\n• Earthing and bonding throughout\n• Testing, commissioning and certification within scope`,
    },
    {
      id: 'elec-002',
      title: 'Exclusions & By-Others',
      category: 'exclusions',
      mandatory: true,
      body: `The following are excluded unless explicitly included in the subcontract scope:\n\n• Builder's works (structural penetrations, coring, plinths, patching)\n• Authority connections and utility upgrades\n• BMS and controls integration beyond interface points defined\n• Security and CCTV systems unless specifically included\n• Mechanical equipment and HVAC power connections by mechanical trade (unless included)\n• Asbestos or hazardous material remediation\n• Seasonal or extended commissioning beyond defects period\n\n**Clarification Principle:**\nWhere responsibilities overlap, the parties shall agree in writing prior to work proceeding.`,
    },
    {
      id: 'elec-003',
      title: 'Interfaces & Responsibility Matrix',
      category: 'interfaces',
      mandatory: true,
      body: `The Subcontractor shall coordinate interfaces with:\n\n• Mechanical/HVAC (power and control supplies to equipment)\n• Plumbing (power to pumps, heaters, controls)\n• Fire Services (power feeds to FIP, EWIS, emergency systems)\n• BMS/Controls (power supplies, interface points, DDC panels)\n• Passive Fire (cable containment penetration timing)\n• Structural (cable tray supports, seismic bracing)\n\n**Interface Responsibility:**\n• Electrical subcontractor responsible for installation to points of connection shown\n• Other trades responsible for their own equipment and controls\n• Coordinated drawings to be agreed prior to installation`,
    },
    {
      id: 'elec-004',
      title: 'Testing, Commissioning & Certification',
      category: 'testing',
      mandatory: true,
      body: `The Subcontractor shall complete testing and commissioning in accordance with the contract specification and AS/NZS 3000 (Wiring Rules) and applicable standards, including:\n\n• Continuity, insulation resistance and polarity testing\n• Earth fault loop impedance testing\n• RCD testing\n• Switchboard functional testing and labelling\n• Emergency lighting functional testing (duration and lux levels)\n• Exit sign testing\n• Lighting control commissioning (dimming, DALI, sensors)\n• Interface testing with BMS and fire systems\n\n**Certificates / Evidence:**\nThe Subcontractor shall provide Certificates of Compliance (CoC) and Electrical Safety Certificates (ESC) as required by the applicable jurisdiction.`,
    },
    {
      id: 'elec-005',
      title: 'Compliance — AS/NZS 3000 & Certification',
      category: 'technical',
      mandatory: true,
      body: `All electrical works shall comply with:\n\n• AS/NZS 3000 (Wiring Rules) — current edition\n• AS/NZS 3018 (Electrical installations — Domestic installations) where applicable\n• Building Act and Building Code requirements\n• Local authority requirements\n• Relevant product standards for installed equipment\n\n**Certification:**\n• Certificates of Compliance (CoC) issued upon completion — New Zealand\n• Electrical Safety Certificates (ESC) where applicable\n• All work carried out by or under the supervision of a Licensed Electrical Inspector (NZ) or licensed electrician (AU)`,
    },
    {
      id: 'elec-006',
      title: 'Documentation: As-builts, CoC, O&M Manuals',
      category: 'documentation',
      mandatory: true,
      body: `The Subcontractor shall provide:\n\n• As-built drawings updated to "as-installed" status\n• Certificates of Compliance (CoC) for all licensed electrical work\n• Electrical Safety Certificates where applicable\n• O&M manuals for all supplied equipment\n• Switchboard schedules and circuit directories\n• Testing records (test results for insulation resistance, RCD, etc.)\n• Emergency lighting test records\n• PS3 (Electrical) where required (NZ consented projects)\n• Asset register for maintainable equipment`,
    },
    {
      id: 'elec-007',
      title: 'Programme, Long-lead Procurement & Access',
      category: 'programme',
      mandatory: true,
      body: `**Access & Sequencing:**\nThe Main Contractor will provide reasonable access and coordinate with other trades. Where access is restricted, the parties will agree resequencing or revised work methods.\n\n**Long-lead Items:**\nThe Subcontractor shall notify long-lead items (switchboards, specialist fittings, emergency systems) at contract commencement.\n\n**Live System Tie-ins:**\nWhere connections to live electrical systems are required, the Subcontractor shall provide notice and method statements. Approvals and stakeholder notifications coordinated through Main Contractor.`,
    },
    {
      id: 'elec-008',
      title: 'Variations & Provisional Sums',
      category: 'variations',
      mandatory: true,
      body: `Any change to scope, design, specification, setout or programme constraints that impacts time or cost shall be treated as a variation, provided notice is given prior to works proceeding.\n\n**Provisional Sums:**\nWhere allowances apply, the basis, inclusions and rates shall be documented. Drawdown requires reasonable supporting evidence and Main Contractor approval.`,
    },
    {
      id: 'elec-009',
      title: 'Quality, Defects & Close-Out',
      category: 'quality',
      mandatory: true,
      body: `All electrical works shall be completed to a standard consistent with AS/NZS 3000 and first-class workmanship. Defects attributable to the Subcontractor shall be rectified within a reasonable timeframe. Defects arising from design changes, builder's works or other trade interference shall be treated as variations where appropriate.`,
    },
  ],

  checklistPhases: [
    {
      id: 'elec-pre-start',
      title: 'Pre-Start Checklist',
      items: [
        { id: 'elec-pre-001', text: 'Site induction completed (electrical safety hazards)', mandatory: true },
        { id: 'elec-pre-002', text: 'Electrical SWMS reviewed and approved', mandatory: true },
        { id: 'elec-pre-003', text: 'Licensed supervisor and electrician competency verified', mandatory: true },
        { id: 'elec-pre-004', text: 'Latest drawings, specs and switchboard schedules available', mandatory: true },
        { id: 'elec-pre-005', text: 'Temporary power supply arrangements confirmed', mandatory: true },
        { id: 'elec-pre-006', text: 'Isolation and permit-to-work procedures confirmed', mandatory: true },
        { id: 'elec-pre-007', text: 'Long-lead items confirmed (switchboards, specialist fittings)', mandatory: true },
        { id: 'elec-pre-008', text: 'Interface responsibilities confirmed (mechanical, BMS, fire)', mandatory: true },
        { id: 'elec-pre-009', text: 'Builders works responsibilities confirmed', mandatory: true },
        { id: 'elec-pre-010', text: 'Coordinated services drawings approved', mandatory: false },
      ],
    },
    {
      id: 'elec-installation',
      title: 'Installation Checklist',
      items: [
        { id: 'elec-inst-001', text: 'Cable containment installed to drawings and specifications', mandatory: true },
        { id: 'elec-inst-002', text: 'All cabling installed with correct size and type per schedule', mandatory: true },
        { id: 'elec-inst-003', text: 'Earthing and bonding complete throughout', mandatory: true },
        { id: 'elec-inst-004', text: 'Switchboards installed, labelled, and circuit directories complete', mandatory: true },
        { id: 'elec-inst-005', text: 'Lighting fixtures installed to approved layout', mandatory: true },
        { id: 'elec-inst-006', text: 'Emergency lighting and exit signs installed per schedule', mandatory: true },
        { id: 'elec-inst-007', text: 'Seismic restraints installed on all cable trays and equipment', mandatory: true },
        { id: 'elec-inst-008', text: 'Penetrations coordinated with passive fire trade', mandatory: true },
        { id: 'elec-inst-009', text: 'No unapproved deviations from drawings or specifications', mandatory: true },
      ],
    },
    {
      id: 'elec-quality',
      title: 'Quality Control & Testing',
      items: [
        { id: 'elec-qc-001', text: 'Continuity, insulation resistance and polarity testing completed (AS/NZS 3000)', mandatory: true },
        { id: 'elec-qc-002', text: 'Earth fault loop impedance testing completed', mandatory: true },
        { id: 'elec-qc-003', text: 'RCD testing completed and recorded', mandatory: true },
        { id: 'elec-qc-004', text: 'Switchboard functional testing completed', mandatory: true },
        { id: 'elec-qc-005', text: 'Emergency lighting duration and lux level testing completed', mandatory: true },
        { id: 'elec-qc-006', text: 'Lighting controls (dimming, DALI, sensors) commissioned', mandatory: false },
        { id: 'elec-qc-007', text: 'Interface testing with BMS and fire systems completed', mandatory: false },
        { id: 'elec-qc-008', text: 'Defects logged and rectified', mandatory: true },
      ],
    },
    {
      id: 'elec-documentation',
      title: 'Documentation & Certification (Critical)',
      items: [
        { id: 'elec-doc-001', text: 'Certificates of Compliance (CoC) issued for all licensed electrical work', mandatory: true },
        { id: 'elec-doc-002', text: 'Electrical Safety Certificates (ESC) issued where applicable', mandatory: false, notes: 'Jurisdiction-dependent requirement' },
        { id: 'elec-doc-003', text: 'As-built drawings completed and submitted', mandatory: true },
        { id: 'elec-doc-004', text: 'Switchboard schedules and circuit directories issued', mandatory: true },
        { id: 'elec-doc-005', text: 'Testing records compiled (IR, RCD, continuity results)', mandatory: true },
        { id: 'elec-doc-006', text: 'Emergency lighting test records issued', mandatory: true },
        { id: 'elec-doc-007', text: 'O&M manuals issued for all supplied equipment', mandatory: true },
        { id: 'elec-doc-008', text: 'PS3 (Electrical — Construction) prepared where required (NZ)', mandatory: false, notes: 'Required for NZ consented projects where electrical is a specified system' },
      ],
    },
    {
      id: 'elec-handover',
      title: 'Final Handover & Close-Out',
      items: [
        { id: 'elec-ho-001', text: 'All electrical systems energised, operational and demonstrated', mandatory: true },
        { id: 'elec-ho-002', text: 'Training provided to FM/client (switchboard operation, emergency systems)', mandatory: true },
        { id: 'elec-ho-003', text: 'Defects list closed and signed off', mandatory: true },
        { id: 'elec-ho-004', text: 'Variations agreed and finalised', mandatory: true },
        { id: 'elec-ho-005', text: 'Final documentation accepted by Main Contractor', mandatory: true },
        { id: 'elec-ho-006', text: 'Practical Completion sign-off obtained', mandatory: true },
      ],
    },
  ],

  riskRegister: [
    {
      id: 'rr-elec-001',
      category: 'Programme',
      risk: 'Switchboard delivery delays',
      cause: 'Long manufacturing lead times, late design freeze',
      consequence: 'Critical path delay, delayed energisation, programme compression',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Place switchboard orders within 4 weeks of contract award. Monitor delivery against programme.',
      owner: 'Project Manager',
    },
    {
      id: 'rr-elec-002',
      category: 'Scope Clarity',
      risk: 'BMS and controls interface boundary disputes',
      cause: 'Unclear scope boundary between electrical and BMS subcontractors',
      consequence: 'Gaps in scope, variation claims, delays to commissioning',
      likelihood: 'high',
      impact: 'high',
      mitigation: 'Agree written interface matrix pre-award. Define electrical scope to points of connection.',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-elec-003',
      category: 'Quality & Compliance',
      risk: 'Failure to achieve AS/NZS 3000 compliance',
      cause: 'Incorrect installation, unlicensed work, product substitution',
      consequence: 'CoC not issuable, failed inspection, remediation costs',
      likelihood: 'low',
      impact: 'critical',
      mitigation: 'All work by licensed electricians. Staged inspections. No product substitution without approval.',
      owner: 'Site Manager',
    },
    {
      id: 'rr-elec-004',
      category: 'Testing & Commissioning',
      risk: 'Emergency lighting testing failures',
      cause: 'Incorrect specification, battery faults, installation errors',
      consequence: 'Failed testing, remediation, potential non-occupancy certificate',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Pre-test inspections. Emergency lighting commissioning plan. Allow programme float.',
      owner: 'Site Manager',
    },
    {
      id: 'rr-elec-005',
      category: 'Interface Risk',
      risk: 'Mechanical power connections not coordinated',
      cause: 'Late equipment schedules, changed equipment locations',
      consequence: 'Variations, rework, cabling cost increases',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Confirm equipment schedule at contract award. Issue coordinated electrical drawings.',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-elec-006',
      category: 'Supply Chain',
      risk: 'Cable and switchgear supply chain delays',
      cause: 'Global supply disruption, high demand, specialist requirements',
      consequence: 'Programme delays, cost increases',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Early procurement of long-lead items. Approved alternative products listed.',
      owner: 'Procurement Manager',
    },
    {
      id: 'rr-elec-007',
      category: 'Access & Coordination',
      risk: 'Cable tray clashes with other trades',
      cause: 'Inadequate 3D coordination, late setout changes',
      consequence: 'Rework, disputes, programme delays',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: '3D coordination model required. Coordinated services drawings signed off before installation.',
      owner: 'Services Coordinator',
    },
    {
      id: 'rr-elec-008',
      category: 'Commercial',
      risk: 'Variations from design development',
      cause: 'Evolving design, specification changes, late authority requirements',
      consequence: 'Cost and programme overrun, commercial disputes',
      likelihood: 'high',
      impact: 'medium',
      mitigation: 'Variation notice requirements in contract. Variation register maintained.',
      owner: 'Quantity Surveyor',
    },
    {
      id: 'rr-elec-009',
      category: 'Authority Dependencies',
      risk: 'Power authority connection delays',
      cause: 'Authority processing times, upgrade works required',
      consequence: 'Delayed energisation, programme impact',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Early engagement with power authority. Include authority risk in programme with float.',
      owner: 'Project Manager',
    },
    {
      id: 'rr-elec-010',
      category: 'Health & Safety',
      risk: 'Electrical arc flash and live work incidents',
      cause: 'Inadequate isolation procedures, unauthorised live work',
      consequence: 'Worker injury, LTI, prosecution, project shutdown',
      likelihood: 'low',
      impact: 'critical',
      mitigation: 'Strict permit-to-work for all live electrical work. Isolation procedure mandatory.',
      owner: 'H&S Manager',
    },
  ],

  complianceRequirements: [
    { id: 'elec-comp-001', label: 'AS/NZS 3000 Wiring Rules', description: 'All electrical works compliant with current edition', mandatory: true, region: 'both' },
    { id: 'elec-comp-002', label: 'Certificate of Compliance (CoC)', description: 'CoC issued for all licensed electrical work (NZ)', mandatory: true, region: 'NZ' },
    { id: 'elec-comp-003', label: 'Electrical Safety Certificate (ESC)', description: 'ESC issued where applicable', mandatory: false, region: 'NZ' },
    { id: 'elec-comp-004', label: 'Licensed Electrician Supervision', description: 'All work by or under supervision of licensed electrician', mandatory: true, region: 'both' },
    { id: 'elec-comp-005', label: 'Emergency Lighting Testing Records', description: 'Duration and lux level test records compiled', mandatory: true, region: 'both' },
    { id: 'elec-comp-006', label: 'PS3 Electrical (NZ)', description: 'Producer Statement Construction for electrical works', mandatory: false, region: 'NZ' },
  ],

  validationRules: [
    { id: 'val-elec-001', check: 'coc_required', message: 'Certificate of Compliance clause must be included for NZ projects', severity: 'error' },
    { id: 'val-elec-002', check: 'testing_clause_present', message: 'AS/NZS 3000 testing and commissioning clause must be included', severity: 'error' },
    { id: 'val-elec-003', check: 'emergency_lighting_checklist', message: 'Emergency lighting test items must appear in handover checklist', severity: 'warning' },
  ],

  awardWording: {
    approved: {
      status: 'Approved / Recommended for Award',
      template: `**Recommendation: APPROVED FOR AWARD**\n\nThis Electrical submission demonstrates:\n• Comprehensive scope coverage consistent with drawings and specification\n• Clear compliance pathway (AS/NZS 3000, CoC, ESC)\n• Appropriate testing, commissioning and certification provisions\n• Suitable interface management with mechanical, BMS and fire trades\n• Adequate long-lead procurement awareness\n\nThe submission is recommended for award subject to standard commercial clarifications.`,
    },
    clarificationRequired: {
      status: 'Clarification Required Prior to Award',
      template: `**Recommendation: CLARIFICATION REQUIRED**\n\nThis Electrical submission requires clarification on:\n• CoC and ESC certification scope and coverage\n• BMS and controls interface boundaries\n• Switchboard delivery programme\n• Emergency lighting test provisions\n• [Specific technical or commercial clarifications]\n\nSubject to satisfactory clarification, the submission may be suitable for award.`,
    },
    notRecommended: {
      status: 'Not Recommended for Award',
      template: `**Recommendation: NOT RECOMMENDED FOR AWARD**\n\nThis Electrical submission presents material compliance and delivery risks:\n• Insufficient AS/NZS 3000 compliance provisions\n• Inadequate certification (CoC/ESC) pathway\n• Scope gaps relative to drawings and specification\n• [Specific deficiencies]\n\nThe submission is not recommended for award without material amendments.`,
    },
  },
};
