import type { TradeSpec } from '../types';

export const hvacSpec: TradeSpec = {
  tradeModule: 'hvac',
  name: 'HVAC',
  color: 'cyan',
  accentHex: '#06b6d4',
  description: 'Heating, ventilation, and air conditioning systems',
  normalizationStrategy: 'system_based',

  scopeCategories: [
    'Ductwork Systems',
    'Pipework (Heating/Cooling)',
    'HVAC Plant & Equipment',
    'Controls & Actuators',
    'Fire & Smoke Dampers',
    'Condensate Drainage',
    'Acoustic & Vibration',
    'Access Doors & Grilles',
    'Other Systems',
  ],

  groupingRules: [
    { groupName: 'Ductwork Systems', keywords: ['duct', 'ductwork', 'ventilation', 'supply air', 'return air', 'extract', 'spiro'] },
    { groupName: 'Pipework (Heating/Cooling)', keywords: ['chilled water', 'heating water', 'hvac pipe', 'refrigerant', 'condenser'] },
    { groupName: 'HVAC Plant & Equipment', keywords: ['ahu', 'fcu', 'chiller', 'boiler', 'heat pump', 'fan coil', 'vrf', 'air handling'] },
    { groupName: 'Controls & Actuators', keywords: ['control', 'actuator', 'vav', 'motorised', 'damper control'] },
    { groupName: 'Fire & Smoke Dampers', keywords: ['fire damper', 'smoke damper', 'combined damper', 'intumescent damper'] },
    { groupName: 'Condensate Drainage', keywords: ['condensate', 'drain', 'condensate pump'] },
    { groupName: 'Acoustic & Vibration', keywords: ['acoustic', 'vibration', 'silencer', 'flexible', 'attenuator'] },
    { groupName: 'Access Doors & Grilles', keywords: ['access door', 'grille', 'diffuser', 'register', 'louvre'] },
  ],

  contractClauses: [
    {
      id: 'hvac-001',
      title: 'Scope & Deliverables (HVAC)',
      category: 'scope',
      mandatory: true,
      body: `The Subcontractor shall supply, install, test, commission and hand over the HVAC works as shown on the contract drawings, specifications, and coordinated services layouts current at the date of subcontract, including all necessary labour, materials, plant, supervision and incidentals for a complete and operable installation.\n\n**Included (unless expressly excluded):**\n• Ductwork systems, supports, dampers and insulation\n• Pipework systems for heating/cooling distribution\n• HVAC plant and equipment as specified\n• Controls and actuators within HVAC scope\n• Testing, commissioning and TAB (air and water balancing)\n• Fire/smoke dampers and associated control interfaces\n• Condensate drainage systems\n• Acoustic and vibration attenuation where specified\n• Access doors, grilles and diffusers\n• Coordination and interface management`,
    },
    {
      id: 'hvac-002',
      title: 'Exclusions & By-Others',
      category: 'exclusions',
      mandatory: true,
      body: `The following items are excluded unless explicitly included in the subcontract scope:\n\n• Builder's works (structural penetrations, coring, chasing, patching, structural supports)\n• Electrical power and control wiring to equipment (unless clearly included)\n• BMS integration beyond interface points defined in specification\n• Passive fire stopping of penetrations (by others unless included)\n• Building facade works, external plant screens\n• Authority fees or offsite works\n• Seasonal energy monitoring or extended commissioning beyond defects period\n\n**Clarification Principle:**\nWhere responsibilities overlap, the parties shall agree in writing prior to work proceeding.`,
    },
    {
      id: 'hvac-003',
      title: 'Interfaces & Responsibility Matrix',
      category: 'interfaces',
      mandatory: true,
      body: `The Subcontractor shall coordinate interfaces with:\n\n• **BMS/Controls:** Integration points, monitoring signals, control wiring demarcation\n• **Electrical:** Power supplies, isolators, disconnects for all HVAC equipment\n• **Fire Services:** Smoke control interfaces, damper control, plant shutdown signals\n• **Passive Fire:** Penetration locations, fire stopping access and timing\n• **Structural:** Plant loadings, seismic bracing, roof penetrations\n• **Hydraulics:** Condensate drainage, heating/cooling water interfaces\n\n**Interface Responsibility:**\n• HVAC subcontractor responsible for HVAC installation to points of connection\n• Other trades responsible for their own works unless expressly included\n• Coordination drawings and setout agreed with Main Contractor`,
    },
    {
      id: 'hvac-004',
      title: 'Testing, Commissioning, TAB & IST Requirements',
      category: 'testing',
      mandatory: true,
      body: `The Subcontractor shall complete testing and commissioning including as a minimum:\n\n• Pipework pressure testing (recorded results)\n• Duct leakage testing where required\n• Functional testing of all equipment, dampers, valves and controls\n• Test and Adjust/Balance (TAB) of air and water systems to design parameters\n• Point-to-point controls testing\n• Integrated Systems Testing (IST) with interfacing trades\n• Fire/smoke damper functional testing\n• Noise and vibration verification where specified\n\nThe Subcontractor shall provide test records, commissioning sheets, TAB reports and certification required by the contract.`,
    },
    {
      id: 'hvac-005',
      title: 'Warranties and Defects Liability',
      category: 'quality',
      mandatory: true,
      body: `The Subcontractor shall provide:\n\n• Equipment warranties and manufacturer's certificates\n• Recommended maintenance schedules for all equipment\n• Rectification of defects attributable to its work\n• Defects from design changes, builder's works issues or third-party damage shall be treated as variations\n\n**Balanced Rule:**\nThe Subcontractor's liability is limited to defects arising from materials, workmanship or installation within scope.`,
    },
    {
      id: 'hvac-006',
      title: 'Documentation: As-builts, O&M, TAB Reports',
      category: 'documentation',
      mandatory: true,
      body: `The Subcontractor shall provide:\n\n• As-built drawings updated to as-installed status\n• Operation & Maintenance (O&M) manuals for all equipment supplied\n• Manufacturer datasheets and product warranties\n• Commissioning records and test certificates\n• TAB reports (air and water balancing)\n• Asset register for maintainable equipment\n• Fire/smoke control compliance documentation\n• Energy efficiency documentation where contract requires`,
    },
    {
      id: 'hvac-007',
      title: 'Programme / Long-lead Procurement',
      category: 'programme',
      mandatory: true,
      body: `**Access & Sequencing:**\nThe Main Contractor will provide reasonable access and coordinate with other trades. Where access is restricted, the parties will agree resequencing.\n\n**Long-lead Items:**\nThe Subcontractor shall provide notice of long-lead items at contract commencement. Delays caused by authority availability or third-party dependencies are not Subcontractor default where reasonable notice is provided.\n\n**Plant Delivery and Cranage:**\nThe Subcontractor shall coordinate plant delivery, cranage and access with the Main Contractor with reasonable advance notice.`,
    },
    {
      id: 'hvac-008',
      title: 'Variations / PS Controls / Approval Thresholds',
      category: 'variations',
      mandatory: true,
      body: `Any change to scope, design, specification, setout, access or programme constraints that impacts time or cost shall be treated as a variation, provided notice is given before varied work is undertaken.\n\n**Provisional Sums:**\nWhere allowances apply, the basis, inclusions and rates shall be documented. Allowance drawdown requires reasonable supporting evidence and Main Contractor approval.`,
    },
  ],

  checklistPhases: [
    {
      id: 'hvac-pre-start',
      title: 'Pre-Start Checklist',
      items: [
        { id: 'hvac-pre-001', text: 'Site induction completed (HVAC-specific hazards)', mandatory: true },
        { id: 'hvac-pre-002', text: 'HVAC SWMS reviewed and approved', mandatory: true },
        { id: 'hvac-pre-003', text: 'Supervisor competency verified', mandatory: true },
        { id: 'hvac-pre-004', text: 'Latest drawings, specs and coordinated services layouts available', mandatory: true },
        { id: 'hvac-pre-005', text: 'Shop drawings approved (duct, pipe, plant layouts)', mandatory: true },
        { id: 'hvac-pre-006', text: 'Builders works responsibilities confirmed', mandatory: true },
        { id: 'hvac-pre-007', text: 'Plant access and cranage confirmed', mandatory: true },
        { id: 'hvac-pre-008', text: 'Temporary services confirmed', mandatory: false },
        { id: 'hvac-pre-009', text: 'Interfaces agreed (BMS/electrical/fire/passive fire)', mandatory: true },
        { id: 'hvac-pre-010', text: 'Long-lead procurement confirmed', mandatory: true },
      ],
    },
    {
      id: 'hvac-installation',
      title: 'Installation Checklist',
      items: [
        { id: 'hvac-inst-001', text: 'Ductwork installed to drawings and specifications', mandatory: true },
        { id: 'hvac-inst-002', text: 'Pipework installed (correct materials, supports, insulation)', mandatory: true },
        { id: 'hvac-inst-003', text: 'Equipment installed with required access clearances', mandatory: true },
        { id: 'hvac-inst-004', text: 'Seismic restraints installed where required', mandatory: true },
        { id: 'hvac-inst-005', text: 'Acoustic treatment installed as specified', mandatory: false },
        { id: 'hvac-inst-006', text: 'Fire/smoke dampers installed and accessible for testing', mandatory: true },
        { id: 'hvac-inst-007', text: 'Condensate drainage installed and falls correct', mandatory: true },
        { id: 'hvac-inst-008', text: 'Penetrations coordinated with passive fire trade', mandatory: true },
        { id: 'hvac-inst-009', text: 'No unapproved deviations from approved scope', mandatory: true },
      ],
    },
    {
      id: 'hvac-quality',
      title: 'Quality Control & Testing',
      items: [
        { id: 'hvac-qc-001', text: 'Visual inspections completed for all systems', mandatory: true },
        { id: 'hvac-qc-002', text: 'Pipework pressure testing completed and recorded', mandatory: true },
        { id: 'hvac-qc-003', text: 'Duct leakage testing completed where required', mandatory: false },
        { id: 'hvac-qc-004', text: 'TAB (air & water balancing) completed to design parameters', mandatory: true },
        { id: 'hvac-qc-005', text: 'Controls point-to-point testing completed', mandatory: true },
        { id: 'hvac-qc-006', text: 'Fire/smoke damper testing completed', mandatory: true },
        { id: 'hvac-qc-007', text: 'Noise and vibration checks completed', mandatory: false },
        { id: 'hvac-qc-008', text: 'Defects logged and closed', mandatory: true },
      ],
    },
    {
      id: 'hvac-documentation',
      title: 'Documentation & Certification (Critical)',
      items: [
        { id: 'hvac-doc-001', text: 'Commissioning plan approved', mandatory: true },
        { id: 'hvac-doc-002', text: 'Commissioning records signed', mandatory: true },
        { id: 'hvac-doc-003', text: 'TAB reports issued (air and water balancing)', mandatory: true },
        { id: 'hvac-doc-004', text: 'Equipment datasheets and warranties provided', mandatory: true },
        { id: 'hvac-doc-005', text: 'As-built drawings completed', mandatory: true },
        { id: 'hvac-doc-006', text: 'O&M manuals issued', mandatory: true },
        { id: 'hvac-doc-007', text: 'Fire/smoke control compliance documentation provided', mandatory: true },
        { id: 'hvac-doc-008', text: 'Energy efficiency documentation provided where required', mandatory: false },
        { id: 'hvac-doc-009', text: 'PS3 prepared where required (NZ consented projects)', mandatory: false },
      ],
    },
    {
      id: 'hvac-handover',
      title: 'Final Handover & Close-Out',
      items: [
        { id: 'hvac-ho-001', text: 'All HVAC systems operational', mandatory: true },
        { id: 'hvac-ho-002', text: 'Integrated systems testing (IST) completed', mandatory: true },
        { id: 'hvac-ho-003', text: 'Seasonal commissioning scheduled/confirmed if required', mandatory: false },
        { id: 'hvac-ho-004', text: 'Training provided to FM/client', mandatory: true },
        { id: 'hvac-ho-005', text: 'Defects list closed', mandatory: true },
        { id: 'hvac-ho-006', text: 'Variations finalised', mandatory: true },
        { id: 'hvac-ho-007', text: 'Final documentation accepted', mandatory: true },
        { id: 'hvac-ho-008', text: 'PC sign-off obtained', mandatory: true },
      ],
    },
  ],

  riskRegister: [
    {
      id: 'rr-hvac-001',
      category: 'Programme',
      risk: 'Plant delivery lead times and cranage access',
      cause: 'Long manufacturing lead times, late design freeze',
      consequence: 'Critical path delay, programme compression',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Early procurement, hold point register, coordination workshops',
      owner: 'Project Manager',
    },
    {
      id: 'rr-hvac-002',
      category: 'Scope Clarity',
      risk: 'BMS scope boundaries and electrical interface disputes',
      cause: 'Unclear scope boundary in specification',
      consequence: 'Scope gaps, variation claims, commissioning delays',
      likelihood: 'high',
      impact: 'high',
      mitigation: 'Interface matrix agreed pre-award, written clarifications on all interface points',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-hvac-003',
      category: 'Quality & Compliance',
      risk: 'TAB failures and fire damper non-compliance',
      cause: 'Incorrect installation, changed design, calibration issues',
      consequence: 'Failed commissioning, remediation, occupation delay',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Commissioning plan, staged testing, TAB specialist engaged early',
      owner: 'Site Manager',
    },
    {
      id: 'rr-hvac-004',
      category: 'Testing & Commissioning',
      risk: 'Seasonal commissioning and IST delays',
      cause: 'Incomplete interfaces, system not ready, authority scheduling',
      consequence: 'Extended programme, post-PC remediation',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'TAB specialist early, IST schedule, seasonal commissioning plan',
      owner: 'Services Coordinator',
    },
    {
      id: 'rr-hvac-005',
      category: 'Interface Risk',
      risk: 'BMS/electrical/fire/passive fire boundary disputes',
      cause: 'Ambiguous specification, poor pre-commencement coordination',
      consequence: 'Scope gaps, delays, variation disputes',
      likelihood: 'high',
      impact: 'high',
      mitigation: 'Written interface matrix, coordination workshops, RFI process',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-hvac-006',
      category: 'Supply Chain',
      risk: 'Plant equipment and specialist dampers on long lead',
      cause: 'Supply chain disruption, specialist requirements',
      consequence: 'Programme delays, cost increases',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Early procurement, approved alternatives, supply chain monitoring',
      owner: 'Procurement Manager',
    },
    {
      id: 'rr-hvac-007',
      category: 'Access & Coordination',
      risk: 'Plantroom access and ceiling grid coordination clashes',
      cause: 'Inadequate 3D coordination, late changes',
      consequence: 'Rework, programme delays',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: '3D coordination, access schedule, coordination drawings',
      owner: 'Services Coordinator',
    },
    {
      id: 'rr-hvac-008',
      category: 'Commercial',
      risk: 'Provisional sum exposure and variation disputes',
      cause: 'Unclear provisional sum scope, disputed variation notices',
      consequence: 'Commercial overrun, disputes',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Variation process agreed, PS/PC register maintained',
      owner: 'Quantity Surveyor',
    },
    {
      id: 'rr-hvac-009',
      category: 'Documentation',
      risk: 'Incomplete O&M manuals and TAB reports at handover',
      cause: 'Inadequate documentation regime, rushed handover',
      consequence: 'Documentation hold up, payment delays',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Documentation tracker, hold points, staged sign-off',
      owner: 'Contract Administrator',
    },
  ],

  complianceRequirements: [
    { id: 'hvac-comp-001', label: 'TAB Specialist Certification', description: 'TAB by qualified specialist, report issued', mandatory: true, region: 'both' },
    { id: 'hvac-comp-002', label: 'Fire/Smoke Damper Compliance', description: 'Fire and smoke damper testing records issued', mandatory: true, region: 'both' },
    { id: 'hvac-comp-003', label: 'IST Coordination', description: 'Integrated Systems Testing completed with interfacing trades', mandatory: true, region: 'both' },
    { id: 'hvac-comp-004', label: 'PS3 HVAC (NZ)', description: 'Producer Statement Construction for HVAC works', mandatory: false, region: 'NZ' },
    { id: 'hvac-comp-005', label: 'Energy Efficiency Documentation', description: 'Energy efficiency compliance documentation where required', mandatory: false, region: 'both' },
  ],

  validationRules: [
    { id: 'val-hvac-001', check: 'tab_in_checklist', message: 'TAB testing must appear in the commissioning checklist', severity: 'error' },
    { id: 'val-hvac-002', check: 'fire_damper_testing_present', message: 'Fire/smoke damper testing must be included in quality checklist', severity: 'error' },
    { id: 'val-hvac-003', check: 'ist_in_scope', message: 'IST coordination clause should be included', severity: 'warning' },
  ],

  awardWording: {
    approved: {
      status: 'Approved / Recommended for Award',
      template: `**Recommendation: APPROVED FOR AWARD**\n\nThis HVAC submission demonstrates:\n• Comprehensive scope coverage of ductwork, pipework, plant and controls\n• Clear TAB and commissioning approach\n• Appropriate interface management with BMS, electrical and fire systems\n• Adequate long-lead procurement awareness\n• Suitable documentation and O&M provisions\n\nThe submission is recommended for award subject to interface matrix confirmation and TAB specialist nomination.`,
    },
    clarificationRequired: {
      status: 'Clarification Required Prior to Award',
      template: `**Recommendation: CLARIFICATION REQUIRED**\n\nThis HVAC submission requires clarification on:\n• BMS and electrical interface boundaries\n• TAB specialist nomination and commissioning plan\n• Seasonal commissioning provisions\n• Fire/smoke damper testing approach\n• [Specific clarifications]\n\nSubject to satisfactory clarification, the submission may be suitable for award.`,
    },
    notRecommended: {
      status: 'Not Recommended for Award',
      template: `**Recommendation: NOT RECOMMENDED FOR AWARD**\n\nThis HVAC submission presents delivery and compliance risks:\n• Insufficient TAB and commissioning provisions\n• Unclear BMS/electrical interface boundaries\n• Scope gaps relative to drawings and specification\n• [Specific deficiencies]\n\nNot recommended for award without material amendments.`,
    },
  },
};
