import type { TradeSpec } from '../types';

export const passiveFireSpec: TradeSpec = {
  tradeModule: 'passive_fire',
  name: 'Passive Fire',
  color: 'orange',
  accentHex: '#f97316',
  description: 'Fire stopping and passive fire protection systems',
  normalizationStrategy: 'frl_based',

  scopeCategories: [
    'Electrical Penetrations',
    'Plumbing Penetrations',
    'Mechanical Penetrations',
    'Fire Sprinkler Penetrations',
    'Data & Communications',
    'Gas Penetrations',
    'Linear Joints',
    'Fire Collars',
    'Fire Batts & Wraps',
    'Flush Boxes',
    'Fire Boards',
    'Other Systems',
  ],

  groupingRules: [
    { groupName: 'Electrical Penetrations', keywords: ['electrical', 'cable', 'conduit', 'cable tray', 'trunking'] },
    { groupName: 'Plumbing Penetrations', keywords: ['plumbing', 'pipe', 'hydraulic', 'water', 'drain'] },
    { groupName: 'Mechanical Penetrations', keywords: ['mechanical', 'duct', 'hvac', 'air', 'damper'] },
    { groupName: 'Fire Sprinkler Penetrations', keywords: ['sprinkler', 'fire pipe', 'fire sprinkler'] },
    { groupName: 'Data & Communications', keywords: ['data', 'comms', 'communications', 'fibre', 'it cable'] },
    { groupName: 'Gas Penetrations', keywords: ['gas', 'lpg'] },
    { groupName: 'Linear Joints', keywords: ['linear joint', 'expansion joint', 'control joint'] },
    { groupName: 'Fire Collars', keywords: ['fire collar', 'collar', 'intumescent collar'] },
    { groupName: 'Fire Batts & Wraps', keywords: ['fire batt', 'wrap', 'mineral wool', 'ceramic'] },
    { groupName: 'Flush Boxes', keywords: ['flush box', 'powerpad', 'intumescent pad'] },
    { groupName: 'Fire Boards', keywords: ['fire board', 'board', 'vermiculite', 'promat'] },
  ],

  contractClauses: [
    {
      id: 'pf-001',
      title: 'Scope of Works — Passive Fire Protection',
      category: 'scope',
      mandatory: true,
      body: `The Subcontractor shall supply, install, test and hand over all passive fire protection works in accordance with the contract drawings, fire engineering report, and applicable standards current at the date of subcontract.\n\nThe scope includes all labour, materials, equipment, supervision and incidental items necessary to deliver compliant, inspected and certified passive fire stopping within the defined scope.\n\n**Included (unless expressly excluded):**\n• Fire stopping of penetrations through fire-rated walls and floors\n• Linear joint sealing at all fire-rated construction joints\n• Fire collars and intumescent products as specified\n• Fire batts, wraps and boards for duct and pipe penetrations\n• Flush boxes and intumescent pads where specified\n• Inspection, testing and certification of completed works\n• Attendance at council or authority inspections`,
    },
    {
      id: 'pf-002',
      title: 'Exclusions & By-Others',
      category: 'exclusions',
      mandatory: true,
      body: `The following are excluded unless expressly included in the Subcontract Particulars:\n\n• Active fire protection systems (sprinklers, detection, alarms — by others)\n• Builder's works including structural penetrations, coring, patching and making good\n• Fire engineering design or amendments\n• Authority or council fees and witnessing fees\n• Fire-rated framing or plasterboard installation (by carpentry trades)\n• Ongoing maintenance beyond defects liability period\n\n**Balanced Clarification Principle:**\nWhere responsibilities overlap, interface responsibilities shall be confirmed in writing prior to works proceeding.`,
    },
    {
      id: 'pf-003',
      title: 'Interfaces & Responsibility Matrix',
      category: 'interfaces',
      mandatory: true,
      body: `The Subcontractor shall coordinate interfaces with:\n\n• Carpentry (wall/ceiling close-in sequence, access for sealing)\n• Electrical (cable containment penetration locations and timing)\n• Mechanical/HVAC (duct penetrations, fire damper interfaces)\n• Plumbing/Hydraulics (pipe penetrations, penetration locations)\n• Main Contractor (inspection hold points, access, programme)\n\n**Responsibility Clarity:**\n• Passive fire contractor responsible for sealing penetrations within their scope\n• Other trades responsible for their own installations and timing coordination\n• Penetration schedule to be agreed with Main Contractor before close-in`,
    },
    {
      id: 'pf-004',
      title: 'Fire Resistance Ratings & Product Compliance',
      category: 'technical',
      mandatory: true,
      body: `All passive fire protection systems shall achieve the specified Fire Resistance Ratings (FRR) as noted in the fire engineering report and drawings.\n\n• Products shall be installed strictly in accordance with the manufacturer's tested assembly instructions\n• No substitutions to specified products or FRR ratings without written approval from the fire engineer\n• Product data sheets and tested assembly certificates shall be maintained on site\n• FRR ratings shall be identified on all installed systems (tagging or marking where required)`,
    },
    {
      id: 'pf-005',
      title: 'Inspection, Testing & Certification',
      category: 'testing',
      mandatory: true,
      body: `The Subcontractor shall:\n\n• Conduct visual inspections of all completed installations\n• Photograph and record all installed systems before concealment\n• Provide inspection records and photographic evidence for each penetration\n• Prepare Producer Statements (PS3) for passive fire works where required (NZ projects)\n• Attend authority or council inspections as required\n\n**Balanced Limitation:**\nThe Subcontractor's responsibility is limited to certification of systems within their contracted scope. Third-party delays are not deemed a default where reasonable notice has been provided.`,
    },
    {
      id: 'pf-006',
      title: 'Documentation & Compliance Records',
      category: 'documentation',
      mandatory: true,
      body: `The Subcontractor shall provide:\n\n• Photographic inspection records for each penetration sealed\n• Product data sheets and manufacturer installation certificates\n• Tested assembly certificates (FRR evidence)\n• As-installed schedules (location, product, FRR, date)\n• PS3 (Producer Statement — Construction) where required\n• Defects records and close-out confirmation`,
    },
    {
      id: 'pf-007',
      title: 'Variations & Provisional Sums',
      category: 'variations',
      mandatory: true,
      body: `Any changes to:\n• Fire engineering requirements\n• Penetration locations or quantities\n• Product specifications\n• Programme or access constraints\n\nthat affect time or cost shall constitute a variation, provided notice is given prior to works proceeding.\n\nProvisional sums shall be drawn down only with reasonable evidence and prior approval.`,
    },
    {
      id: 'pf-008',
      title: 'Programme, Access & Inspections',
      category: 'programme',
      mandatory: true,
      body: `• The Main Contractor will coordinate access and inspection hold points\n• The Subcontractor shall provide reasonable notice before concealing any penetrations\n• Delays caused by late access, incomplete penetrations, or third-party constraints are not deemed Subcontractor default where reasonable notice has been provided`,
    },
  ],

  checklistPhases: [
    {
      id: 'pf-pre-start',
      title: 'Pre-Start Checklist',
      items: [
        { id: 'pf-pre-001', text: 'Site induction completed (fire stopping hazards)', mandatory: true },
        { id: 'pf-pre-002', text: 'SWMS reviewed and approved', mandatory: true },
        { id: 'pf-pre-003', text: 'Supervisor competency and product training verified', mandatory: true },
        { id: 'pf-pre-004', text: 'Latest fire engineering report and drawings available on site', mandatory: true },
        { id: 'pf-pre-005', text: 'Penetration schedule agreed with Main Contractor', mandatory: true },
        { id: 'pf-pre-006', text: 'Product approvals confirmed (fire engineer or specification)', mandatory: true },
        { id: 'pf-pre-007', text: 'Inspection hold points agreed with Main Contractor', mandatory: true },
        { id: 'pf-pre-008', text: 'Interface responsibilities confirmed with other trades', mandatory: true },
      ],
    },
    {
      id: 'pf-installation',
      title: 'Installation Checklist',
      items: [
        { id: 'pf-inst-001', text: 'Penetrations installed to fire engineering drawings and FRR schedule', mandatory: true },
        { id: 'pf-inst-002', text: 'Correct product used per tested assembly (no unapproved substitutions)', mandatory: true },
        { id: 'pf-inst-003', text: 'All penetrations photographed before concealment', mandatory: true },
        { id: 'pf-inst-004', text: 'Linear joints sealed at all fire-rated construction joints', mandatory: true },
        { id: 'pf-inst-005', text: 'Fire collars and intumescent products installed per manufacturer instructions', mandatory: true },
        { id: 'pf-inst-006', text: 'Duct wraps and fire batts installed where specified', mandatory: false },
        { id: 'pf-inst-007', text: 'Flush boxes and intumescent pads installed where specified', mandatory: false },
        { id: 'pf-inst-008', text: 'No unapproved deviations from specification', mandatory: true },
      ],
    },
    {
      id: 'pf-quality',
      title: 'Quality Control & Inspection',
      items: [
        { id: 'pf-qc-001', text: 'Visual inspection completed for all installed systems', mandatory: true },
        { id: 'pf-qc-002', text: 'Photographic records compiled for each penetration', mandatory: true },
        { id: 'pf-qc-003', text: 'Hold-point inspections passed and signed off', mandatory: true },
        { id: 'pf-qc-004', text: 'Defects identified and rectified', mandatory: true },
        { id: 'pf-qc-005', text: 'FRR tagging or identification installed where required', mandatory: false },
      ],
    },
    {
      id: 'pf-documentation',
      title: 'Documentation & Certification (Critical)',
      items: [
        { id: 'pf-doc-001', text: 'Photographic inspection register completed', mandatory: true },
        { id: 'pf-doc-002', text: 'As-installed penetration schedule issued', mandatory: true },
        { id: 'pf-doc-003', text: 'Product data sheets and tested assembly certificates provided', mandatory: true },
        { id: 'pf-doc-004', text: 'PS3 (Producer Statement — Construction) prepared where required (NZ)', mandatory: false, notes: 'Required for NZ consented buildings where passive fire is a specified system' },
        { id: 'pf-doc-005', text: 'Defects register reviewed and closed', mandatory: true },
      ],
    },
    {
      id: 'pf-handover',
      title: 'Final Handover & Close-Out',
      items: [
        { id: 'pf-ho-001', text: 'All penetrations sealed and inspected', mandatory: true },
        { id: 'pf-ho-002', text: 'Final documentation accepted by Main Contractor', mandatory: true },
        { id: 'pf-ho-003', text: 'Authority or council inspections passed where required', mandatory: false },
        { id: 'pf-ho-004', text: 'Variations agreed and finalised', mandatory: true },
        { id: 'pf-ho-005', text: 'Practical Completion sign-off obtained', mandatory: true },
      ],
    },
  ],

  riskRegister: [
    {
      id: 'rr-pf-001',
      category: 'Programme',
      risk: 'Late access to penetrations before close-in',
      cause: 'Other trades close walls/ceilings before passive fire sealing is complete',
      consequence: 'Rework, cost disputes, programme delays',
      likelihood: 'high',
      impact: 'high',
      mitigation: 'Establish formal hold-point programme. No close-in without passive fire sign-off.',
      owner: 'Site Manager',
    },
    {
      id: 'rr-pf-002',
      category: 'Scope Clarity',
      risk: 'Penetration quantity growth beyond estimate',
      cause: 'Incomplete coordinated drawings at tender, late design changes',
      consequence: 'Significant variation exposure, programme impact',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Issue coordinated penetration schedule at tender. Include provisional sum for growth allowance.',
      owner: 'Quantity Surveyor',
    },
    {
      id: 'rr-pf-003',
      category: 'Quality & Compliance',
      risk: 'Incorrect FRR product used for penetration type',
      cause: 'Insufficient installer training, product substitution, unclear specification',
      consequence: 'Failed inspection, remediation cost, compliance liability',
      likelihood: 'medium',
      impact: 'critical',
      mitigation: 'Product-specific training required. Maintain tested assembly schedule on site. No substitutions without fire engineer approval.',
      owner: 'Site Manager / Fire Engineer',
    },
    {
      id: 'rr-pf-004',
      category: 'Documentation',
      risk: 'Missing photographic records for concealed penetrations',
      cause: 'Inadequate inspection regime, rushed programme',
      consequence: 'Cannot demonstrate compliance, PS3 not issuable, certification delays',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Mandatory photo register before any concealment. Hold point approval process.',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-pf-005',
      category: 'Interface Risk',
      risk: 'Coordination disputes with other trades on penetration ownership',
      cause: 'Unclear scope boundaries for sealing responsibility',
      consequence: 'Unsealed penetrations, liability disputes, compliance gaps',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Written interface matrix agreed pre-start. Penetration responsibility schedule issued.',
      owner: 'Contract Administrator',
    },
  ],

  complianceRequirements: [
    { id: 'pf-comp-001', label: 'Fire Engineering Approval', description: 'All products and assemblies approved by fire engineer', mandatory: true, region: 'both' },
    { id: 'pf-comp-002', label: 'PS3 Producer Statement (NZ)', description: 'PS3 Construction statement issued for passive fire works', mandatory: false, region: 'NZ' },
    { id: 'pf-comp-003', label: 'Photographic Inspection Records', description: 'Photo register for every penetration sealed', mandatory: true, region: 'both' },
    { id: 'pf-comp-004', label: 'Tested Assembly Certificates', description: 'Manufacturer FRR test certificates for all products used', mandatory: true, region: 'both' },
  ],

  validationRules: [
    { id: 'val-pf-001', check: 'scope_not_empty', message: 'At least one penetration system must be included in scope', severity: 'error' },
    { id: 'val-pf-002', check: 'clauses_include_testing', message: 'Inspection and certification clause must be included', severity: 'error' },
    { id: 'val-pf-003', check: 'checklist_documentation_complete', message: 'Documentation phase checklist must be completed before handover', severity: 'warning' },
  ],

  awardWording: {
    approved: {
      status: 'Approved / Recommended for Award',
      template: `**Recommendation: APPROVED FOR AWARD**\n\nThis Passive Fire Protection submission demonstrates:\n• Adequate scope coverage of fire-rated penetrations per fire engineering requirements\n• Clear product compliance and FRR certification pathway\n• Appropriate inspection and documentation provisions\n• Reasonable programme and access provisions\n\nThe submission is recommended for award subject to standard commercial clarifications and hold-point programme confirmation.`,
    },
    clarificationRequired: {
      status: 'Clarification Required Prior to Award',
      template: `**Recommendation: CLARIFICATION REQUIRED**\n\nThis Passive Fire Protection submission requires clarification on:\n• Product compliance and FRR certification approach\n• Penetration quantity inclusions and exclusions\n• Inspection hold-point programme\n• PS3 scope and certification pathway\n• [Specific commercial or technical clarifications]\n\nSubject to satisfactory clarification, the submission may be suitable for award.`,
    },
    notRecommended: {
      status: 'Not Recommended for Award',
      template: `**Recommendation: NOT RECOMMENDED FOR AWARD**\n\nThis Passive Fire Protection submission presents material compliance and delivery risks:\n• Insufficient FRR product compliance or certification coverage\n• Inadequate inspection provisions\n• Documentation and PS3 gaps\n• [Specific deficiencies]\n\nThe submission is not recommended for award without material scope and commercial amendments.`,
    },
  },
};
