import type { TradeSpec } from '../types';

export const plumbingSpec: TradeSpec = {
  tradeModule: 'plumbing',
  name: 'Plumbing',
  color: 'blue',
  accentHex: '#3b82f6',
  description: 'Plumbing, hydraulics and drainage systems',
  normalizationStrategy: 'system_based',

  scopeCategories: [
    'Cold Water Services',
    'Hot Water Services',
    'Sanitary Plumbing & Drainage',
    'Stormwater Drainage',
    'Plant Connections',
    'Fixtures & Fit-off',
    'Backflow Prevention',
    'Pumps & Pressure Equipment',
    'Other Systems',
  ],

  groupingRules: [
    { groupName: 'Cold Water Services', keywords: ['cold water', 'potable', 'cwf', 'cws', 'cold supply'] },
    { groupName: 'Hot Water Services', keywords: ['hot water', 'hwf', 'hws', 'heated water', 'tmv', 'temperature'] },
    { groupName: 'Sanitary Plumbing & Drainage', keywords: ['sanitary', 'waste', 'vent', 'sewer', 'soil', 'drainage', 'trap'] },
    { groupName: 'Stormwater Drainage', keywords: ['stormwater', 'rainwater', 'downpipe', 'gutter', 'storm'] },
    { groupName: 'Plant Connections', keywords: ['plant connection', 'mechanical connection', 'equipment connection'] },
    { groupName: 'Fixtures & Fit-off', keywords: ['fixture', 'basin', 'sink', 'toilet', 'wc', 'urinal', 'shower', 'fitout'] },
    { groupName: 'Backflow Prevention', keywords: ['backflow', 'rp valve', 'dca', 'prevention'] },
    { groupName: 'Pumps & Pressure Equipment', keywords: ['pump', 'prv', 'pressure', 'booster', 'strainer'] },
  ],

  contractClauses: [
    {
      id: 'plumb-001',
      title: 'Scope & Deliverables (Plumbing/Hydraulics)',
      category: 'scope',
      mandatory: true,
      body: `The Subcontractor shall supply, install, test, commission and hand over the Plumbing/Hydraulics works as shown on the contract drawings, specifications, hydraulic schematics, and coordinated services layouts current at the date of subcontract.\n\n**Included (unless expressly excluded):**\n• Potable (cold) water reticulation, valves, isolation, and identification\n• Heated water services distribution and temperature control devices\n• Sanitary plumbing, wastes, vents and connections within the building footprint\n• Stormwater drainage within the building footprint (where shown)\n• Plant connections to nominated mechanical equipment (where indicated)\n• Fixtures and fit-off items specifically scheduled or detailed\n• Supports, brackets, fixings and penetrations coordination\n• Backflow prevention devices where specified\n• Testing, commissioning and certification within scope`,
    },
    {
      id: 'plumb-002',
      title: 'Exclusions / By Others',
      category: 'exclusions',
      mandatory: true,
      body: `The following are excluded unless explicitly included in the subcontract scope:\n\n• Builder's works (structural penetrations, coring, chasing, patching, structural supports)\n• Excavation, trenching, backfill, reinstatement and traffic management\n• Authority service upgrades, offsite works, meter supply and authority connection fees\n• Roofing works including flashings and waterproofing (unless specified)\n• Third-party testing not defined in specification (council/authority witnessing)\n• Electrical power and control wiring to pumps, heaters and equipment\n• Asbestos or hazardous material remediation\n\n**Clarification Principle:**\nWhere responsibilities overlap, the parties shall agree in writing prior to work proceeding.`,
    },
    {
      id: 'plumb-003',
      title: 'Interfaces & Coordination',
      category: 'interfaces',
      mandatory: true,
      body: `The Subcontractor shall coordinate interfaces with:\n\n• Civil drainage (stormwater and sanitary outfalls, invert levels, manholes)\n• Fire services (shared risers, plantrooms, isolation and clearances)\n• Mechanical (plant connections, penetrations, condensate interfaces)\n• Electrical (power to pumps/heaters, controls, isolators)\n• Passive fire (penetrations requiring fire stopping, access for sealing)\n\n**Interface Responsibility:**\n• Plumbing subcontractor responsible for hydraulic installation to points of connection shown\n• Other trades responsible for their own works unless expressly included\n• Coordination drawings agreed with Main Contractor before installation`,
    },
    {
      id: 'plumb-004',
      title: 'Testing & Commissioning Requirements',
      category: 'testing',
      mandatory: true,
      body: `The Subcontractor shall complete testing and commissioning including as a minimum:\n\n• Pressure testing of water services (recorded results)\n• Drainage testing where required (water or air test as specified)\n• Functional testing of valves, isolation and fixture operation\n• Temperature verification and commissioning of TMVs where included\n• Backflow prevention testing and certification by an authorised person\n\nThe Subcontractor shall provide test records, commissioning sheets and certification required by the contract and/or consenting authority.`,
    },
    {
      id: 'plumb-005',
      title: 'As-Built Documentation & O&M Manuals',
      category: 'documentation',
      mandatory: true,
      body: `The Subcontractor shall provide:\n\n• Marked-up as-builts updated to as-installed status\n• Asset register for maintainable items (pumps, TMVs, backflow devices)\n• O&M manuals and manufacturer datasheets for supplied equipment\n• Warranty certificates and recommended maintenance schedules\n• Test certificates (pressure, drainage, backflow)\n• Backflow prevention certification and asset register\n• Producer Statements / compliance documentation where contract requires (NZ)`,
    },
    {
      id: 'plumb-006',
      title: 'Variations',
      category: 'variations',
      mandatory: true,
      body: `Any change to scope, design, specification, setout, access or programme constraints that impacts time or cost shall be treated as a variation, provided notice is given prior to works proceeding.\n\n**Provisional Sums:**\nWhere allowances apply, the basis, inclusions and rates shall be documented. Drawdown requires reasonable supporting evidence and Main Contractor approval.`,
    },
    {
      id: 'plumb-007',
      title: 'Programme, Access & Shutdowns',
      category: 'programme',
      mandatory: true,
      body: `**Access & Sequencing:**\nThe Main Contractor will provide reasonable access and coordinate with other trades. Where access is restricted, the parties will agree resequencing.\n\n**Shutdowns / Tie-ins:**\nWhere tie-ins to live services are required, the Subcontractor will provide required notice and method statements. The Main Contractor will coordinate approvals and stakeholder notifications.`,
    },
    {
      id: 'plumb-008',
      title: 'Quality, Defects & Close-Out',
      category: 'quality',
      mandatory: true,
      body: `The Subcontractor shall deliver works compliant with the contract documentation and shall rectify defects attributable to its work within a reasonable timeframe. Defects arising from design changes, builder's works issues, third-party damage, or other trade interference shall be treated as coordination items and variations where appropriate.`,
    },
  ],

  checklistPhases: [
    {
      id: 'plumb-pre-start',
      title: 'Pre-Start Checklist',
      items: [
        { id: 'plumb-pre-001', text: 'Site induction completed (plumbing/hydraulics hazards)', mandatory: true },
        { id: 'plumb-pre-002', text: 'Plumbing SWMS reviewed and approved', mandatory: true },
        { id: 'plumb-pre-003', text: 'Supervisor/licence/competency verified (NZ: licensed certifier; AU: licensed plumber)', mandatory: true },
        { id: 'plumb-pre-004', text: 'Latest drawings, specs and coordination drawings available', mandatory: true },
        { id: 'plumb-pre-005', text: 'Penetration/setout coordination confirmed (builder + passive fire)', mandatory: true },
        { id: 'plumb-pre-006', text: 'Builders works responsibilities confirmed (core holes, trenches, plinths)', mandatory: true },
        { id: 'plumb-pre-007', text: 'Material approvals confirmed (pipe types, valves, fixtures, backflow)', mandatory: true },
        { id: 'plumb-pre-008', text: 'Long-lead items confirmed (fixtures, pumps, TMVs, backflow devices)', mandatory: true },
        { id: 'plumb-pre-009', text: 'Water shutdowns and tie-in windows confirmed (if live building)', mandatory: false },
        { id: 'plumb-pre-010', text: 'Interface responsibilities confirmed (civil, fire, mechanical, electrical)', mandatory: true },
      ],
    },
    {
      id: 'plumb-installation',
      title: 'Installation Checklist',
      items: [
        { id: 'plumb-inst-001', text: 'Pipework installed to drawings/specs with correct materials and supports', mandatory: true },
        { id: 'plumb-inst-002', text: 'Pipe gradients/falls confirmed for drainage', mandatory: true },
        { id: 'plumb-inst-003', text: 'Isolation valves installed and accessible', mandatory: true },
        { id: 'plumb-inst-004', text: 'Backflow prevention devices installed to approved locations and standards', mandatory: true },
        { id: 'plumb-inst-005', text: 'Hot water systems installed and TMVs fitted where required', mandatory: true },
        { id: 'plumb-inst-006', text: 'Fixtures and fit-off installed as specified', mandatory: true },
        { id: 'plumb-inst-007', text: 'Pump sets, PRVs and strainers installed where applicable', mandatory: false },
        { id: 'plumb-inst-008', text: 'Acoustic and seismic restraints installed where required', mandatory: true },
        { id: 'plumb-inst-009', text: 'Insulation installed where specified (thermal/condensation)', mandatory: false },
        { id: 'plumb-inst-010', text: 'Roof penetrations and flashings coordinated and completed (if in scope)', mandatory: false },
        { id: 'plumb-inst-011', text: 'No unapproved deviations from approved scope', mandatory: true },
      ],
    },
    {
      id: 'plumb-quality',
      title: 'Quality Control & Testing',
      items: [
        { id: 'plumb-qc-001', text: 'Visual inspection completed for all pipework', mandatory: true },
        { id: 'plumb-qc-002', text: 'Pressure testing completed and recorded (water services)', mandatory: true },
        { id: 'plumb-qc-003', text: 'Drainage testing completed (water test/air test per spec)', mandatory: true },
        { id: 'plumb-qc-004', text: 'Backflow devices tested by authorised person; results recorded', mandatory: true },
        { id: 'plumb-qc-005', text: 'Hot water temperatures verified and recorded (TMVs set and tested)', mandatory: true },
        { id: 'plumb-qc-006', text: 'Leak checks completed at all joints and fixtures', mandatory: true },
        { id: 'plumb-qc-007', text: 'Pumps and controls tested', mandatory: false },
        { id: 'plumb-qc-008', text: 'Defects logged and rectified', mandatory: true },
      ],
    },
    {
      id: 'plumb-documentation',
      title: 'Documentation & Certification (Critical)',
      items: [
        { id: 'plumb-doc-001', text: 'Test certificates compiled (pressure, drainage, backflow)', mandatory: true },
        { id: 'plumb-doc-002', text: 'Backflow prevention certification and asset register provided', mandatory: true },
        { id: 'plumb-doc-003', text: 'As-built drawings completed', mandatory: true },
        { id: 'plumb-doc-004', text: 'O&M manuals compiled (pumps, heaters, valves, backflow, controls)', mandatory: true },
        { id: 'plumb-doc-005', text: 'Warranties provided for fixtures and equipment', mandatory: true },
        { id: 'plumb-doc-006', text: 'Commissioning sheets provided', mandatory: true },
        { id: 'plumb-doc-007', text: 'Producer Statements / compliance documentation where required (NZ)', mandatory: false, notes: 'PS3/PS4 required by NZ councils for consented plumbing works' },
        { id: 'plumb-doc-008', text: 'Maintenance schedules provided (filters, backflow retest intervals)', mandatory: true },
      ],
    },
    {
      id: 'plumb-handover',
      title: 'Final Handover & Close-Out',
      items: [
        { id: 'plumb-ho-001', text: 'Systems operational and demonstrated', mandatory: true },
        { id: 'plumb-ho-002', text: 'Final tie-ins completed and water services restored', mandatory: true },
        { id: 'plumb-ho-003', text: 'Training provided to FM/client (isolation, backflow maintenance)', mandatory: true },
        { id: 'plumb-ho-004', text: 'Defects list closed', mandatory: true },
        { id: 'plumb-ho-005', text: 'Variations agreed and finalised', mandatory: true },
        { id: 'plumb-ho-006', text: 'Final documentation accepted', mandatory: true },
        { id: 'plumb-ho-007', text: 'Practical Completion sign-off obtained', mandatory: true },
      ],
    },
  ],

  riskRegister: [
    {
      id: 'rr-plumb-001',
      category: 'Programme',
      risk: 'Shutdown windows and live tie-in constraints',
      cause: 'Live building, restricted access, authority approvals',
      consequence: 'Programme delays, resequencing cost',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Tie-in plan, hold points, resequencing provisions in contract',
      owner: 'Project Manager',
    },
    {
      id: 'rr-plumb-002',
      category: 'Scope Clarity',
      risk: 'Builders works and authority connection exclusions unclear',
      cause: 'Ambiguous specification, inconsistent drawings',
      consequence: 'Variation claims, scope gaps',
      likelihood: 'high',
      impact: 'high',
      mitigation: 'Confirm inclusion schedule and interface matrix pre-award',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-plumb-003',
      category: 'Quality & Compliance',
      risk: 'TMV and backflow compliance failures',
      cause: 'Incorrect specification, unlicensed work, testing gaps',
      consequence: 'Failed inspection, public health risk, remediation',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Commissioning sheets, authorised testing, records maintained',
      owner: 'Site Manager',
    },
    {
      id: 'rr-plumb-004',
      category: 'Testing & Commissioning',
      risk: 'Pressure and drainage tests not witnessed or recorded',
      cause: 'Rushed programme, inadequate inspection regime',
      consequence: 'Certification delays, compliance gaps',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Testing plan, scheduled inspections, signed records',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-plumb-005',
      category: 'Interface Risk',
      risk: 'Civil, fire, mechanical and electrical boundary disputes',
      cause: 'Unclear scope at interfaces',
      consequence: 'Scope gaps, variation claims',
      likelihood: 'high',
      impact: 'high',
      mitigation: 'Written interface matrix, coordination workshops',
      owner: 'Contract Administrator',
    },
    {
      id: 'rr-plumb-006',
      category: 'Supply Chain',
      risk: 'Fixtures, pumps, TMVs and backflow devices on long lead',
      cause: 'Supply chain disruption, specialist requirements',
      consequence: 'Programme delays',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Early procurement, approved alternatives, supply tracking',
      owner: 'Procurement Manager',
    },
    {
      id: 'rr-plumb-007',
      category: 'Access & Coordination',
      risk: 'Stack alignment and riser penetration clashes',
      cause: 'Inadequate 3D coordination',
      consequence: 'Rework, disputes, programme delays',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: '3D coordination, setout workshops, coordination drawings',
      owner: 'Services Coordinator',
    },
    {
      id: 'rr-plumb-008',
      category: 'Commercial',
      risk: 'Provisional sum exposure and variation disputes',
      cause: 'Unclear PS scope, late design changes',
      consequence: 'Commercial overrun, disputes',
      likelihood: 'medium',
      impact: 'medium',
      mitigation: 'Variation process agreed, PS/PC register maintained',
      owner: 'Quantity Surveyor',
    },
    {
      id: 'rr-plumb-009',
      category: 'Authority/Utility Dependencies',
      risk: 'Water authority delays, meter connections and approvals',
      cause: 'Authority processing times, upgrade works required',
      consequence: 'Delayed commissioning, programme impact',
      likelihood: 'medium',
      impact: 'high',
      mitigation: 'Early engagement with water authority, programme float',
      owner: 'Project Manager',
    },
  ],

  complianceRequirements: [
    { id: 'plumb-comp-001', label: 'Licensed Certifier (NZ)', description: 'Licensed Building Practitioner — Plumbing certifier', mandatory: true, region: 'NZ' },
    { id: 'plumb-comp-002', label: 'Licensed Plumber (AU)', description: 'Licensed plumber for all hydraulic works', mandatory: true, region: 'AU' },
    { id: 'plumb-comp-003', label: 'Backflow Certification', description: 'Backflow prevention testing by authorised person, asset register', mandatory: true, region: 'both' },
    { id: 'plumb-comp-004', label: 'TMV Commissioning Records', description: 'Temperature verification and commissioning sheets for all TMVs', mandatory: true, region: 'both' },
    { id: 'plumb-comp-005', label: 'Pressure Test Certificates', description: 'Signed pressure test records for water services', mandatory: true, region: 'both' },
    { id: 'plumb-comp-006', label: 'PS3 Plumbing (NZ)', description: 'Producer Statement Construction for plumbing works', mandatory: false, region: 'NZ' },
  ],

  validationRules: [
    { id: 'val-plumb-001', check: 'backflow_certification_required', message: 'Backflow certification clause must be included', severity: 'error' },
    { id: 'val-plumb-002', check: 'pressure_testing_in_checklist', message: 'Pressure testing must appear in quality checklist', severity: 'error' },
    { id: 'val-plumb-003', check: 'tmv_commissioning_included', message: 'TMV commissioning should be included if hot water systems are in scope', severity: 'warning' },
    { id: 'val-plumb-004', check: 'licensed_certifier_requirement', message: 'Licensed certifier/plumber clause must be included', severity: 'error' },
  ],

  awardWording: {
    approved: {
      status: 'Approved / Recommended for Award',
      template: `**Recommendation: APPROVED FOR AWARD**\n\nThis Plumbing/Hydraulics submission demonstrates:\n• Comprehensive scope coverage consistent with hydraulic drawings and specification\n• Clear compliance pathway (licensed certifier, backflow certification, TMV commissioning)\n• Appropriate testing, commissioning and certification provisions\n• Suitable interface management with civil, mechanical and electrical trades\n• Adequate documentation and O&M provisions\n\nThe submission is recommended for award subject to standard commercial clarifications.`,
    },
    clarificationRequired: {
      status: 'Clarification Required Prior to Award',
      template: `**Recommendation: CLARIFICATION REQUIRED**\n\nThis Plumbing/Hydraulics submission requires clarification on:\n• Backflow certification scope and authorised person arrangements\n• Civil drainage interface responsibilities\n• TMV commissioning and temperature verification approach\n• Builders works inclusions/exclusions\n• [Specific technical or commercial clarifications]\n\nSubject to satisfactory clarification, the submission may be suitable for award.`,
    },
    notRecommended: {
      status: 'Not Recommended for Award',
      template: `**Recommendation: NOT RECOMMENDED FOR AWARD**\n\nThis Plumbing/Hydraulics submission presents compliance and delivery risks:\n• Insufficient backflow and TMV compliance provisions\n• Inadequate pressure testing and certification approach\n• Scope gaps relative to hydraulic drawings and specification\n• [Specific deficiencies]\n\nNot recommended for award without material amendments.`,
    },
  },
};
