/**
 * Modern Handover Pack Generators with VerifyTrade Branding
 * Matches Award Report design and styling
 */

const VERIFYTRADE_ORANGE = '#f97316';
const VERIFYTRADE_ORANGE_LIGHT = '#fed7aa';
const VERIFYTRADE_ORANGE_DARK = '#ea580c';

function generateLogoSection(organisationLogoUrl?: string): string {
  if (organisationLogoUrl) {
    return `
      <div class="logo-section">
        <img
          src="${organisationLogoUrl}"
          alt="Organisation Logo"
          style="max-width: 140px; max-height: 52px; object-fit: contain;"
        />
        <div style="border-left: 2px solid #e5e7eb; height: 52px; margin: 0 12px;"></div>
        <div class="logo-text">VerifyTrade</div>
      </div>`;
  } else {
    return `
      <div class="logo-section">
        <div class="logo-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
            <path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"/>
          </svg>
        </div>
        <div class="logo-text">VerifyTrade</div>
      </div>`;
  }
}

export function generateJuniorPackHTML(
  projectName: string,
  supplierName: string,
  scopeSystems: any[],
  inclusions: string[],
  exclusions: string[],
  organisationLogoUrl?: string
): string {
  const systemsHTML = scopeSystems.map((sys, index) => {
    const detailsHTML = sys.details && sys.details.length > 0
      ? `<ul class="detail-list">${sys.details.map((d: string) => `<li>${d}</li>`).join('')}</ul>`
      : '';

    const isFirst = index === 0;
    const header = isFirst
      ? `<header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header><h2>Scope of Works Overview</h2>`
      : `<header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>`;

    return `<div class="page">
      ${header}
      <div class="system-card">
        <h4>${sys.service_type}</h4>
        <p class="item-count">${sys.item_count} items</p>
        ${detailsHTML}
      </div>
    </div>`;
  }).join('');

  const inclusionsHTML = inclusions.length > 0
    ? `<h2>Scope Inclusions</h2><ul class="checklist">${inclusions.map(i => `<li><input type="checkbox" disabled> ${i}</li>`).join('')}</ul>`
    : '';

  const exclusionsHTML = exclusions.length > 0
    ? `<h2>Scope Exclusions</h2><div class="warning-box"><h3>Not Included in Scope</h3><ul>${exclusions.map(e => `<li class="safety-item">${e}</li>`).join('')}</ul></div>`
    : '';

  const year = new Date().getFullYear();
  const generatedDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Junior Site Team Handover Pack - ${projectName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Helvetica Neue', Arial, sans-serif; font-size: 14px; line-height: 1.6; color: #1f2937; background: white; padding: 0; -webkit-font-smoothing: antialiased; }
    @page { size: A4; margin: 15mm 12mm; }
    .page { page-break-after: always; padding: 32px; }
    .page:last-child { page-break-after: auto; }
    header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 24px; padding-bottom: 12px; border-bottom: 3px solid ${VERIFYTRADE_ORANGE}; }
    .logo-section { display: flex; align-items: center; gap: 12px; }
    .logo-icon { width: 52px; height: 52px; background: linear-gradient(135deg, ${VERIFYTRADE_ORANGE} 0%, ${VERIFYTRADE_ORANGE_DARK} 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center; box-shadow: 0 4px 8px rgba(249, 115, 22, 0.25); }
    .logo-text { font-size: 26px; font-weight: 700; color: #111827; letter-spacing: -0.5px; }
    .generated-by { text-align: right; font-size: 12px; color: #6b7280; }
    .generated-by strong { color: ${VERIFYTRADE_ORANGE}; font-weight: 600; }
    footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; display: flex; justify-content: space-between; align-items: center; font-size: 11px; color: #9ca3af; }
    @page { @bottom-right { content: "Page " counter(page); } }
    footer .page-number:after { content: "Page " counter(page); }
    .cover-page { display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; min-height: 80vh; }
    h1 { font-size: 46px; font-weight: 800; color: #111827; letter-spacing: -1.2px; line-height: 1.1; margin-bottom: 12px; }
    .subtitle { font-size: 22px; color: #6b7280; font-weight: 400; margin-bottom: 48px; }
    h2 { font-size: 28px; font-weight: 700; color: #111827; letter-spacing: -0.5px; margin-bottom: 20px; padding-bottom: 8px; border-bottom: 2px solid #f3f4f6; }
    h3 { font-size: 20px; font-weight: 600; color: #374151; margin-bottom: 14px; }
    .project-details-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 32px; margin: 40px 0; text-align: left; width: 100%; max-width: 600px; }
    .project-details-card .detail-row { display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid #e5e7eb; }
    .project-details-card .detail-row:last-child { border-bottom: none; }
    .project-details-card .detail-label { font-weight: 600; color: #6b7280; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
    .project-details-card .detail-value { font-weight: 600; color: #111827; font-size: 15px; }
    .system-card { background: white; border: 2px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
    .system-card h4 { color: ${VERIFYTRADE_ORANGE}; font-size: 16px; margin-bottom: 6px; }
    .item-count { font-size: 12px; color: #6b7280; margin-bottom: 10px; font-weight: 500; }
    .detail-list { list-style: none; font-size: 12px; color: #4b5563; padding-left: 0; column-count: 2; column-gap: 16px; }
    .detail-list li { padding: 6px 0; padding-left: 20px; position: relative; line-height: 1.6; break-inside: avoid; }
    .detail-list li:before { content: "✓"; position: absolute; left: 0; color: #10b981; font-weight: 700; }
    .warning-box { background: #fef3c7; border-left: 4px solid #f59e0b; border-radius: 0 8px 8px 0; padding: 16px 20px; margin: 16px 0; line-height: 1.7; }
    .warning-box h3 { font-weight: 700; font-size: 15px; color: #92400e; margin-bottom: 10px; }
    .warning-box ul { list-style: none; padding-left: 0; }
    .safety-item { display: flex; align-items: flex-start; margin-bottom: 10px; line-height: 1.6; color: #78350f; }
    .safety-item:before { content: "⚠"; display: inline-flex; align-items: center; justify-content: center; width: 22px; height: 22px; background: #f59e0b; color: white; border-radius: 50%; margin-right: 10px; flex-shrink: 0; font-weight: 700; font-size: 13px; }
    .checklist-section { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 18px; margin-bottom: 14px; }
    .checklist-section h3 { font-size: 17px; color: #111827; margin-bottom: 12px; font-weight: 600; }
    .checklist { list-style: none; padding-left: 0; }
    .checklist li { padding: 10px 0; font-size: 13px; border-bottom: 1px solid #e5e7eb; display: flex; align-items: center; color: #374151; }
    .checklist li:last-child { border-bottom: none; }
    .checklist input[type="checkbox"] { margin-right: 10px; width: 16px; height: 16px; flex-shrink: 0; }
    @media print { body { print-color-adjust: exact; -webkit-print-color-adjust: exact; } .page-break { page-break-after: always; break-after: page; } }
  </style>
</head>
<body>
  <div class="page cover-page">
    <div style="flex: 1; display: flex; flex-direction: column; justify-content: center; align-items: center;">
      <h1 style="text-align: center;">Junior Site Team Handover Pack</h1>
      <div class="subtitle" style="text-align: center;">Practical Guide for On-Site Installation & Quality Control</div>
      <div class="project-details-card">
        <div class="detail-row"><span class="detail-label">Project</span><span class="detail-value">${projectName}</span></div>
        <div class="detail-row"><span class="detail-label">Subcontractor</span><span class="detail-value">${supplierName}</span></div>
      </div>
      <div style="margin-top: 60px;">
        ${generateLogoSection(organisationLogoUrl)}
        <div style="font-size: 13px; color: #6b7280; margin-top: 12px; text-align: center;">Generated ${generatedDate}</div>
      </div>
    </div>
    <footer style="text-align: right; margin-top: auto;"><div style="color: ${VERIFYTRADE_ORANGE}; font-weight: 600;">Generated by VerifyTrade</div></footer>
  </div>

  ${systemsHTML}

  <div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    <div class="warning-box">
      <h3>Safety & Installation Notes</h3>
      <ul>
        <li class="safety-item">All personnel must complete site induction before commencing work</li>
        <li class="safety-item">Use appropriate PPE: Hard hat, safety glasses, high-vis vest, safety boots</li>
        <li class="safety-item">Follow manufacturer's instructions for all fire protection materials</li>
      </ul>
    </div>
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div class="page-number"></div></footer>
  </div>

  <div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    <h2>Site Handover Checklists</h2>
    <div class="checklist-section"><h3>Pre-Start Checklist</h3><ul class="checklist">
      <li><input type="checkbox" disabled> Site induction completed</li>
      <li><input type="checkbox" disabled> SWMS reviewed and signed</li>
      <li><input type="checkbox" disabled> All required materials and equipment on site</li>
    </ul></div>
    <div class="checklist-section"><h3>Installation Checklist</h3><ul class="checklist">
      <li><input type="checkbox" disabled> Verify penetration dimensions against drawings</li>
      <li><input type="checkbox" disabled> Check FRR requirements</li>
      <li><input type="checkbox" disabled> Apply products as per manufacturer specifications</li>
    </ul></div>
    <div class="checklist-section"><h3>Quality Control</h3><ul class="checklist">
      <li><input type="checkbox" disabled> Photograph all completed penetrations</li>
      <li><input type="checkbox" disabled> Complete QA documentation for each penetration</li>
      <li><input type="checkbox" disabled> Ensure PS3 documentation is prepared</li>
    </ul></div>
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div class="page-number"></div></footer>
  </div>

  ${inclusionsHTML || exclusionsHTML ? `<div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    ${inclusionsHTML}
    ${exclusionsHTML}
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div class="page-number"></div></footer>
  </div>` : ''}
</body>
</html>`;
}

export function generateSeniorReportHTML(
  projectName: string,
  supplierName: string,
  totalAmount: number,
  scopeSystems: any[],
  inclusions: string[],
  exclusions: string[],
  organisationLogoUrl?: string,
  additionalData?: any
): string {
  const retentionPercentage = additionalData?.retentionPercentage || 3;
  const retentionAmount = totalAmount * (retentionPercentage / 100);
  const netAmount = totalAmount - retentionAmount;

  const formatCurrency = (value: number) => {
    return `$${value.toLocaleString('en-NZ', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  const awardSummary = additionalData?.awardReport?.awardSummary || {};
  const suppliers = awardSummary.suppliers || [];
  const benchmarkData = suppliers.length > 1 ? suppliers : [];

  const inclusionsHTML = inclusions.length > 0
    ? `<div style="margin-top: 24px;"><h3>Scope Inclusions</h3><ul style="list-style: disc; margin-left: 20px;">${inclusions.map(i => `<li style="margin: 8px 0;">${i}</li>`).join('')}</ul></div>`
    : '';

  const exclusionsHTML = exclusions.length > 0
    ? `<div style="margin-top: 24px;"><h3>Scope Exclusions</h3><ul style="list-style: disc; margin-left: 20px; color: #ef4444;">${exclusions.map(e => `<li style="margin: 8px 0;">${e}</li>`).join('')}</ul></div>`
    : '';

  const pieColors = ['#3b82f6','#10b981','#f59e0b','#ef4444','#8b5cf6','#ec4899','#06b6d4','#84cc16'];
  let currentAngle = -90;
  const paths = scopeSystems.map((sys, idx) => {
    const angle = (sys.percentage / 100) * 360;
    const startAngle = currentAngle;
    const endAngle = currentAngle + angle;
    const startRad = (startAngle * Math.PI) / 180;
    const endRad = (endAngle * Math.PI) / 180;
    const x1 = 100 + 90 * Math.cos(startRad);
    const y1 = 100 + 90 * Math.sin(startRad);
    const x2 = 100 + 90 * Math.cos(endRad);
    const y2 = 100 + 90 * Math.sin(endRad);
    const largeArc = angle > 180 ? 1 : 0;
    currentAngle = endAngle;
    return `<path d="M 100 100 L ${x1} ${y1} A 90 90 0 ${largeArc} 1 ${x2} ${y2} Z" fill="${pieColors[idx % pieColors.length]}" stroke="white" stroke-width="2"/>`;
  }).join('');

  const legend = scopeSystems.map((sys, idx) => `
    <div style="display: flex; align-items: center; gap: 8px; font-size: 13px;">
      <div style="width: 12px; height: 12px; border-radius: 2px; background-color: ${pieColors[idx % pieColors.length]};"></div>
      <div style="flex: 1; color: #475569;">${sys.service_type}</div>
      <div style="font-weight: 600; color: #1e293b;">${sys.percentage.toFixed(1)}%</div>
    </div>
  `).join('');

  const scopeDetailsHTML = scopeSystems.map(sys => {
    // Calculate grid dimensions: prefer 3 columns for readability
    const itemsPerRow = 3;
    const totalRows = Math.ceil(sys.details.length / itemsPerRow);

    return `
    <div style="margin-bottom: 32px; page-break-inside: avoid;">
      <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #e5e7eb;">
        ${sys.service_type} (${sys.item_count} items) · ${totalRows} rows × ${itemsPerRow} columns
      </h3>
      <div style="background: #f9fafb; border-radius: 8px; padding: 16px;">
        <div style="
          display: grid;
          grid-template-columns: repeat(${itemsPerRow}, 1fr);
          gap: 12px;
          margin: 0;
        ">
          ${sys.details.map((d: string) => `
            <div style="
              padding: 10px 12px;
              background: white;
              border: 1px solid #e5e7eb;
              border-radius: 6px;
              font-size: 13px;
              color: #374151;
              break-inside: avoid;
              position: relative;
              padding-left: 28px;
              line-height: 1.5;
              min-height: 40px;
              display: flex;
              align-items: center;
            ">
              <span style="position: absolute; left: 10px; top: 50%; transform: translateY(-50%); color: #10b981; font-weight: 700; font-size: 14px;">✓</span>
              <span>${d}</span>
            </div>
          `).join('')}
        </div>
      </div>
    </div>
  `;
  }).join('');

  const year = new Date().getFullYear();
  const generatedDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Senior Project Team Overview - ${projectName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Helvetica Neue', Arial, sans-serif; font-size: 14px; line-height: 1.6; color: #1f2937; background: white; padding: 0; -webkit-font-smoothing: antialiased; }
    @page { size: A4; margin: 15mm 12mm; }
    .page { page-break-after: always; padding: 32px; }
    .page:last-child { page-break-after: auto; }
    header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 24px; padding-bottom: 12px; border-bottom: 3px solid ${VERIFYTRADE_ORANGE}; }
    .logo-section { display: flex; align-items: center; gap: 12px; }
    .logo-icon { width: 52px; height: 52px; background: linear-gradient(135deg, ${VERIFYTRADE_ORANGE} 0%, ${VERIFYTRADE_ORANGE_DARK} 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center; box-shadow: 0 4px 8px rgba(249, 115, 22, 0.25); }
    .logo-text { font-size: 26px; font-weight: 700; color: #111827; letter-spacing: -0.5px; }
    .generated-by { text-align: right; font-size: 12px; color: #6b7280; }
    .generated-by strong { color: ${VERIFYTRADE_ORANGE}; font-weight: 600; }
    footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; display: flex; justify-content: space-between; align-items: center; font-size: 11px; color: #9ca3af; }
    @page { @bottom-right { content: "Page " counter(page); } }
    .cover-page { display: flex; flex-direction: column; justify-content: center; align-items: center; text-align: center; min-height: 80vh; }
    h1 { font-size: 46px; font-weight: 800; color: #111827; letter-spacing: -1.2px; line-height: 1.1; margin-bottom: 12px; }
    .subtitle { font-size: 22px; color: #6b7280; font-weight: 400; margin-bottom: 48px; }
    h2 { font-size: 28px; font-weight: 700; color: #111827; letter-spacing: -0.5px; margin-bottom: 20px; padding-bottom: 8px; border-bottom: 2px solid #f3f4f6; }
    h3 { font-size: 20px; font-weight: 600; color: #374151; margin-bottom: 14px; }
    .project-details-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 32px; margin: 40px 0; text-align: left; width: 100%; max-width: 600px; }
    .project-details-card .detail-row { display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid #e5e7eb; }
    .project-details-card .detail-row:last-child { border-bottom: none; }
    .project-details-card .detail-label { font-weight: 600; color: #6b7280; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; }
    .project-details-card .detail-value { font-weight: 600; color: #111827; font-size: 15px; }
    .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin: 32px 0; }
    .stat-card { background: white; border: 1px solid #e5e7eb; border-radius: 12px; padding: 24px; text-align: center; }
    .stat-card-value { font-size: 20px; font-weight: 800; color: ${VERIFYTRADE_ORANGE}; margin-bottom: 8px; line-height: 1.2; word-break: break-word; }
    .stat-card-label { font-size: 13px; color: #6b7280; font-weight: 500; text-transform: uppercase; letter-spacing: 0.5px; }
    .content-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 32px; }
    .card { background: white; border: 2px solid #e5e7eb; border-radius: 12px; padding: 28px; }
    .cost-breakdown { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 24px; margin-top: 24px; }
    .cost-row { display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
    .cost-row:last-child { border-bottom: none; padding-top: 16px; margin-top: 8px; border-top: 2px solid ${VERIFYTRADE_ORANGE}; font-weight: 700; }
    @media print { body { print-color-adjust: exact; -webkit-print-color-adjust: exact; } }
  </style>
</head>
<body>
  <div class="page cover-page">
    <div style="flex: 1; display: flex; flex-direction: column; justify-content: center; align-items: center;">
      <h1 style="text-align: center;">Senior Project Team Overview</h1>
      <div class="subtitle" style="text-align: center;">Executive Summary & Commercial Dashboard</div>
      <div class="project-details-card">
        <div class="detail-row"><span class="detail-label">Project</span><span class="detail-value">${projectName}</span></div>
        <div class="detail-row"><span class="detail-label">Subcontractor</span><span class="detail-value">${supplierName}</span></div>
      </div>
      <div class="stats-grid" style="margin-top: 40px;">
        <div class="stat-card"><div class="stat-card-value">${formatCurrency(totalAmount)}</div><div class="stat-card-label">Contract Value</div></div>
        <div class="stat-card"><div class="stat-card-value">${formatCurrency(retentionAmount)}</div><div class="stat-card-label">Retention (${retentionPercentage}%)</div></div>
        <div class="stat-card"><div class="stat-card-value">${formatCurrency(netAmount)}</div><div class="stat-card-label">Net Payable</div></div>
        <div class="stat-card"><div class="stat-card-value">${scopeSystems.length}</div><div class="stat-card-label">Service Types</div></div>
      </div>
      <div style="margin-top: 60px;">
        ${generateLogoSection(organisationLogoUrl)}
        <div style="font-size: 13px; color: #6b7280; margin-top: 12px; text-align: center;">Generated ${generatedDate}</div>
      </div>
    </div>
    <footer style="text-align: right; margin-top: auto;"><div style="color: ${VERIFYTRADE_ORANGE}; font-weight: 600;">Generated by VerifyTrade</div></footer>
  </div>

  <div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    <div class="content-grid">
      <div class="card">
        <h3>Scope Distribution</h3>
        <div style="display: flex; justify-content: center; padding: 10px;">
          <svg width="200" height="200" viewBox="0 0 200 200">${paths}</svg>
        </div>
        <div style="display: grid; gap: 6px; margin-top: 12px;">${legend}</div>
      </div>
      <div class="card">
        <h3>Financial Breakdown</h3>
        ${inclusionsHTML}
        ${exclusionsHTML}
        <div class="cost-breakdown">
          <div class="cost-row"><span style="color: #6b7280;">Total Contract Value</span><span style="color: #111827; font-weight: 700;">${formatCurrency(totalAmount)}</span></div>
          <div class="cost-row"><span style="color: #6b7280;">Less: Retention (${retentionPercentage}%)</span><span style="color: #f59e0b; font-weight: 700;">-${formatCurrency(retentionAmount)}</span></div>
          <div class="cost-row"><span style="color: #6b7280;">Net Amount Payable</span><span style="color: #16a34a; font-weight: 700;">${formatCurrency(netAmount)}</span></div>
        </div>
      </div>
    </div>
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div>Page 2</div></footer>
  </div>

  <div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    <h2 style="margin-bottom: 24px;">Detailed Scope Breakdown</h2>
    ${scopeDetailsHTML}
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div>Page 3</div></footer>
  </div>

  <div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    <h2>Executive Contract Summary</h2>
    <div style="display: grid; gap: 24px;">
      <div style="background: white; border: 2px solid #e5e7eb; border-radius: 12px; padding: 24px;">
        <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-bottom: 16px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">Project Information</h3>
        <div style="display: grid; grid-template-columns: 1fr 2fr; gap: 12px; font-size: 14px;">
          ${additionalData?.client ? `<div style="color: #6b7280; font-weight: 600;">Client:</div><div style="color: #111827;">${additionalData.client}</div>` : ''}
          ${additionalData?.mainContractor ? `<div style="color: #6b7280; font-weight: 600;">Main Contractor:</div><div style="color: #111827;">${additionalData.mainContractor}</div>` : ''}
          ${additionalData?.projectManager?.name ? `<div style="color: #6b7280; font-weight: 600;">Project Manager:</div><div style="color: #111827;">${additionalData.projectManager.name}</div>` : ''}
          ${additionalData?.projectManager?.email ? `<div style="color: #6b7280; font-weight: 600;">PM Email:</div><div style="color: #111827;">${additionalData.projectManager.email}</div>` : ''}
          ${additionalData?.projectManager?.phone ? `<div style="color: #6b7280; font-weight: 600;">PM Phone:</div><div style="color: #111827;">${additionalData.projectManager.phone}</div>` : ''}
        </div>
      </div>

      <div style="background: white; border: 2px solid #e5e7eb; border-radius: 12px; padding: 24px;">
        <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-bottom: 16px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">Subcontractor Contact Details</h3>
        <div style="display: grid; grid-template-columns: 1fr 2fr; gap: 12px; font-size: 14px;">
          <div style="color: #6b7280; font-weight: 600;">Company:</div><div style="color: #111827;">${supplierName}</div>
          ${additionalData?.supplier?.contactName ? `<div style="color: #6b7280; font-weight: 600;">Contact Person:</div><div style="color: #111827;">${additionalData.supplier.contactName}</div>` : ''}
          ${additionalData?.supplier?.contactEmail ? `<div style="color: #6b7280; font-weight: 600;">Email:</div><div style="color: #111827;">${additionalData.supplier.contactEmail}</div>` : ''}
          ${additionalData?.supplier?.contactPhone ? `<div style="color: #6b7280; font-weight: 600;">Phone:</div><div style="color: #111827;">${additionalData.supplier.contactPhone}</div>` : ''}
          ${additionalData?.supplier?.address ? `<div style="color: #6b7280; font-weight: 600;">Address:</div><div style="color: #111827;">${additionalData.supplier.address}</div>` : ''}
        </div>
      </div>

      <div style="background: white; border: 2px solid #e5e7eb; border-radius: 12px; padding: 24px;">
        <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-bottom: 16px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px;">Commercial Terms</h3>
        <div style="display: grid; grid-template-columns: 1fr 2fr; gap: 12px; font-size: 14px;">
          <div style="color: #6b7280; font-weight: 600;">Contract Value:</div><div style="color: #111827; font-weight: 700;">${formatCurrency(totalAmount)}</div>
          <div style="color: #6b7280; font-weight: 600;">Retention:</div><div style="color: #111827;">${retentionPercentage}% (${formatCurrency(retentionAmount)})</div>
          ${additionalData?.paymentTerms ? `<div style="color: #6b7280; font-weight: 600;">Payment Terms:</div><div style="color: #111827;">${additionalData.paymentTerms}</div>` : ''}
          ${additionalData?.liquidatedDamages ? `<div style="color: #6b7280; font-weight: 600;">Liquidated Damages:</div><div style="color: #111827;">${additionalData.liquidatedDamages}</div>` : ''}
        </div>
      </div>
    </div>
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div>Page 4</div></footer>
  </div>

  ${benchmarkData.length > 1 ? `<div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    <h2>Commercial Analysis & Benchmarking</h2>
    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
      <h3 style="color: #374151; margin-bottom: 16px;">Supplier Comparison</h3>
      <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
        <thead>
          <tr style="background: #e5e7eb;">
            <th style="padding: 12px; text-align: left; border: 1px solid #d1d5db;">Supplier</th>
            <th style="padding: 12px; text-align: right; border: 1px solid #d1d5db;">Total Price</th>
            <th style="padding: 12px; text-align: right; border: 1px solid #d1d5db;">Coverage</th>
            <th style="padding: 12px; text-align: right; border: 1px solid #d1d5db;">Weighted Score</th>
          </tr>
        </thead>
        <tbody>
          ${benchmarkData.map((s: any, idx: number) => `
            <tr style="background: ${idx === 0 ? '#d1fae5' : 'white'};">
              <td style="padding: 12px; border: 1px solid #d1d5db; ${idx === 0 ? 'font-weight: 700;' : ''}">${s.supplierName || 'Unknown'}</td>
              <td style="padding: 12px; text-align: right; border: 1px solid #d1d5db;">${formatCurrency(s.adjustedTotal || 0)}</td>
              <td style="padding: 12px; text-align: right; border: 1px solid #d1d5db;">${(s.coverage || 0).toFixed(1)}%</td>
              <td style="padding: 12px; text-align: right; border: 1px solid #d1d5db; ${idx === 0 ? 'font-weight: 700; color: #16a34a;' : ''}">${(s.weightedScore || 0).toFixed(2)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    <div style="background: white; border: 2px solid #e5e7eb; border-radius: 12px; padding: 24px;">
      <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-bottom: 16px;">Key Insights</h3>
      <ul style="list-style: none; padding: 0; margin: 0;">
        <li style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; display: flex; align-items: start;">
          <span style="color: #16a34a; font-weight: 700; margin-right: 12px;">✓</span>
          <span style="color: #374151;">Recommended supplier offers ${benchmarkData[0]?.coverage?.toFixed(1) || '0'}% scope coverage</span>
        </li>
        ${benchmarkData.length > 1 ? `<li style="padding: 10px 0; border-bottom: 1px solid #e5e7eb; display: flex; align-items: start;">
          <span style="color: #16a34a; font-weight: 700; margin-right: 12px;">✓</span>
          <span style="color: #374151;">Price variance: ${formatCurrency(Math.abs((benchmarkData[0]?.adjustedTotal || 0) - (benchmarkData[benchmarkData.length - 1]?.adjustedTotal || 0)))} between highest and lowest</span>
        </li>` : ''}
        <li style="padding: 10px 0; display: flex; align-items: start;">
          <span style="color: #16a34a; font-weight: 700; margin-right: 12px;">✓</span>
          <span style="color: #374151;">Evaluation based on price, coverage, and quality factors</span>
        </li>
      </ul>
    </div>
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div>Page 5</div></footer>
  </div>` : ''}

  <div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    <h2>Risk Assessment & Recommendations</h2>
    <div style="display: grid; gap: 20px;">
      <div style="background: #fef3c7; border-left: 4px solid #f59e0b; border-radius: 0 8px 8px 0; padding: 20px;">
        <h3 style="color: #92400e; margin-bottom: 12px; font-size: 16px; font-weight: 700;">⚠ Key Commercial Risks</h3>
        <ul style="list-style: none; padding: 0; margin: 0;">
          ${exclusions.length > 0 ? `<li style="padding: 8px 0; color: #78350f; line-height: 1.6;"><strong>Scope Exclusions:</strong> ${exclusions.length} items excluded from quote - may result in variations</li>` : ''}
          <li style="padding: 8px 0; color: #78350f; line-height: 1.6;"><strong>Retention:</strong> ${retentionPercentage}% retention (${formatCurrency(retentionAmount)}) held until practical completion</li>
          ${scopeSystems.length < 3 ? `<li style="padding: 8px 0; color: #78350f; line-height: 1.6;"><strong>Limited Coverage:</strong> Quote covers ${scopeSystems.length} service types - verify completeness against drawings</li>` : ''}
          ${!additionalData?.paymentTerms ? `<li style="padding: 8px 0; color: #78350f; line-height: 1.6;"><strong>Payment Terms:</strong> Confirm payment terms and milestone schedule with supplier</li>` : ''}
        </ul>
      </div>

      <div style="background: #dbeafe; border-left: 4px solid #3b82f6; border-radius: 0 8px 8px 0; padding: 20px;">
        <h3 style="color: #1e3a8a; margin-bottom: 12px; font-size: 16px; font-weight: 700;">✓ Recommended Actions</h3>
        <ol style="padding-left: 20px; margin: 0; color: #1e40af;">
          <li style="padding: 8px 0; line-height: 1.6;">Review detailed scope breakdown with design team to confirm completeness</li>
          <li style="padding: 8px 0; line-height: 1.6;">Verify subcontractor licenses, insurances, and track record for similar projects</li>
          <li style="padding: 8px 0; line-height: 1.6;">Establish clear communication protocol and site coordination requirements</li>
          <li style="padding: 8px 0; line-height: 1.6;">Schedule pre-start meeting to align on quality standards and documentation</li>
          ${exclusions.length > 0 ? `<li style="padding: 8px 0; line-height: 1.6;">Clarify responsibility for ${exclusions.length} excluded items before contract award</li>` : ''}
        </ol>
      </div>

      <div style="background: #d1fae5; border-left: 4px solid #10b981; border-radius: 0 8px 8px 0; padding: 20px;">
        <h3 style="color: #065f46; margin-bottom: 12px; font-size: 16px; font-weight: 700;">💡 Practical Site Considerations</h3>
        <ul style="list-style: none; padding: 0; margin: 0;">
          <li style="padding: 8px 0; color: #047857; line-height: 1.6;"><strong>Access & Coordination:</strong> Confirm site access requirements and coordinate with other trades</li>
          <li style="padding: 8px 0; color: #047857; line-height: 1.6;"><strong>Quality Control:</strong> Establish inspection checkpoints and documentation requirements (photos, compliance certs)</li>
          <li style="padding: 8px 0; color: #047857; line-height: 1.6;"><strong>Material Lead Times:</strong> Confirm supply chain and lead times for specialized materials</li>
          <li style="padding: 8px 0; color: #047857; line-height: 1.6;"><strong>Safety & Compliance:</strong> Ensure SWMS provided and site induction completed before start</li>
        </ul>
      </div>
    </div>
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div>Page ${benchmarkData.length > 1 ? '6' : '5'}</div></footer>
  </div>

  <div class="page page-break">
    <header>${generateLogoSection(organisationLogoUrl)}<div class="generated-by">Generated by <strong>VerifyTrade</strong></div></header>
    <h2>Financial Breakdown & Cash Flow Forecast</h2>
    <div style="display: grid; gap: 24px;">
      <div style="background: white; border: 2px solid #e5e7eb; border-radius: 12px; padding: 24px;">
        <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-bottom: 16px;">Contract Financial Summary</h3>
        <table style="width: 100%; font-size: 14px; border-collapse: collapse;">
          <tr style="border-bottom: 1px solid #e5e7eb;">
            <td style="padding: 12px 0; color: #6b7280;">Contract Sum</td>
            <td style="padding: 12px 0; text-align: right; font-weight: 700; color: #111827;">${formatCurrency(totalAmount)}</td>
          </tr>
          <tr style="border-bottom: 1px solid #e5e7eb;">
            <td style="padding: 12px 0; color: #6b7280;">Less: Retention (${retentionPercentage}%)</td>
            <td style="padding: 12px 0; text-align: right; color: #f59e0b; font-weight: 600;">-${formatCurrency(retentionAmount)}</td>
          </tr>
          <tr style="border-bottom: 2px solid ${VERIFYTRADE_ORANGE};">
            <td style="padding: 12px 0; color: #6b7280; font-weight: 700;">Net Payable</td>
            <td style="padding: 12px 0; text-align: right; font-weight: 700; color: #16a34a; font-size: 16px;">${formatCurrency(netAmount)}</td>
          </tr>
          <tr style="border-bottom: 1px solid #e5e7eb;">
            <td style="padding: 12px 0; color: #6b7280;">Retention Release (PC)</td>
            <td style="padding: 12px 0; text-align: right; color: #3b82f6; font-weight: 600;">${formatCurrency(retentionAmount * 0.5)}</td>
          </tr>
          <tr>
            <td style="padding: 12px 0; color: #6b7280;">Retention Release (Final)</td>
            <td style="padding: 12px 0; text-align: right; color: #3b82f6; font-weight: 600;">${formatCurrency(retentionAmount * 0.5)}</td>
          </tr>
        </table>
      </div>

      <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 24px;">
        <h3 style="color: #374151; margin-bottom: 16px;">Indicative Cash Flow Forecast</h3>
        <p style="color: #6b7280; font-size: 13px; margin-bottom: 16px; line-height: 1.6;">Based on typical monthly progress claims. Actual payments subject to site progress and payment terms.</p>
        <table style="width: 100%; font-size: 13px; border-collapse: collapse;">
          <thead>
            <tr style="background: #e5e7eb; border-bottom: 2px solid #d1d5db;">
              <th style="padding: 10px; text-align: left;">Period</th>
              <th style="padding: 10px; text-align: right;">Progress %</th>
              <th style="padding: 10px; text-align: right;">Claim Amount</th>
              <th style="padding: 10px; text-align: right;">Cumulative</th>
            </tr>
          </thead>
          <tbody>
            ${[15, 30, 25, 20, 10].map((percent, idx) => {
              const periodAmount = (totalAmount * percent) / 100;
              const cumulativePercent = [15, 45, 70, 90, 100][idx];
              const cumulativeAmount = (totalAmount * cumulativePercent) / 100;
              return `<tr style="border-bottom: 1px solid #e5e7eb;">
                <td style="padding: 10px;">Month ${idx + 1}</td>
                <td style="padding: 10px; text-align: right;">${percent}%</td>
                <td style="padding: 10px; text-align: right;">${formatCurrency(periodAmount)}</td>
                <td style="padding: 10px; text-align: right; font-weight: 600;">${formatCurrency(cumulativeAmount)}</td>
              </tr>`;
            }).join('')}
            <tr style="background: #f3f4f6; font-weight: 700;">
              <td style="padding: 12px;">Total</td>
              <td style="padding: 12px; text-align: right;">100%</td>
              <td style="padding: 12px; text-align: right;">${formatCurrency(totalAmount)}</td>
              <td style="padding: 12px; text-align: right; color: ${VERIFYTRADE_ORANGE};">${formatCurrency(totalAmount)}</td>
            </tr>
          </tbody>
        </table>
        <p style="color: #6b7280; font-size: 12px; margin-top: 12px; font-style: italic;">* Retention ${formatCurrency(retentionAmount)} to be released: 50% at Practical Completion, 50% at Final Completion</p>
      </div>
    </div>
    <footer><div>© ${year} VerifyTrade. All rights reserved.</div><div>Page ${benchmarkData.length > 1 ? '7' : '6'}</div></footer>
  </div>
</body>
</html>`;
}

export function generatePreletAppendixHTML(
  projectName: string,
  supplierName: string,
  totalAmount: number,
  appendixData: any,
  organisationLogoUrl?: string
): string {
  const generatedDate = new Date().toLocaleDateString('en-NZ', { day: 'numeric', month: 'long', year: 'numeric' });
  const year = new Date().getFullYear();

  const formatCurrency = (value: number) => {
    return `$${value.toLocaleString('en-NZ', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  const pricingBasisLabels: Record<string, string> = {
    'lump_sum': 'Lump Sum',
    'schedule_of_rates': 'Schedule of Rates',
    'cost_plus': 'Cost Plus',
    'unit_rates': 'Unit Rates'
  };

  const pricingBasisLabel = pricingBasisLabels[appendixData.pricing_basis] || 'Lump Sum';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pre-let Minute Appendix - ${projectName}</title>
  <style>
    @media print {
      .page { page-break-after: always; }
      @page { margin: 15mm; }
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #ffffff; color: #111827; line-height: 1.6; }
    .page { width: 210mm; min-height: 297mm; padding: 20mm; background: white; position: relative; }
    .logo-section { display: flex; align-items: center; gap: 16px; margin-bottom: 24px; }
    .logo-icon { width: 48px; height: 48px; background: linear-gradient(135deg, ${VERIFYTRADE_ORANGE} 0%, ${VERIFYTRADE_ORANGE_DARK} 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center; }
    .logo-text { font-size: 24px; font-weight: 800; background: linear-gradient(135deg, ${VERIFYTRADE_ORANGE} 0%, ${VERIFYTRADE_ORANGE_DARK} 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }
    header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px; border-bottom: 3px solid ${VERIFYTRADE_ORANGE}; padding-bottom: 16px; }
    .generated-by { font-size: 13px; color: #6b7280; text-align: right; }
    h1 { font-size: 36px; font-weight: 900; color: #111827; margin-bottom: 16px; line-height: 1.2; }
    h2 { font-size: 28px; font-weight: 800; color: ${VERIFYTRADE_ORANGE}; margin-bottom: 20px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
    h3 { font-size: 18px; font-weight: 700; color: #374151; margin: 20px 0 12px 0; }
    .section-card { background: #f9fafb; border: 2px solid #e5e7eb; border-left: 4px solid ${VERIFYTRADE_ORANGE}; border-radius: 8px; padding: 24px; margin-bottom: 24px; }
    .info-grid { display: grid; grid-template-columns: 200px 1fr; gap: 12px; }
    .info-label { font-weight: 600; color: #6b7280; }
    .info-value { color: #111827; font-weight: 500; }
    .list-section { margin: 16px 0; }
    .list-section ul { list-style: none; padding: 0; }
    .list-section li { padding: 10px 12px; margin: 6px 0; background: white; border: 1px solid #e5e7eb; border-radius: 6px; position: relative; padding-left: 32px; }
    .list-section li:before { content: '▸'; position: absolute; left: 12px; color: ${VERIFYTRADE_ORANGE}; font-weight: bold; }
    .disclaimer-box { background: #dbeafe; border: 2px solid #3b82f6; border-radius: 8px; padding: 20px; margin: 32px 0; text-align: center; }
    .disclaimer-box p { color: #1e40af; font-size: 14px; font-weight: 600; line-height: 1.8; }
    .disclaimer-box .icon { display: inline-block; width: 20px; height: 20px; vertical-align: middle; margin-right: 8px; }
    footer { position: absolute; bottom: 15mm; left: 20mm; right: 20mm; border-top: 2px solid #e5e7eb; padding-top: 12px; font-size: 12px; color: #6b7280; display: flex; justify-content: space-between; }
  </style>
</head>
<body>
  <div class="page">
    <header>
      ${generateLogoSection(organisationLogoUrl)}
      <div class="generated-by">Generated by <strong>VerifyTrade</strong><br/>${generatedDate}</div>
    </header>

    <h1>Pre-let Minute Appendix</h1>
    <p style="font-size: 16px; color: #6b7280; margin-bottom: 32px;">
      Commercial and scope clarifications for subcontract award
    </p>

    <div class="section-card">
      <div class="info-grid">
        <div class="info-label">Project:</div>
        <div class="info-value">${projectName}</div>
        <div class="info-label">Subcontractor:</div>
        <div class="info-value">${supplierName}</div>
        <div class="info-label">Contract Value:</div>
        <div class="info-value" style="font-weight: 700; color: ${VERIFYTRADE_ORANGE};">${formatCurrency(totalAmount)}</div>
        <div class="info-label">Pricing Basis:</div>
        <div class="info-value">${pricingBasisLabel}</div>
        <div class="info-label">Date Finalised:</div>
        <div class="info-value">${new Date(appendixData.finalised_at || Date.now()).toLocaleDateString('en-NZ', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
      </div>
    </div>

    <div class="section-card">
      <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-top: 0;">Priced Scope Summary (Plain English)</h3>
      <p style="color: #374151; line-height: 1.8; white-space: pre-wrap;">${appendixData.scope_summary || 'No scope summary provided.'}</p>
    </div>

    ${appendixData.inclusions?.length > 0 ? `
    <div class="section-card">
      <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-top: 0;">Explicit Inclusions</h3>
      <p style="font-size: 13px; color: #6b7280; margin-bottom: 12px;">What is explicitly included in the subcontractor's scope</p>
      <div class="list-section">
        <ul>
          ${appendixData.inclusions.map((inc: string) => `<li>${inc}</li>`).join('')}
        </ul>
      </div>
    </div>` : ''}

    ${appendixData.exclusions?.length > 0 ? `
    <div class="section-card">
      <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-top: 0;">Explicit Exclusions</h3>
      <p style="font-size: 13px; color: #6b7280; margin-bottom: 12px;">What is explicitly excluded from the subcontractor's scope</p>
      <div class="list-section">
        <ul>
          ${appendixData.exclusions.map((exc: string) => `<li>${exc}</li>`).join('')}
        </ul>
      </div>
    </div>` : ''}

    <footer>
      <div>© ${year} VerifyTrade. All rights reserved.</div>
      <div>Page 1</div>
    </footer>
  </div>

  ${(appendixData.commercial_assumptions?.length > 0 || appendixData.clarifications?.length > 0 || appendixData.known_risks?.length > 0) ? `
  <div class="page page-break">
    <header>
      ${generateLogoSection(organisationLogoUrl)}
      <div class="generated-by">Generated by <strong>VerifyTrade</strong></div>
    </header>

    ${appendixData.commercial_assumptions?.length > 0 ? `
    <div class="section-card">
      <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-top: 0;">Commercial Assumptions</h3>
      <p style="font-size: 13px; color: #6b7280; margin-bottom: 12px;">Assumptions impacting cost, access, staging, or hours</p>
      <div class="list-section">
        <ul>
          ${appendixData.commercial_assumptions.map((asmp: string) => `<li>${asmp}</li>`).join('')}
        </ul>
      </div>
    </div>` : ''}

    ${appendixData.clarifications?.length > 0 ? `
    <div class="section-card">
      <h3 style="color: ${VERIFYTRADE_ORANGE}; margin-top: 0;">Subcontractor Clarifications</h3>
      <p style="font-size: 13px; color: #6b7280; margin-bottom: 12px;">Clarifications intended to remain part of the contract</p>
      <div class="list-section">
        <ul>
          ${appendixData.clarifications.map((clar: string) => `<li>${clar}</li>`).join('')}
        </ul>
      </div>
    </div>` : ''}

    ${appendixData.known_risks?.length > 0 ? `
    <div class="section-card" style="background: #fef3c7; border-left-color: #f59e0b;">
      <h3 style="color: #92400e; margin-top: 0;">Known Risks & Hold Points</h3>
      <p style="font-size: 13px; color: #78350f; margin-bottom: 12px;">Known risks, exclusions, or hold points affecting scope or price</p>
      <div class="list-section">
        <ul>
          ${appendixData.known_risks.map((risk: string) => `<li>${risk}</li>`).join('')}
        </ul>
      </div>
    </div>` : ''}

    <div class="disclaimer-box">
      <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#3b82f6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
      <p>
        This appendix will be attached to signed pre-letting minutes and read in conjunction<br/>
        with the main pre-letting minutes and subcontract agreement.
      </p>
    </div>

    <footer>
      <div>© ${year} VerifyTrade. All rights reserved.</div>
      <div>Page 2</div>
    </footer>
  </div>` : `
  <div class="page page-break">
    <header>
      ${generateLogoSection(organisationLogoUrl)}
      <div class="generated-by">Generated by <strong>VerifyTrade</strong></div>
    </header>

    <div class="disclaimer-box">
      <svg class="icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#3b82f6" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>
      <p>
        This appendix will be attached to signed pre-letting minutes and read in conjunction<br/>
        with the main pre-letting minutes and subcontract agreement.
      </p>
    </div>

    <footer>
      <div>© ${year} VerifyTrade. All rights reserved.</div>
      <div>Page 2</div>
    </footer>
  </div>`}
</body>
</html>`;
}
