export function generateJuniorPackHTML(projectName: string, clientName: string, supplierName: string, scopeSystems: any[]): string {
  const systemsHTML = scopeSystems.map(sys => {
    const detailsHTML = sys.details && sys.details.length > 0
      ? `<ul class="detail-list">${sys.details.slice(0, 3).map((d: string) => `<li>${d}</li>`).join('')}</ul>`
      : '';

    return `<div class="system-card">
      <h4>${sys.service_type}</h4>
      <p class="item-count">${sys.item_count} items</p>
      ${detailsHTML}
    </div>`;
  }).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Junior Site Team Pack - ${projectName}</title>
<style>
@page{size:A4 landscape;margin:15mm}
body{font-family:'Segoe UI',sans-serif;font-size:11pt;line-height:1.5;color:#1e293b}
.header{background:linear-gradient(135deg,#1e40af,#3b82f6);color:white;padding:20px 30px;margin-bottom:20px;border-radius:8px}
.header h1{font-size:24pt;margin-bottom:8px}
.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-bottom:25px}
.meta-item{background:#f1f5f9;padding:12px 15px;border-radius:6px;border-left:4px solid #3b82f6}
.meta-label{font-size:9pt;color:#64748b;text-transform:uppercase;font-weight:600;margin-bottom:4px}
.meta-value{font-size:12pt;color:#0f172a;font-weight:600}
h2{font-size:16pt;color:#1e40af;margin:25px 0 12px;padding-bottom:8px;border-bottom:2px solid #e2e8f0}
.systems-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:15px}
.system-card{background:#f8fafc;border:1px solid #cbd5e1;border-radius:6px;padding:12px}
.system-card h4{color:#1e40af;font-size:12pt;margin-bottom:6px}
.item-count{font-size:9pt;color:#64748b;margin-bottom:8px}
.detail-list{list-style:none;font-size:10pt;color:#475569;padding:0}
.detail-list li{padding:3px 0 3px 15px;position:relative}
.detail-list li:before{content:"•";position:absolute;left:0;color:#3b82f6}
.warning-box{background:#fef3c7;border-left:5px solid #f59e0b;padding:15px;margin:15px 0;border-radius:4px}
.checklist-section{background:#f1f5f9;padding:15px;border-radius:6px;margin-bottom:15px}
.checklist{list-style:none;padding:0}
.checklist li{padding:8px 0;font-size:10pt;border-bottom:1px solid #e2e8f0}
.footer{margin-top:30px;padding-top:15px;border-top:2px solid #e2e8f0;font-size:9pt;color:#64748b;text-align:center}
</style></head><body>
<div class="header"><h1>Junior Site Team Handover Pack</h1><p>Practical Guide for On-Site Installation & Quality Control</p></div>
<div class="meta">
<div class="meta-item"><div class="meta-label">Project</div><div class="meta-value">${projectName}</div></div>
<div class="meta-item"><div class="meta-label">Client</div><div class="meta-value">${clientName}</div></div>
<div class="meta-item"><div class="meta-label">Subcontractor</div><div class="meta-value">${supplierName}</div></div>
</div>
<h2>Scope of Works Overview</h2>
<div class="systems-grid">${systemsHTML}</div>
<div class="warning-box">
<h3 style="color:#92400e;margin-bottom:8px">Safety & Installation Notes</h3>
<ul style="list-style:none;padding:0">
<li style="padding:6px 0 6px 25px;position:relative"><span style="position:absolute;left:0">⚠</span>All personnel must complete site induction</li>
<li style="padding:6px 0 6px 25px;position:relative"><span style="position:absolute;left:0">⚠</span>Use appropriate PPE at all times</li>
<li style="padding:6px 0 6px 25px;position:relative"><span style="position:absolute;left:0">⚠</span>Follow manufacturer instructions for all materials</li>
</ul>
</div>
<h2>Site Handover Checklists</h2>
<div class="checklist-section"><h3 style="margin-bottom:10px">Pre-Start Checklist</h3>
<ul class="checklist">
<li><input type="checkbox" disabled> Site induction completed</li>
<li><input type="checkbox" disabled> SWMS reviewed and signed</li>
<li><input type="checkbox" disabled> Materials and equipment on site</li>
<li><input type="checkbox" disabled> Access to work areas confirmed</li>
</ul></div>
<div class="checklist-section"><h3 style="margin-bottom:10px">Installation Checklist</h3>
<ul class="checklist">
<li><input type="checkbox" disabled> Verify penetration dimensions</li>
<li><input type="checkbox" disabled> Check FRR requirements</li>
<li><input type="checkbox" disabled> Apply per manufacturer specifications</li>
<li><input type="checkbox" disabled> Label all penetrations</li>
</ul></div>
<div class="checklist-section"><h3 style="margin-bottom:10px">Quality Control</h3>
<ul class="checklist">
<li><input type="checkbox" disabled> Photograph all completed work</li>
<li><input type="checkbox" disabled> Complete QA documentation</li>
<li><input type="checkbox" disabled> Prepare PS3 documentation</li>
</ul></div>
<div class="footer"><p>Generated by VerifyTrade - Contract Manager | ${new Date().toLocaleDateString('en-NZ')}</p>
<p>Non-sensitive site team reference document</p></div>
</body></html>`;
}

export function generateSeniorReportHTML(projectName: string, clientName: string, supplierName: string, totalAmount: number, scopeSystems: any[]): string {
  const retentionAmount = totalAmount * 0.03;
  const netAmount = totalAmount - retentionAmount;

  const pieColors = ['#3b82f6','#10b981','#f59e0b','#ef4444','#8b5cf6','#ec4899','#06b6d4','#84cc16'];
  let currentAngle = -90;
  const paths = scopeSystems.map((sys, idx) => {
    const angle = (sys.percentage / 100) * 360;
    const startAngle = currentAngle;
    const endAngle = currentAngle + angle;
    const startRad = (startAngle * Math.PI) / 180;
    const endRad = (endAngle * Math.PI) / 180;
    const x1 = 100 + 90 * Math.cos(startRad);
    const y1 = 100 + 90 * Math.sin(startRad);
    const x2 = 100 + 90 * Math.cos(endRad);
    const y2 = 100 + 90 * Math.sin(endRad);
    const largeArc = angle > 180 ? 1 : 0;
    currentAngle = endAngle;
    return `<path d="M 100 100 L ${x1} ${y1} A 90 90 0 ${largeArc} 1 ${x2} ${y2} Z" fill="${pieColors[idx % pieColors.length]}" stroke="white" stroke-width="2"/>`;
  }).join('');

  const legendHTML = scopeSystems.map((sys, idx) =>
    `<div style="display:flex;align-items:center;gap:8px;font-size:9pt">
    <div style="width:12px;height:12px;background:${pieColors[idx % pieColors.length]};border-radius:2px"></div>
    <div style="flex:1;color:#475569">${sys.service_type}</div>
    <div style="font-weight:600">${sys.percentage.toFixed(1)}%</div>
    </div>`
  ).join('');

  return `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Senior Project Pack - ${projectName}</title>
<style>
@page{size:A4 landscape;margin:15mm}
body{font-family:'Segoe UI',sans-serif;font-size:10pt;line-height:1.4;color:#1e293b}
.header{background:linear-gradient(135deg,#7c3aed,#a855f7);color:white;padding:20px 30px;margin-bottom:20px;border-radius:8px}
.header h1{font-size:22pt;margin-bottom:6px}
.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:20px}
.summary-card{background:linear-gradient(135deg,#f8fafc,#e2e8f0);border:1px solid #cbd5e1;border-radius:6px;padding:12px}
.summary-label{font-size:8pt;color:#64748b;text-transform:uppercase;font-weight:600;margin-bottom:4px}
.summary-value{font-size:18pt;color:#7c3aed;font-weight:700}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-bottom:20px}
.card{background:white;border:1px solid #e2e8f0;border-radius:6px;padding:15px}
h2{font-size:13pt;color:#7c3aed;margin-bottom:12px;padding-bottom:8px;border-bottom:2px solid #e2e8f0}
table{width:100%;border-collapse:collapse;margin:10px 0;font-size:9pt}
th{background:#f1f5f9;color:#475569;font-size:9pt;text-align:left;padding:8px;border-bottom:2px solid #cbd5e1;font-weight:600}
td{padding:8px;border-bottom:1px solid #e2e8f0}
.cost-row{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #e2e8f0}
.footer{margin-top:20px;padding-top:12px;border-top:2px solid #e2e8f0;font-size:8pt;color:#64748b;text-align:center}
</style></head><body>
<div class="header"><h1>Senior Project Team Pack</h1><p style="font-size:11pt">Executive Summary & Commercial Dashboard</p></div>
<div class="summary">
<div class="summary-card"><div class="summary-label">Contract Value</div><div class="summary-value">$${(totalAmount/1000).toFixed(0)}k</div></div>
<div class="summary-card"><div class="summary-label">Retention</div><div class="summary-value">$${(retentionAmount/1000).toFixed(0)}k</div></div>
<div class="summary-card"><div class="summary-label">Net Payable</div><div class="summary-value">$${(netAmount/1000).toFixed(0)}k</div></div>
<div class="summary-card"><div class="summary-label">Service Types</div><div class="summary-value">${scopeSystems.length}</div></div>
</div>
<div class="grid">
<div class="card"><h2>Scope Distribution</h2>
<svg width="200" height="200" viewBox="0 0 200 200" style="display:block;margin:0 auto">${paths}</svg>
<div style="margin-top:12px;display:grid;gap:6px">${legendHTML}</div>
</div>
<div class="card"><h2>Financial Breakdown</h2>
<div style="background:#f8fafc;padding:12px;border-radius:6px">
<div class="cost-row"><span>Total Contract Value</span><span style="font-weight:600">$${totalAmount.toLocaleString('en-NZ',{minimumFractionDigits:2})}</span></div>
<div class="cost-row"><span>Less: Retention (3%)</span><span style="color:#f59e0b;font-weight:600">-$${retentionAmount.toLocaleString('en-NZ',{minimumFractionDigits:2})}</span></div>
<div class="cost-row" style="border-top:2px solid #7c3aed;padding-top:10px;margin-top:6px;font-weight:700"><span>Net Payable</span><span style="color:#16a34a">$${netAmount.toLocaleString('en-NZ',{minimumFractionDigits:2})}</span></div>
</div>
<h2 style="margin-top:15px">Key Terms</h2>
<table><tbody>
<tr><td style="width:40%;font-weight:600">Payment Terms</td><td>20th following month, 22 working days</td></tr>
<tr><td style="font-weight:600">Retention</td><td>3% until practical completion</td></tr>
<tr><td style="font-weight:600">Liquidated Damages</td><td>None specified</td></tr>
</tbody></table>
</div>
</div>
<div class="card" style="margin-bottom:20px"><h2>Risk Register</h2>
<table><thead><tr><th>Category</th><th>Description</th><th>Mitigation</th></tr></thead>
<tbody>
<tr style="background:#fee2e2"><td style="font-weight:600;color:#dc2626">Quality & Compliance</td><td>Non-compliant installations</td><td>Site supervision, QA checks, regular inspections</td></tr>
<tr style="background:#fef3c7"><td style="font-weight:600;color:#f59e0b">Programme Risk</td><td>Delays in preceding trades</td><td>Weekly coordination, early warning system</td></tr>
<tr style="background:#fef3c7"><td style="font-weight:600;color:#f59e0b">Scope Clarity</td><td>Additional penetrations</td><td>Allowance included, variation process</td></tr>
</tbody></table>
</div>
<div class="footer"><p>Generated by VerifyTrade - Contract Manager | ${new Date().toLocaleDateString('en-NZ')}</p>
<p>Commercial and sensitive information - restricted distribution</p></div>
</body></html>`;
}
