/**
 * Unified PDF Header & Footer System
 * Implements consistent, clean headers/footers across all VerifyTrade PDFs
 *
 * PRESENTATION ONLY - NO DATA CHANGES
 */

export interface HeaderFooterConfig {
  documentTitle: string;
  projectName: string;
  supplierName: string;
  generatedDate: string;
  organisationLogoUrl?: string;
}

const VERIFYTRADE_ORANGE = '#f97316';

/**
 * Generate standardized PDF header
 * Layout: Logo (left) | Document Title (center) | Project Name (right)
 */
export function generatePDFHeader(config: HeaderFooterConfig): string {
  const logoSection = config.organisationLogoUrl
    ? `
      <div style="display: flex; align-items: center; gap: 12px;">
        <img
          src="${config.organisationLogoUrl}"
          alt="Organisation Logo"
          style="max-width: 80px; max-height: 36px; object-fit: contain;"
        />
        <div style="width: 1px; height: 32px; background: #e5e7eb; margin: 0 8px;"></div>
        <img
          src="https://verifytrade.com/verifytrade_logo.png"
          alt="VerifyTrade"
          style="max-width: 120px; max-height: 36px; object-fit: contain;"
          onerror="this.style.display='none'; this.nextElementSibling.style.display='block';"
        />
        <div style="display: none; font-size: 16px; font-weight: 700; color: #111827; letter-spacing: -0.3px;">
          VerifyTrade
        </div>
      </div>
    `
    : `
      <div style="display: flex; align-items: center;">
        <img
          src="https://verifytrade.com/verifytrade_logo.png"
          alt="VerifyTrade"
          style="max-width: 120px; max-height: 36px; object-fit: contain;"
          onerror="this.style.display='none'; this.nextElementSibling.style.display='block';"
        />
        <div style="display: none; font-size: 16px; font-weight: 700; color: #111827; letter-spacing: -0.3px;">
          VerifyTrade
        </div>
      </div>
    `;

  return `
    <div class="pdf-header" style="
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 12px 0;
      border-bottom: 2px solid ${VERIFYTRADE_ORANGE};
      margin-bottom: 20px;
    ">
      <div style="flex: 1;">
        ${logoSection}
      </div>
      <div style="flex: 1; text-align: center;">
        <div style="font-size: 11px; font-weight: 600; color: #374151; letter-spacing: 0.3px;">
          ${config.documentTitle}
        </div>
      </div>
      <div style="flex: 1; text-align: right;">
        <div style="font-size: 10px; font-weight: 600; color: #6b7280;">
          ${config.projectName}
        </div>
      </div>
    </div>
  `;
}

/**
 * Generate standardized PDF footer
 * Layout: Supplier (left) | Generated info (center) | Page X of Y (right)
 */
export function generatePDFFooter(config: HeaderFooterConfig): string {
  return `
    <div class="pdf-footer" style="
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      padding: 10px 12mm;
      border-top: 1px solid #e5e7eb;
      background: white;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 9px;
      color: #6b7280;
    ">
      <div style="flex: 1; text-align: left;">
        <span style="font-weight: 600;">${config.supplierName}</span>
      </div>
      <div style="flex: 1; text-align: center;">
        <span style="color: ${VERIFYTRADE_ORANGE}; font-weight: 600;">Generated by VerifyTrade</span>
        <span style="margin-left: 8px;">|</span>
        <span style="margin-left: 8px;">${config.generatedDate}</span>
      </div>
      <div style="flex: 1; text-align: right;">
        <span class="page-number"></span>
      </div>
    </div>
  `;
}

/**
 * Inject page numbering script
 * This runs in the browser/Gotenberg context to add "Page X of Y"
 */
export function generatePageNumberingScript(): string {
  return `
    <script>
      (function() {
        // This script runs after PDF rendering to inject page numbers
        // Gotenberg supports this via Paged.js or similar
        if (typeof window !== 'undefined' && window.PagedPolyfill) {
          window.PagedPolyfill.registerHandlers(class extends window.PagedPolyfill.Handler {
            afterRendered(pages) {
              const totalPages = pages.length;
              pages.forEach((page, index) => {
                const pageNum = index + 1;
                const footer = page.element.querySelector('.page-number');
                if (footer) {
                  footer.textContent = \`Page \${pageNum} of \${totalPages}\`;
                }
              });
            }
          });
        } else {
          // Fallback for non-Paged.js environments
          const footers = document.querySelectorAll('.page-number');
          const totalPages = document.querySelectorAll('.page').length || footers.length;
          footers.forEach((footer, index) => {
            footer.textContent = \`Page \${index + 1} of \${totalPages}\`;
          });
        }
      })();
    </script>
  `;
}

/**
 * Wrap content with header and footer
 */
export function wrapContentWithHeaderFooter(
  content: string,
  config: HeaderFooterConfig
): string {
  const header = generatePDFHeader(config);
  const footer = generatePDFFooter(config);
  const script = generatePageNumberingScript();

  return `
    ${header}
    <div class="pdf-content" style="min-height: calc(100vh - 120px); padding-bottom: 60px;">
      ${content}
    </div>
    ${footer}
    ${script}
  `;
}

/**
 * Remove old-style inline "Generated by VerifyTrade" text from content
 */
export function cleanupRedundantGeneratedText(html: string): string {
  // Remove standalone "Generated by VerifyTrade" lines
  return html
    .replace(/<div[^>]*>Generated by <strong>VerifyTrade<\/strong><\/div>/gi, '')
    .replace(/<div[^>]*class="generated-by"[^>]*>.*?<\/div>/gi, '')
    .replace(/Generated by VerifyTrade/g, '');
}

/**
 * Apply header/footer system to full HTML document
 */
export function applyHeaderFooterSystem(
  htmlDoc: string,
  config: HeaderFooterConfig
): string {
  // First, clean up any old-style generated text
  let cleanedHTML = cleanupRedundantGeneratedText(htmlDoc);

  // Parse and wrap each page content
  // This is a simplified approach - production would use proper HTML parsing
  if (cleanedHTML.includes('<div class="page">')) {
    const pages = cleanedHTML.split('<div class="page">');
    const wrappedPages = pages.map((page, index) => {
      if (index === 0) return page; // Skip before first page

      // Extract page content
      const pageContent = page.replace('</div>', '');

      return `<div class="page">${wrapContentWithHeaderFooter(pageContent, config)}</div>`;
    });

    cleanedHTML = wrappedPages.join('');
  }

  return cleanedHTML;
}
