import { createClient } from 'npm:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Client-Info, Apikey',
};

interface GotenbergPdfRequest {
  htmlContent: string;
  filename: string;
  projectName?: string;
  contractNumber?: string;
  reportType?: string;
  supplierName?: string;
  organisationLogoUrl?: string;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers: corsHeaders });
  }

  const requestStartTime = Date.now();
  let userId: string | undefined;
  let reportType: string | undefined;

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get Gotenberg URL from environment or system_config
    let gotenbergUrl = Deno.env.get('GOTENBERG_URL');

    if (!gotenbergUrl) {
      console.log('📄 [Gotenberg] GOTENBERG_URL not in env, checking system_config...');
      const { data: configData } = await supabase
        .from('system_config')
        .select('value')
        .eq('key', 'GOTENBERG_URL')
        .single();

      if (configData?.value) {
        gotenbergUrl = configData.value;
        console.log('📄 [Gotenberg] Using URL from system_config');
      } else {
        throw new Error('GOTENBERG_URL not found in environment or system_config');
      }
    }

    // Authenticate request
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('No authorization header');
    }

    // Verify user session
    const token = authHeader.replace('Bearer ', '');
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);

    if (authError || !user) {
      throw new Error('Authentication failed');
    }

    userId = user.id;

    const requestBody: GotenbergPdfRequest = await req.json();
    const {
      htmlContent,
      filename,
      projectName,
      contractNumber,
      reportType: reqReportType,
      supplierName,
      organisationLogoUrl,
    } = requestBody;

    reportType = reqReportType;

    if (!htmlContent) {
      throw new Error('htmlContent is required');
    }

    if (!filename) {
      throw new Error('filename is required');
    }

    // Generate filename with timestamp
    const today = new Date().toISOString().split('T')[0];
    const pdfFilename = `${filename}_${today}.pdf`;

    // Note: htmlContent arrives PRE-WRAPPED by pdfGenerator.ts with:
    // - wrapContentWithLayout() which includes full CSS
    // - cleanLegacyPaginationArtifacts() to remove manual pagination
    // - preparePdfContent() for QA
    //
    // So we DON'T need to add CSS here - just pass it through
    const completeHtml = htmlContent;

    console.log(`📄 [Gotenberg] Generating PDF: ${pdfFilename}`);
    console.log(`📄 [Gotenberg] HTML size: ${completeHtml.length} bytes`);

    // Create form data for Gotenberg
    const formData = new FormData();

    // Add HTML file
    const htmlBlob = new Blob([completeHtml], { type: 'text/html' });
    formData.append('files', htmlBlob, 'index.html');

    //=============================================================================
    // GOTENBERG PARAMETERS - MUST MATCH pdfLayoutSystem.ts CONSTANTS
    //=============================================================================
    // Margins:
    //   Top: 25mm = 0.98" (reserves 20mm header + 5mm buffer)
    //   Bottom: 20mm = 0.79" (reserves 16mm footer + 4mm buffer)
    //   Left/Right: 15mm = 0.59" (generous for executive feel)
    //=============================================================================

    formData.append('paperWidth', '8.27');   // A4 width in inches
    formData.append('paperHeight', '11.69'); // A4 height in inches
    formData.append('marginTop', '0.98');     // 25mm (MUST match PDF_CONSTANTS.MARGINS.TOP_MM)
    formData.append('marginBottom', '0.79');  // 20mm (MUST match PDF_CONSTANTS.MARGINS.BOTTOM_MM)
    formData.append('marginLeft', '0.59');    // 15mm (MUST match PDF_CONSTANTS.MARGINS.LEFT_MM)
    formData.append('marginRight', '0.59');   // 15mm (MUST match PDF_CONSTANTS.MARGINS.RIGHT_MM)
    formData.append('printBackground', 'true');
    formData.append('preferCssPageSize', 'true');
    formData.append('emulatedMediaType', 'print');
    formData.append('scale', '1.0');
    formData.append('waitDelay', '100ms'); // Small delay for font loading
    formData.append('waitForExpression', ''); // Don't wait for JS

    //=============================================================================
    // EXECUTIVE-GRADE HEADER & FOOTER
    //=============================================================================
    // These are generated by pdfLayoutSystem.ts functions:
    // - generateGotenbergHeader()
    // - generateGotenbergFooter()
    //
    // They use Chromium placeholders that Gotenberg auto-populates:
    // - <span class="pageNumber"></span> → 1, 2, 3, ...
    // - <span class="totalPages"></span> → total page count
    //=============================================================================

    const leftHeader = contractNumber
      ? `${projectName || 'Project'} | ${contractNumber}`
      : projectName || 'Project';

    const headerHtml = generateGotenbergHeader({
      projectName: leftHeader,
      documentTitle: reportType,
      organisationLogoUrl: organisationLogoUrl,
    });

    const footerHtml = generateGotenbergFooter({
      projectName: leftHeader,
      supplierName: supplierName,
    });

    formData.append('headerHtml', headerHtml);
    formData.append('footerHtml', footerHtml);

    // Call Gotenberg API with timeout
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 60000); // 60 second timeout

    try {
      const gotenbergResponse = await fetch(
        `${gotenbergUrl}/forms/chromium/convert/html`,
        {
          method: 'POST',
          body: formData,
          signal: controller.signal,
        }
      );

      clearTimeout(timeoutId);

      if (!gotenbergResponse.ok) {
        const errorText = await gotenbergResponse.text();
        console.error('❌ [Gotenberg] Error:', errorText);
        throw new Error(`Gotenberg API error: ${gotenbergResponse.status} - ${errorText}`);
      }

      const pdfBuffer = await gotenbergResponse.arrayBuffer();
      const pdfSize = pdfBuffer.byteLength;
      const duration = Date.now() - requestStartTime;

      console.log(`✅ [Gotenberg] PDF generated: ${pdfFilename} (${pdfSize} bytes in ${duration}ms)`);

      return new Response(pdfBuffer, {
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="${pdfFilename}"`,
        },
      });
    } catch (error) {
      clearTimeout(timeoutId);

      if (error instanceof Error && error.name === 'AbortError') {
        throw new Error('PDF generation timeout (60s)');
      }
      throw error;
    }

  } catch (error) {
    const duration = Date.now() - requestStartTime;
    console.error(`❌ [Gotenberg] PDF generation error (${duration}ms):`, error);

    // Log error details for debugging
    console.error('Error details:', {
      userId,
      reportType,
      errorMessage: error instanceof Error ? error.message : 'Unknown error',
      errorStack: error instanceof Error ? error.stack : undefined,
    });

    return new Response(
      JSON.stringify({
        error: error instanceof Error ? error.message : 'PDF generation failed',
        fallback: 'htm_export',
        message: 'Gotenberg service unavailable. Please use HTM export as fallback.',
      }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json',
        },
      }
    );
  }
});

//=============================================================================
// HEADER & FOOTER GENERATORS (FROM pdfLayoutSystem.ts)
//=============================================================================
// These are duplicated here because edge functions can't import from src/
// MUST stay in sync with src/lib/reports/pdfLayoutSystem.ts
//=============================================================================

const COLORS = {
  BRAND_ORANGE: '#f97316',
  BRAND_ORANGE_DARK: '#ea580c',
  GRAY_900: '#111827',
  GRAY_700: '#374151',
  GRAY_600: '#4b5563',
  GRAY_500: '#6b7280',
  GRAY_400: '#9ca3af',
  GRAY_300: '#d1d5db',
  GRAY_200: '#e5e7eb',
};

interface HeaderFooterConfig {
  projectName: string;
  documentTitle?: string;
  supplierName?: string;
  organisationLogoUrl?: string;
}

function generateGotenbergHeader(config: HeaderFooterConfig): string {
  const { projectName, documentTitle, organisationLogoUrl } = config;
  const today = new Date().toLocaleDateString('en-NZ', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const logoSection = organisationLogoUrl
    ? `
      <div class="logo-container" style="display: flex; align-items: center; gap: 10px;">
        <img
          src="${organisationLogoUrl}"
          alt="Organisation Logo"
          style="max-width: 100px; max-height: 40px; object-fit: contain;"
        />
        <div style="width: 1px; height: 32px; background: ${COLORS.GRAY_300}; margin: 0 4px;"></div>
        <div style="font-size: 15px; font-weight: 700; color: ${COLORS.GRAY_900}; letter-spacing: -0.3px;">VerifyTrade</div>
      </div>
    `
    : `
      <div class="logo-container" style="display: flex; align-items: center; gap: 10px;">
        <div style="
          width: 40px;
          height: 40px;
          background: linear-gradient(135deg, ${COLORS.BRAND_ORANGE} 0%, ${COLORS.BRAND_ORANGE_DARK} 100%);
          border-radius: 10px;
          display: flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 2px 8px rgba(249, 115, 22, 0.25);
        ">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
            <path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"/>
          </svg>
        </div>
        <div style="font-size: 16px; font-weight: 700; color: ${COLORS.GRAY_900}; letter-spacing: -0.4px;">VerifyTrade</div>
      </div>
    `;

  return `
    <html>
      <head>
        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif;
            font-size: 9pt;
            color: ${COLORS.GRAY_600};
            margin: 0;
            padding: 4mm 15mm 6mm 15mm;
            height: 20mm;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 3px solid ${COLORS.BRAND_ORANGE};
            background: white;
          }
          .left {
            display: flex;
            align-items: center;
            gap: 0;
          }
          .right {
            text-align: right;
          }
          .doc-title {
            font-size: 11pt;
            font-weight: 700;
            color: ${COLORS.GRAY_900};
            margin-bottom: 3px;
            letter-spacing: -0.2px;
          }
          .page-info {
            font-size: 9pt;
            color: ${COLORS.GRAY_500};
            font-weight: 500;
          }
        </style>
      </head>
      <body>
        <div class="left">${logoSection}</div>
        <div class="right">
          ${documentTitle ? `<div class="doc-title">${documentTitle}</div>` : ''}
          <div class="page-info">
            ${projectName} | ${today} | Page <span class="pageNumber"></span> of <span class="totalPages"></span>
          </div>
        </div>
      </body>
    </html>
  `;
}

function generateGotenbergFooter(config: HeaderFooterConfig): string {
  const { supplierName } = config;

  return `
    <html>
      <head>
        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            print-color-adjust: exact;
            -webkit-print-color-adjust: exact;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif;
            font-size: 8pt;
            color: ${COLORS.GRAY_400};
            margin: 0;
            padding: 8mm 15mm;
            height: 16mm;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-top: 1px solid ${COLORS.GRAY_200};
            background: white;
          }
          .left {
            font-weight: 600;
            color: ${COLORS.GRAY_600};
            font-size: 9pt;
          }
          .center {
            color: ${COLORS.BRAND_ORANGE};
            font-weight: 700;
            font-size: 9pt;
            letter-spacing: 0.3px;
          }
          .right {
            font-size: 8pt;
            color: ${COLORS.GRAY_400};
            font-style: italic;
          }
        </style>
      </head>
      <body>
        <div class="left">${supplierName || ''}</div>
        <div class="center">VerifyTrade | www.verifytrade.co.nz</div>
        <div class="right">Confidential</div>
      </body>
    </html>
  `;
}
