export interface PatternRule {
  pattern: RegExp;
  weight: number;
  reason: string;
}

export const TOTAL_LINE_RULES: PatternRule[] = [
  { pattern: /^total\s*:?\s*$/i,                          weight: 1.0, reason: "Exact 'Total' label" },
  { pattern: /^totals\s*:?\s*$/i,                         weight: 1.0, reason: "Exact 'Totals' label" },
  { pattern: /\btotal\s*:/i,                              weight: 0.95, reason: "Total colon prefix" },
  { pattern: /\bgrand\s+total\b/i,                        weight: 1.0,  reason: "Grand total keyword" },
  { pattern: /\bquote\s+total\b/i,                        weight: 1.0,  reason: "Quote total keyword" },
  { pattern: /\bcontract\s+sum\b/i,                       weight: 1.0,  reason: "Contract sum keyword" },
  { pattern: /\blump\s+sum\s+total\b/i,                   weight: 1.0,  reason: "Lump sum total keyword" },
  { pattern: /\boverall\s+total\b/i,                      weight: 1.0,  reason: "Overall total keyword" },
  { pattern: /\bsub[-\s]?total\b/i,                       weight: 0.9,  reason: "Subtotal keyword" },
  { pattern: /\bsection\s+total\b/i,                      weight: 0.9,  reason: "Section total keyword" },
  { pattern: /\bblock\s+total\b/i,                        weight: 0.9,  reason: "Block total keyword" },
  { pattern: /\bpage\s+total\b/i,                         weight: 0.85, reason: "Page total keyword" },
  { pattern: /\bcarried\s+forward\b/i,                    weight: 0.85, reason: "Carried forward" },
  { pattern: /\bbrought\s+forward\b/i,                    weight: 0.85, reason: "Brought forward" },
  { pattern: /\bc\/f\b|\bb\/f\b/i,                        weight: 0.8,  reason: "C/F or B/F abbreviation" },
  { pattern: /\bcumulative\s+total\b/i,                   weight: 0.9,  reason: "Cumulative total" },
  { pattern: /\btotal\s+\(excl/i,                         weight: 0.95, reason: "Total (excl. GST)" },
  { pattern: /\btotal\s+\(inc/i,                          weight: 0.95, reason: "Total (inc. GST)" },
  { pattern: /\btotal\s+price\b/i,                        weight: 0.9,  reason: "Total price label" },
  { pattern: /\btotal\s+amount\b/i,                       weight: 0.9,  reason: "Total amount label" },
  { pattern: /\btotal\s+cost\b/i,                         weight: 0.9,  reason: "Total cost label" },
  { pattern: /\bsum\s+of\b/i,                             weight: 0.8,  reason: "Sum of label" },
];

export const EXCLUSION_RULES: PatternRule[] = [
  { pattern: /\bexcluded?\b/i,                            weight: 0.95, reason: "Excluded keyword" },
  { pattern: /\bexclusion\b/i,                            weight: 0.95, reason: "Exclusion keyword" },
  { pattern: /\bby\s+others\b/i,                          weight: 1.0,  reason: "By others phrase" },
  { pattern: /\bnot\s+included\b/i,                       weight: 1.0,  reason: "Not included phrase" },
  { pattern: /\bno\s+allowance\b/i,                       weight: 1.0,  reason: "No allowance phrase" },
  { pattern: /\bomitted\b/i,                              weight: 0.95, reason: "Omitted keyword" },
  { pattern: /\bexcluded\s+from\s+price\b/i,              weight: 1.0,  reason: "Excluded from price" },
  { pattern: /\bsupply\s+by\s+others\b/i,                 weight: 1.0,  reason: "Supply by others" },
  { pattern: /\binstall\s+by\s+others\b/i,                weight: 1.0,  reason: "Install by others" },
  { pattern: /\bclient\s+supply\b/i,                      weight: 1.0,  reason: "Client supply" },
  { pattern: /\bclient\s+to\s+supply\b/i,                 weight: 1.0,  reason: "Client to supply" },
  { pattern: /\bnot\s+in\s+(this\s+)?contract\b/i,        weight: 0.9,  reason: "Not in contract" },
  { pattern: /\bnot\s+in\s+scope\b/i,                     weight: 0.9,  reason: "Not in scope" },
  { pattern: /\bout\s+of\s+scope\b/i,                     weight: 0.9,  reason: "Out of scope" },
  { pattern: /\ballow(ed)?\s+by\s+others\b/i,             weight: 0.9,  reason: "Allowed by others" },
];

export const QUALIFICATION_RULES: PatternRule[] = [
  { pattern: /\bsubject\s+to\b/i,                         weight: 0.95, reason: "Subject to qualifier" },
  { pattern: /\bassuming\b/i,                             weight: 0.9,  reason: "Assuming qualifier" },
  { pattern: /\bassumption\b/i,                           weight: 0.9,  reason: "Assumption keyword" },
  { pattern: /\bbased\s+on\b/i,                           weight: 0.85, reason: "Based on qualifier" },
  { pattern: /\bprovided\s+that\b/i,                      weight: 0.9,  reason: "Provided that qualifier" },
  { pattern: /\bpending\b/i,                              weight: 0.8,  reason: "Pending qualifier" },
  { pattern: /\btbc\b/i,                                  weight: 0.85, reason: "TBC qualifier" },
  { pattern: /\bto\s+be\s+confirmed\b/i,                  weight: 0.9,  reason: "To be confirmed" },
  { pattern: /\blimited\s+to\b/i,                         weight: 0.85, reason: "Limited to qualifier" },
  { pattern: /\bconditional\s+upon\b/i,                   weight: 0.9,  reason: "Conditional upon" },
  { pattern: /\bvalid\s+for\b/i,                          weight: 0.8,  reason: "Valid for qualifier" },
  { pattern: /\bsubject\s+to\s+survey\b/i,                weight: 1.0,  reason: "Subject to survey" },
  { pattern: /\bsubject\s+to\s+design\b/i,                weight: 1.0,  reason: "Subject to design" },
  { pattern: /\bnote:/i,                                  weight: 0.7,  reason: "Note prefix" },
  { pattern: /\bplease\s+note\b/i,                        weight: 0.7,  reason: "Please note phrase" },
];

export const OPTIONAL_RULES: PatternRule[] = [
  { pattern: /\boptional\b/i,                             weight: 1.0,  reason: "Optional keyword" },
  { pattern: /\boption\b/i,                               weight: 0.85, reason: "Option keyword" },
  { pattern: /\balternate\b/i,                            weight: 0.9,  reason: "Alternate keyword" },
  { pattern: /\balternative\b/i,                          weight: 0.9,  reason: "Alternative keyword" },
  { pattern: /\bprovisional\b/i,                          weight: 0.95, reason: "Provisional keyword" },
  { pattern: /\bprovisional\s+sum\b/i,                    weight: 1.0,  reason: "Provisional sum" },
  { pattern: /\bcontingency\b/i,                          weight: 0.95, reason: "Contingency item" },
  { pattern: /\bestimate\s+only\b/i,                      weight: 0.9,  reason: "Estimate only" },
  { pattern: /\bbudget\s+allowance\b/i,                   weight: 0.95, reason: "Budget allowance" },
  { pattern: /\ballowance\b/i,                            weight: 0.75, reason: "Allowance item" },
  { pattern: /\bpc\s+sum\b/i,                             weight: 0.9,  reason: "PC sum (provisional)" },
  { pattern: /\bprime\s+cost\b/i,                         weight: 0.85, reason: "Prime cost item" },
  { pattern: /\bvar\b|\bvariations?\b/i,                  weight: 0.7,  reason: "Variation item" },
];

export const NARRATIVE_RULES: PatternRule[] = [
  { pattern: /\bdear\s+\w+/i,                             weight: 1.0,  reason: "Greeting salutation" },
  { pattern: /\bbest\s+regards?\b/i,                      weight: 1.0,  reason: "Closing salutation" },
  { pattern: /\byours\s+(sincerely|faithfully|truly)\b/i, weight: 1.0,  reason: "Closing salutation" },
  { pattern: /\bthank\s+you\s+for\b/i,                    weight: 1.0,  reason: "Thank you phrase" },
  { pattern: /\bplease\s+find\b/i,                        weight: 0.9,  reason: "Please find phrase" },
  { pattern: /\bwe\s+are\s+pleased\b/i,                   weight: 0.9,  reason: "Intro phrase" },
  { pattern: /\bwe\s+hereby\b/i,                          weight: 0.9,  reason: "Intro phrase" },
  { pattern: /\bterms\s+and\s+conditions?\b/i,            weight: 0.95, reason: "T&C heading" },
  { pattern: /\bpayment\s+terms?\b/i,                     weight: 0.85, reason: "Payment terms text" },
  { pattern: /\bwarranty\b/i,                             weight: 0.7,  reason: "Warranty text" },
  { pattern: /^\s*page\s+\d+\s*(of\s+\d+)?\s*$/i,        weight: 1.0,  reason: "Page number" },
  { pattern: /^\s*\d+\s*of\s*\d+\s*$/i,                  weight: 1.0,  reason: "Page number fraction" },
  { pattern: /\bdocuments?\s+used\b/i,                    weight: 0.9,  reason: "Documents used section" },
  { pattern: /\barchitectural\s+drawings?\b/i,            weight: 0.8,  reason: "Drawing reference" },
  { pattern: /\bhydraulic\s+drawings?\b/i,                weight: 0.8,  reason: "Drawing reference" },
  { pattern: /\bcivil\s+drawings?\b/i,                    weight: 0.8,  reason: "Drawing reference" },
  { pattern: /\bproject\s+#\s*:\s*\d+/i,                 weight: 0.95, reason: "Project number header" },
  { pattern: /\bproject\s+number\b/i,                     weight: 0.9,  reason: "Project number label" },
  { pattern: /\bre:\s+/i,                                 weight: 0.7,  reason: "RE: subject line" },
  { pattern: /\bn\.t\.t\./i,                              weight: 0.9,  reason: "NTT reference line" },
  { pattern: /\bnone\s+received\b/i,                      weight: 0.85, reason: "None received phrase" },
  { pattern: /@[\w.-]+\.\w{2,}/,                          weight: 0.95, reason: "Email address present" },
  { pattern: /^(e|f|p|m|t)\s*:\s*[\d\s()+/-]+$/i,        weight: 0.85, reason: "Contact detail line" },
  { pattern: /^\s*[-–—]{3,}\s*$/,                         weight: 0.9,  reason: "Separator/divider line" },
  { pattern: /\babb\s+fire\s+protection\b/i,              weight: 0.6,  reason: "Company name only" },
];

export const MAIN_SCOPE_POSITIVE_RULES: PatternRule[] = [
  { pattern: /\bsanitary\b/i,                             weight: 0.5,  reason: "Sanitary system scope" },
  { pattern: /\bhot\s*&?\s*cold\s+water\b/i,              weight: 0.5,  reason: "Hot & cold water scope" },
  { pattern: /\bstormwater\b/i,                           weight: 0.5,  reason: "Stormwater scope" },
  { pattern: /\bgas\s+system\b/i,                         weight: 0.5,  reason: "Gas system scope" },
  { pattern: /\bacoustic\s+lagging\b/i,                   weight: 0.5,  reason: "Acoustic lagging scope" },
  { pattern: /\bsanitary\s+fittings\b/i,                  weight: 0.5,  reason: "Sanitary fittings scope" },
  { pattern: /\bplant\s*&?\s*valve\b/i,                   weight: 0.5,  reason: "Plant & valve scope" },
  { pattern: /\brainwater\b/i,                            weight: 0.5,  reason: "Rainwater scope" },
  { pattern: /\bfire\s+(rated|stopping|collar|damper)\b/i,weight: 0.5,  reason: "Passive fire scope" },
  { pattern: /\bpenetration\b/i,                          weight: 0.4,  reason: "Penetration item" },
  { pattern: /\bconduit\b/i,                              weight: 0.4,  reason: "Conduit scope" },
  { pattern: /\bcable\s+tray\b/i,                         weight: 0.4,  reason: "Cable tray scope" },
  { pattern: /\bduct\b/i,                                 weight: 0.35, reason: "Ductwork scope" },
  { pattern: /\bsprinkler\b/i,                            weight: 0.5,  reason: "Sprinkler scope" },
  { pattern: /\bhvac\b/i,                                 weight: 0.5,  reason: "HVAC scope" },
  { pattern: /\belectrical\b/i,                           weight: 0.45, reason: "Electrical scope" },
  { pattern: /\binsulation\b/i,                           weight: 0.4,  reason: "Insulation scope" },
  { pattern: /\bwrap\b/i,                                 weight: 0.35, reason: "Wrap scope" },
  { pattern: /\bsealing\b/i,                              weight: 0.4,  reason: "Sealing scope" },
  { pattern: /\binstallation\s+of\b/i,                    weight: 0.4,  reason: "Installation of scope" },
  { pattern: /\bsupply\s+(&|and)\s+install\b/i,           weight: 0.5,  reason: "Supply & install scope" },
  { pattern: /\bsupply\s+and\s+fix\b/i,                   weight: 0.5,  reason: "Supply and fix scope" },
  { pattern: /\b\d+mm\b/,                                 weight: 0.3,  reason: "Dimensional measurement" },
  { pattern: /\d+\/\d+\/\d+/,                             weight: 0.35, reason: "FRR rating present" },
];
