/**
 * Dispute Defence Pack Generator
 *
 * Purpose: Generate an immutable, timestamped, formally worded document
 * suitable for use in procurement disputes, contract investigations,
 * audit proceedings, or regulatory review.
 *
 * Sections:
 *   1. Decision Record — Who decided, when, what was recommended
 *   2. Data Snapshot — All tenderer inputs and normalised outputs at time of decision
 *   3. Risk Identification — Pre-award risks that were known and documented
 *   4. Recommendation Justification — Scored rationale with weights
 *   5. Commercial Warnings Issued — Any warnings raised before award
 *   6. Approval Trace — Full audit chain (who approved, when, any overrides)
 *   7. Defence Statement — Formal declaration of process integrity
 *
 * IMPORTANT: This file contains NO calculation logic.
 * All values are passed in pre-computed from upstream engines and frozen at export time.
 */

import type { ReportOptions } from './reportTypes';
import {
  C, fmt, pct, riskRatio, riskLabel,
  sharedHeader, sharedFooter, sectionHeading, infoBox,
  baseStyles, htmlWrap, openPrintWindow,
} from './reportShared';

const PACK_SUBTITLE = 'Dispute Defence Pack — Procurement Record';

function packHeader(opts: ReportOptions, snapshotTs: string): string {
  return sharedHeader(opts.organisationLogoUrl, opts.projectName, opts.clientName, snapshotTs, PACK_SUBTITLE);
}

function page1DecisionRecord(opts: ReportOptions, snapshotTs: string): string {
  const top = opts.suppliers[0];
  const ap = opts.approvalRecord;
  const weights = opts.scoringWeights ?? { price: 45, compliance: 20, coverage: 25, risk: 10 };

  return `<div class="page">
    ${packHeader(opts, snapshotTs)}

    <div style="background:${C.RED_BG};border:2px solid ${C.RED_BORDER};border-radius:6px;padding:10px 16px;margin-bottom:20px;font-size:11px;font-weight:700;color:${C.RED};text-transform:uppercase;letter-spacing:0.5px;">
      PRIVILEGED AND CONFIDENTIAL — DISPUTE DEFENCE DOCUMENT — NOT FOR GENERAL DISTRIBUTION
    </div>

    ${sectionHeading('1', 'Decision Record')}

    <div style="font-size:12px;color:${C.MID};line-height:1.7;margin-bottom:18px;">
      This document constitutes a formal record of the commercial adjudication conducted for the above project.
      It is produced for the purpose of evidencing the integrity, process compliance, and commercial defensibility of the tender evaluation and award decision.
      All data contained herein represents a point-in-time snapshot as at the timestamp stated below and is considered immutable for the purposes of this record.
    </div>

    <div style="border:1px solid ${C.BORDER};border-radius:10px;overflow:hidden;margin-bottom:20px;">
      <div style="background:${C.DARK};padding:10px 13px;">
        <div style="font-size:10px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.8px;">Decision Particulars</div>
      </div>
      ${[
        ['Project Name', opts.projectName],
        ['Client / Principal', opts.clientName ?? 'Not recorded'],
        ['Snapshot Timestamp (UTC)', snapshotTs],
        ['Report Generated By', opts.generatedByEmail ?? 'System'],
        ['Report ID', opts.reportId ?? 'N/A'],
        ['Number of Tenderers Evaluated', String(opts.suppliers.length)],
        ['Total Scope Items', String(opts.suppliers[0]?.totalItems ?? 'N/A')],
        ['Scoring Methodology', `Price ${weights.price}% / Coverage ${weights.coverage}% / Compliance ${weights.compliance}% / Risk ${weights.risk}%`],
        ['AI-Recommended Tenderer', ap?.ai_recommended_supplier ?? (top?.supplierName ?? 'Not recorded')],
        ['Approved Tenderer', ap?.final_approved_supplier ?? (top?.supplierName ?? 'Not recorded')],
        ['Override Applied', ap ? (ap.is_override ? 'YES — see Section 6' : 'No') : 'N/A'],
      ].map(([l, v], i) => `<div style="display:flex;padding:10px 13px;border-bottom:${i < 10 ? `1px solid ${C.BORDER}` : 'none'};background:${i % 2 === 0 ? 'white' : C.LIGHT_BG};">
        <div style="font-size:11px;font-weight:700;color:${C.MUTED};text-transform:uppercase;letter-spacing:0.4px;width:280px;flex-shrink:0;padding-top:1px;">${l}</div>
        <div style="font-size:13px;font-weight:600;color:${C.DARK};">${v}</div>
      </div>`).join('')}
    </div>

    ${sharedFooter('Decision Record', '1', true)}
  </div>`;
}

function page2DataSnapshot(opts: ReportOptions, snapshotTs: string): string {
  const maxRisk = Math.max(...opts.suppliers.map(s => s.riskScore));

  const rows = opts.suppliers.map(s => {
    const ratio = riskRatio(s.riskScore, maxRisk);
    const proj = s.projectedTotal ?? s.adjustedTotal;
    const varVal = s.variationExposureValue ?? 0;
    return `<tr style="border-bottom:1px solid ${C.BORDER};">
      <td style="padding:10px 11px;font-weight:700;font-size:12px;color:${C.DARK};">${s.supplierName}</td>
      <td style="padding:10px 11px;text-align:right;font-weight:700;font-size:12px;">${fmt(s.adjustedTotal)}</td>
      <td style="padding:10px 11px;text-align:right;font-size:12px;color:${proj !== s.adjustedTotal ? C.AMBER : C.GREEN};">${fmt(proj)}</td>
      <td style="padding:10px 11px;text-align:right;font-size:12px;color:${varVal > 0 ? C.RED : C.MUTED};">${fmt(varVal)}</td>
      <td style="padding:10px 11px;text-align:center;font-size:12px;">${pct(s.coveragePercent)}</td>
      <td style="padding:10px 11px;text-align:center;font-size:12px;">${s.itemsQuoted} / ${s.totalItems}</td>
      <td style="padding:10px 11px;text-align:center;font-size:12px;">${riskLabel(ratio)}</td>
      <td style="padding:10px 11px;text-align:center;font-size:12px;">${s.weightedScore !== undefined ? `${Math.round(s.weightedScore)}/100` : '—'}</td>
      <td style="padding:10px 11px;text-align:center;font-size:12px;">${s.rank}</td>
      <td style="padding:10px 11px;text-align:center;">
        ${s.underallowanceFlag
          ? `<span style="display:inline-block;padding:2px 7px;border-radius:3px;background:${C.RED_BG};color:${C.RED};font-size:9px;font-weight:700;text-transform:uppercase;">Yes</span>`
          : `<span style="display:inline-block;padding:2px 7px;border-radius:3px;background:${C.GREEN_BG};color:${C.GREEN};font-size:9px;font-weight:700;text-transform:uppercase;">No</span>`}
      </td>
    </tr>`;
  }).join('');

  return `<div class="page">
    ${packHeader(opts, snapshotTs)}
    ${sectionHeading('2', 'Data Snapshot — Tenderer Inputs & Outputs')}

    ${infoBox(`All figures below represent the immutable data captured at snapshot timestamp <strong>${snapshotTs}</strong>. No values have been altered for the purposes of this document.`, C.BLUE, C.BLUE_BG, '#1e3a8a')}

    <div style="border:1px solid ${C.BORDER};border-radius:10px;overflow:hidden;margin-bottom:16px;font-size:11px;">
      <table>
        <thead style="background:${C.DARK};">
          <tr>
            ${['Tenderer','Quoted Total','Projected Total','Variation Exp.','Coverage %','Items (Priced/Total)','Risk Level','Score','Rank','Qty Flag'].map(h =>
              `<th style="padding:9px 11px;font-size:9px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.4px;text-align:${h==='Tenderer'?'left':'center'};">${h}</th>`
            ).join('')}
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    </div>

    <div style="font-size:12px;color:${C.MUTED};line-height:1.6;border:1px solid ${C.BORDER};border-radius:6px;padding:12px 14px;">
      <strong>Data provenance:</strong> Quoted Totals are derived from supplier-submitted documents as parsed by the VerifyTrade extraction engine.
      Projected Totals incorporate variation exposure estimates based on scope coverage gaps and behaviour patterns.
      Scores are computed by the multi-criteria decision engine using the weights stated in Section 1.
      No manual adjustments to tenderer data have been made for this record.
    </div>

    ${sharedFooter('Data Snapshot', '2', true)}
  </div>`;
}

function page3RiskIdentification(opts: ReportOptions, snapshotTs: string): string {
  const maxRisk = Math.max(...opts.suppliers.map(s => s.riskScore));
  const hasHighRisk = opts.suppliers.some(s => riskRatio(s.riskScore, maxRisk) >= 0.6);
  const hasLowCoverage = opts.suppliers.some(s => s.coveragePercent < 75);
  const hasUnderallowance = opts.suppliers.some(s => s.underallowanceFlag);

  const riskItems: Array<{ level: string; color: string; bg: string; border: string; text: string }> = [];

  if (hasHighRisk) {
    const highRiskNames = opts.suppliers.filter(s => riskRatio(s.riskScore, maxRisk) >= 0.6).map(s => s.supplierName);
    riskItems.push({
      level: 'High', color: C.RED, bg: C.RED_BG, border: C.RED_BORDER,
      text: `${highRiskNames.join(', ')} ${highRiskNames.length === 1 ? 'was' : 'were'} identified as carrying a high-risk classification at the time of tender evaluation. This risk was recorded and factored into the composite scoring prior to any award recommendation.`,
    });
  }

  if (hasLowCoverage) {
    const lowCovNames = opts.suppliers.filter(s => s.coveragePercent < 75).map(s => `${s.supplierName} (${pct(s.coveragePercent)})`);
    riskItems.push({
      level: 'Elevated', color: C.AMBER, bg: C.AMBER_BG, border: C.AMBER_BORDER,
      text: `The following tenderers submitted below the 75% scope coverage threshold: ${lowCovNames.join(', ')}. Scope gap risk was recorded and variation exposure was quantified as part of the assessment. The projected total values in Section 2 reflect this adjustment.`,
    });
  }

  if (hasUnderallowance) {
    const uaNames = opts.suppliers.filter(s => s.underallowanceFlag).map(s => s.supplierName);
    riskItems.push({
      level: 'Elevated', color: C.AMBER, bg: C.AMBER_BG, border: C.AMBER_BORDER,
      text: `Quantity under-allowance was identified for: ${uaNames.join(', ')}. Submitted quantities fell below the reference baseline, creating a risk of post-contract measurement disputes. This risk was disclosed to the recommending authority prior to any award decision.`,
    });
  }

  if (opts.commercialWarning) {
    riskItems.push({
      level: 'Commercial Warning', color: C.AMBER, bg: C.AMBER_BG, border: C.AMBER_BORDER,
      text: opts.commercialWarning,
    });
  }

  if (riskItems.length === 0) {
    riskItems.push({
      level: 'Standard', color: C.GREEN, bg: C.GREEN_BG, border: C.GREEN_BORDER,
      text: 'No material pre-award risks were identified above standard thresholds. Risk levels across the tender field were within normal commercial bounds at the time of evaluation.',
    });
  }

  return `<div class="page">
    ${packHeader(opts, snapshotTs)}
    ${sectionHeading('3', 'Risk Identification — Pre-Award Risks on Record')}

    <div style="font-size:12px;color:${C.MID};line-height:1.7;margin-bottom:16px;">
      The following risks were identified and formally recorded during the tender evaluation process.
      Each item below represents a risk that was known to the evaluation team prior to any recommendation or award decision being made.
      The existence of these records demonstrates that risk identification was systematic and documented, not reactive.
    </div>

    ${riskItems.map((r, i) => `<div style="background:${r.bg};border:2px solid ${r.border};border-radius:8px;padding:16px 20px;margin-bottom:14px;">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:8px;">
        <span style="display:inline-block;padding:3px 10px;border-radius:4px;background:${r.color};color:white;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px;">${r.level}</span>
        <span style="font-size:11px;font-weight:700;color:${C.MUTED};text-transform:uppercase;letter-spacing:0.5px;">Risk Item ${i + 1} of ${riskItems.length}</span>
      </div>
      <p style="font-size:13px;color:${C.MID};line-height:1.7;margin:0;">${r.text}</p>
    </div>`).join('')}

    <div style="background:${C.LIGHT_BG};border:1px solid ${C.BORDER};border-radius:8px;padding:14px 18px;font-size:12px;color:${C.MID};line-height:1.7;margin-top:8px;">
      <strong>Risk recording confirmation:</strong> The above risks were surfaced by the VerifyTrade automated risk engine and presented to the evaluating officer prior to the award recommendation being finalised.
      Risks were not suppressed, modified, or omitted from the evaluation record.
    </div>

    ${sharedFooter('Risk Identification', '3', true)}
  </div>`;
}

function page4RecommendationJustification(opts: ReportOptions, snapshotTs: string): string {
  const top = opts.suppliers[0];
  const weights = opts.scoringWeights ?? { price: 45, compliance: 20, coverage: 25, risk: 10 };
  const maxRisk = Math.max(...opts.suppliers.map(s => s.riskScore));

  const scoreRows = opts.suppliers.map(s => {
    const ratio = riskRatio(s.riskScore, maxRisk);
    return `<tr style="border-bottom:1px solid ${C.BORDER};${s.rank === 1 ? `background:${C.GREEN_BG};` : ''}">
      <td style="padding:10px 12px;font-weight:700;font-size:12px;color:${C.DARK};">${s.supplierName}</td>
      <td style="padding:10px 12px;text-align:right;font-size:12px;font-weight:600;">${fmt(s.adjustedTotal)}</td>
      <td style="padding:10px 12px;text-align:center;font-size:12px;font-weight:600;color:${s.coveragePercent >= 85 ? C.GREEN : C.AMBER};">${pct(s.coveragePercent)}</td>
      <td style="padding:10px 12px;text-align:center;font-size:12px;font-weight:600;">${riskLabel(ratio)}</td>
      <td style="padding:10px 12px;text-align:center;font-size:12px;font-weight:700;color:${C.DARK};">${s.weightedScore !== undefined ? `${Math.round(s.weightedScore)}/100` : '—'}</td>
      <td style="padding:10px 12px;text-align:center;font-size:12px;font-weight:700;color:${s.rank === 1 ? C.GREEN : C.MUTED};">
        <span style="display:inline-block;padding:3px 8px;border-radius:4px;background:${s.rank === 1 ? C.GREEN_BG : C.LIGHT_BG};color:${s.rank === 1 ? C.GREEN : C.MUTED};font-size:10px;font-weight:700;text-transform:uppercase;">${s.rank === 1 ? 'Recommended' : `Rank ${s.rank}`}</span>
      </td>
    </tr>`;
  }).join('');

  const drivers = opts.keyDecisionDrivers ?? top?.notes ?? [];
  const execText = opts.executiveSummary ?? (top
    ? `Commercial analysis of ${opts.suppliers.length} tenderer${opts.suppliers.length !== 1 ? 's' : ''} was conducted across ${top.totalItems} scope items. ${top.supplierName} was assessed as the preferred tenderer, achieving the highest composite score of ${top.weightedScore !== undefined ? `${Math.round(top.weightedScore)}/100` : 'N/A'} under the stated scoring methodology.`
    : 'Commercial analysis completed.');

  return `<div class="page">
    ${packHeader(opts, snapshotTs)}
    ${sectionHeading('4', 'Recommendation Justification')}

    <div style="background:${C.LIGHT_BG};border-left:4px solid ${C.ORANGE};border-radius:0 8px 8px 0;padding:16px 20px;margin-bottom:18px;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px;color:${C.MUTED};margin-bottom:7px;">Justification Statement</div>
      <p style="font-size:13px;color:${C.MID};line-height:1.8;margin:0;">${execText}</p>
    </div>

    <div style="background:${C.LIGHT_BG};border:1px solid ${C.BORDER};border-radius:8px;padding:14px 18px;margin-bottom:16px;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;color:${C.MUTED};margin-bottom:10px;">Scoring Methodology Applied</div>
      <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;">
        ${[['Price', weights.price], ['Coverage', weights.coverage], ['Compliance', weights.compliance], ['Risk', weights.risk]].map(([l, w]) =>
          `<div style="text-align:center;background:white;border:1px solid ${C.BORDER};border-radius:6px;padding:12px 8px;">
            <div style="font-size:20px;font-weight:800;color:${C.ORANGE};">${w}%</div>
            <div style="font-size:10px;font-weight:700;text-transform:uppercase;color:${C.MUTED};margin-top:3px;">${l}</div>
          </div>`).join('')}
      </div>
    </div>

    <div style="border:1px solid ${C.BORDER};border-radius:10px;overflow:hidden;margin-bottom:18px;">
      <table>
        <thead style="background:${C.DARK};">
          <tr>
            <th style="padding:10px 12px;text-align:left;font-size:10px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.5px;">Tenderer</th>
            <th style="padding:10px 12px;text-align:right;font-size:10px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.5px;">Quoted Total</th>
            <th style="padding:10px 12px;text-align:center;font-size:10px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.5px;">Coverage</th>
            <th style="padding:10px 12px;text-align:center;font-size:10px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.5px;">Risk</th>
            <th style="padding:10px 12px;text-align:center;font-size:10px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.5px;">Composite Score</th>
            <th style="padding:10px 12px;text-align:center;font-size:10px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.5px;">Outcome</th>
          </tr>
        </thead>
        <tbody>${scoreRows}</tbody>
      </table>
    </div>

    ${drivers.length > 0 ? `<div style="border:1px solid ${C.BORDER};border-radius:8px;padding:16px 18px;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;color:${C.MUTED};margin-bottom:10px;">Documented Decision Factors</div>
      ${drivers.map((d, i) => `<div style="display:flex;gap:10px;margin-bottom:7px;font-size:12px;color:${C.MID};">
        <span style="font-size:11px;font-weight:700;color:${C.MUTED};flex-shrink:0;">${i + 1}.</span>
        <span>${d}</span>
      </div>`).join('')}
    </div>` : ''}

    ${sharedFooter('Recommendation Justification', '4', true)}
  </div>`;
}

function page5CommercialWarnings(opts: ReportOptions, snapshotTs: string): string {
  const controls = opts.commercialControlsRequired ?? [];
  const hasWarning = !!opts.commercialWarning;
  const hasControls = controls.length > 0;

  return `<div class="page">
    ${packHeader(opts, snapshotTs)}
    ${sectionHeading('5', 'Commercial Warnings Issued')}

    <div style="font-size:12px;color:${C.MID};line-height:1.7;margin-bottom:16px;">
      This section records all commercial warnings and required controls that were communicated to the responsible officer prior to any award decision.
      The existence of this record evidences that warnings were not withheld or suppressed, and that the awarding authority was properly informed of all material commercial risks.
    </div>

    ${hasWarning ? `<div style="background:${C.AMBER_BG};border:2px solid ${C.AMBER_BORDER};border-radius:8px;padding:16px 20px;margin-bottom:16px;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;color:${C.AMBER};margin-bottom:7px;">Commercial Warning — Issued Pre-Award</div>
      <p style="font-size:13px;color:#78350f;line-height:1.7;margin:0;">${opts.commercialWarning}</p>
      <div style="margin-top:10px;font-size:11px;color:${C.AMBER};font-weight:600;">Issued at: ${snapshotTs}</div>
    </div>` : `<div style="background:${C.GREEN_BG};border:2px solid ${C.GREEN_BORDER};border-radius:8px;padding:16px 20px;margin-bottom:16px;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;color:${C.GREEN};margin-bottom:7px;">No Commercial Warning Issued</div>
      <p style="font-size:13px;color:#14532d;line-height:1.7;margin:0;">No material commercial warnings were generated during the evaluation of this tender. Risk levels were within standard commercial thresholds.</p>
    </div>`}

    ${hasControls ? `<div style="border:1px solid ${C.BORDER};border-radius:10px;overflow:hidden;margin-bottom:18px;">
      <div style="background:${C.DARK};padding:10px 13px;">
        <div style="font-size:10px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.8px;">Commercial Controls Required — On Record</div>
      </div>
      ${controls.map((c, i) => `<div style="display:flex;gap:12px;padding:12px 15px;border-bottom:${i < controls.length - 1 ? `1px solid ${C.BORDER}` : 'none'};background:${i % 2 === 0 ? 'white' : C.LIGHT_BG};">
        <div style="width:22px;height:22px;border-radius:4px;background:${C.DARK};color:white;font-size:10px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0;">${i + 1}</div>
        <div style="font-size:12px;color:${C.MID};line-height:1.6;padding-top:1px;">${c}</div>
      </div>`).join('')}
    </div>` : ''}

    <div style="background:${C.LIGHT_BG};border:1px solid ${C.BORDER};border-radius:8px;padding:14px 18px;font-size:12px;color:${C.MID};line-height:1.7;">
      <strong>Record integrity statement:</strong> The warnings and controls recorded above were generated by the VerifyTrade automated analysis engine
      and presented to the responsible officer without alteration. This record has not been modified after the fact.
    </div>

    ${sharedFooter('Commercial Warnings Issued', '5', true)}
  </div>`;
}

function page6ApprovalTrace(opts: ReportOptions, snapshotTs: string): string {
  const ap = opts.approvalRecord;

  return `<div class="page">
    ${packHeader(opts, snapshotTs)}
    ${sectionHeading('6', 'Approval Trace')}

    <div style="font-size:12px;color:${C.MID};line-height:1.7;margin-bottom:16px;">
      This section provides the complete approval chain for the award decision, including the identity of the approving officer,
      the timestamp of approval, and any override of the system recommendation. This record is intended to demonstrate
      that the award decision was authorised by a duly empowered officer and is not subject to dispute on the grounds of unauthorised action.
    </div>

    ${ap ? `<div style="border:1px solid ${ap.is_override ? C.AMBER_BORDER : C.GREEN_BORDER};border-radius:10px;overflow:hidden;margin-bottom:18px;">
      <div style="background:${ap.is_override ? C.AMBER : C.GREEN};padding:12px 16px;">
        <div style="font-size:11px;font-weight:700;color:white;text-transform:uppercase;letter-spacing:0.5px;">${ap.is_override ? 'OVERRIDE APPROVAL — System Recommendation Departed From' : 'STANDARD APPROVAL — System Recommendation Followed'}</div>
      </div>
      ${[
        ['System Recommended Tenderer', ap.ai_recommended_supplier],
        ['Approved Tenderer', ap.final_approved_supplier],
        ['Approving Officer (Email)', ap.approved_by_email],
        ['Approval Timestamp (local)', new Date(ap.approved_at).toLocaleString('en-AU', { timeZoneName: 'short' })],
        ['Approval Timestamp (ISO 8601)', ap.approved_at],
        ['Override Applied', ap.is_override ? 'YES' : 'No'],
        ...(ap.is_override ? [
          ['Override Category', ap.override_reason_category?.replace(/_/g, ' ').toUpperCase() ?? 'Not recorded'],
          ['Override Justification', ap.override_reason_detail ?? 'Not recorded'],
        ] : []),
      ].map(([l, v], i) => `<div style="display:flex;padding:10px 14px;border-bottom:1px solid ${C.BORDER};background:${i % 2 === 0 ? 'white' : C.LIGHT_BG};">
        <div style="font-size:11px;font-weight:700;color:${C.MUTED};text-transform:uppercase;letter-spacing:0.4px;width:260px;flex-shrink:0;padding-top:1px;">${l}</div>
        <div style="font-size:13px;font-weight:600;color:${C.DARK};">${v}</div>
      </div>`).join('')}
    </div>

    ${ap.is_override ? `<div style="background:${C.AMBER_BG};border:2px solid ${C.AMBER_BORDER};border-radius:8px;padding:16px 20px;margin-bottom:16px;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;color:${C.AMBER};margin-bottom:7px;">Override Audit Note</div>
      <p style="font-size:13px;color:#78350f;line-height:1.7;margin:0;">
        The awarding officer departed from the system recommendation. The reason for departure was formally recorded at the time of approval.
        The override was made by a duly authorised officer and does not invalidate the procurement process, provided the recorded justification is considered adequate
        under applicable procurement policy and governance requirements.
      </p>
    </div>` : ''}` : `<div style="background:${C.LIGHT_BG};border:1px solid ${C.BORDER};border-radius:8px;padding:16px 20px;font-size:13px;color:${C.MID};line-height:1.7;">
      No formal approval record was captured in the system at the time this Defence Pack was generated.
      This may indicate that approval was obtained outside the system or that the award had not yet been formally approved.
      Please attach any external approval documentation to this pack.
    </div>`}

    ${sharedFooter('Approval Trace', '6', true)}
  </div>`;
}

function page7DefenceStatement(opts: ReportOptions, snapshotTs: string): string {
  const top = opts.suppliers[0];
  const ap = opts.approvalRecord;
  const weights = opts.scoringWeights ?? { price: 45, compliance: 20, coverage: 25, risk: 10 };

  return `<div class="page">
    ${packHeader(opts, snapshotTs)}
    ${sectionHeading('7', 'Defence Statement')}

    <div style="background:${C.DARK};border-radius:10px;padding:24px;margin-bottom:20px;">
      <div style="font-size:13px;font-weight:800;color:white;margin-bottom:16px;text-transform:uppercase;letter-spacing:0.5px;">Formal Declaration of Process Integrity</div>
      <p style="font-size:13px;color:#d1d5db;line-height:1.9;margin:0 0 14px;">
        This Dispute Defence Pack has been prepared for the project known as <strong style="color:white;">${opts.projectName}</strong>${opts.clientName ? `, on behalf of ${opts.clientName}` : ''}.
        It constitutes a complete and accurate record of the commercial adjudication process conducted for this tender evaluation.
      </p>
      <p style="font-size:13px;color:#d1d5db;line-height:1.9;margin:0 0 14px;">
        The evaluation was conducted using a structured multi-criteria assessment methodology, applying defined weights of
        ${weights.price}% price, ${weights.coverage}% scope coverage, ${weights.compliance}% compliance, and ${weights.risk}% risk.
        These weights were applied consistently across all ${opts.suppliers.length} tenderer${opts.suppliers.length !== 1 ? 's' : ''} evaluated.
      </p>
      <p style="font-size:13px;color:#d1d5db;line-height:1.9;margin:0 0 14px;">
        ${top ? `On the basis of the evaluation, <strong style="color:white;">${top.supplierName}</strong> was identified as the preferred tenderer,
        achieving the highest composite score of <strong style="color:white;">${top.weightedScore !== undefined ? `${Math.round(top.weightedScore)}/100` : 'N/A'}</strong>
        against the stated criteria. The recommendation was made on commercial grounds and in accordance with the scoring methodology disclosed to all participating tenderers.` : ''}
      </p>
      ${ap ? `<p style="font-size:13px;color:#d1d5db;line-height:1.9;margin:0 0 14px;">
        The award was ${ap.is_override ? `approved with a departure from the system recommendation, authorised by ${ap.approved_by_email} on ${new Date(ap.approved_at).toLocaleDateString('en-AU')}. The basis for departure was formally recorded.` : `approved in accordance with the system recommendation by ${ap.approved_by_email} on ${new Date(ap.approved_at).toLocaleDateString('en-AU')}.`}
      </p>` : ''}
      <p style="font-size:13px;color:#d1d5db;line-height:1.9;margin:0;">
        All commercial warnings, risk identifications, and control requirements documented in this pack were communicated to the responsible officer prior to the award decision.
        The process was conducted with transparency, impartiality, and in accordance with the commercial governance requirements applicable to this project.
        This document is produced in good faith as evidence of a properly conducted procurement process.
      </p>
    </div>

    <div style="border:2px solid ${C.BORDER};border-radius:10px;padding:20px;margin-bottom:18px;">
      <div style="font-size:11px;font-weight:700;text-transform:uppercase;color:${C.MUTED};margin-bottom:14px;">Record Metadata</div>
      ${[
        ['Document Type', 'Dispute Defence Pack'],
        ['Project', opts.projectName],
        ['Snapshot Timestamp', snapshotTs],
        ['Generated By', opts.generatedByEmail ?? 'VerifyTrade System'],
        ['Report ID', opts.reportId ?? 'N/A'],
        ['Tenderers Evaluated', String(opts.suppliers.length)],
        ['Pack Status', 'Immutable — Do not alter after generation'],
      ].map(([l, v]) => `<div style="display:flex;padding:8px 0;border-bottom:1px solid ${C.BORDER};">
        <div style="font-size:11px;font-weight:700;color:${C.MUTED};text-transform:uppercase;letter-spacing:0.4px;width:240px;flex-shrink:0;">${l}</div>
        <div style="font-size:12px;font-weight:600;color:${C.DARK};">${v}</div>
      </div>`).join('')}
    </div>

    <div style="background:${C.LIGHT_BG};border:1px solid ${C.BORDER};border-radius:8px;padding:14px 18px;font-size:11px;color:${C.MUTED};line-height:1.7;text-align:center;">
      This Dispute Defence Pack is generated by VerifyTrade. It is privileged and confidential and is intended solely for authorised recipients in connection with a formal dispute, audit, or regulatory proceeding.
      It does not constitute legal advice. Recipients should seek independent legal counsel as required.
    </div>

    ${sharedFooter('Defence Statement', '7', true)}
  </div>`;
}

export interface DisputeDefencePackOptions extends ReportOptions {
  snapshotTimestamp?: string;
}

export function generateDisputeDefencePack(opts: DisputeDefencePackOptions): string {
  const snapshotTs = opts.snapshotTimestamp ?? new Date().toISOString();

  const body = [
    page1DecisionRecord(opts, snapshotTs),
    page2DataSnapshot(opts, snapshotTs),
    page3RiskIdentification(opts, snapshotTs),
    page4RecommendationJustification(opts, snapshotTs),
    page5CommercialWarnings(opts, snapshotTs),
    page6ApprovalTrace(opts, snapshotTs),
    page7DefenceStatement(opts, snapshotTs),
  ].join('\n');

  return htmlWrap(
    `Dispute Defence Pack — ${opts.projectName} — ${snapshotTs}`,
    baseStyles('screen'),
    body,
  );
}

export function openDisputeDefencePack(opts: DisputeDefencePackOptions, filename: string): void {
  openPrintWindow(generateDisputeDefencePack(opts), filename);
}
