/*
  # Phase 10 – Predictive Intelligence Layer

  ## Summary
  Three new additive tables that power pre-parse risk scoring, post-parse enrichment,
  and admin-configurable routing policies for plumbing_parser. Nothing is deployed
  to the live parser automatically — all routing is advisory unless an explicit admin
  policy is activated.

  ## New Tables

  ### parser_risk_profiles
  One risk profile per parsed document (source_id). Stores the extracted quote
  signature, computed risk score (0-100), risk tier, individual risk factors, and
  the routing recommendation generated by the policy engine. Updated after post-parse
  enrichment with actuals.

  ### parser_risk_events
  Immutable event log of each risk evaluation — pre_parse, post_parse, and
  route_decision events. Multiple events per source_id are expected as the document
  moves through the pipeline. Used for prediction validation and trend analysis.

  ### parser_risk_policy
  Admin-managed policies that translate risk tiers into routing behaviors. Only one
  policy can be is_active at a time per module. All others are archived. Policy JSON
  contains tier-to-action mappings. Defaults to conservative/log-only mode.

  ## Security
  - RLS enabled on all tables
  - Platform admins only
  - No anonymous or authenticated-user access

  ## Notes
  1. All additive — no existing tables modified
  2. IF NOT EXISTS / IF NOT EXISTS guard throughout
  3. Future-hook columns (e.g. auto_shadow_route) are present but default to false
*/

-- ─── parser_risk_profiles ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS parser_risk_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  module_key text NOT NULL,
  source_type text NOT NULL,
  source_id text NOT NULL,
  org_id text,
  quote_signature_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  risk_score numeric(5,1) NOT NULL DEFAULT 0,
  risk_tier text NOT NULL DEFAULT 'low' CHECK (risk_tier IN ('low', 'medium', 'high', 'critical')),
  risk_factors_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  routing_recommendation text NOT NULL DEFAULT 'normal_live_path',
  post_parse_enriched bool NOT NULL DEFAULT false,
  post_parse_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  actual_outcome text,
  prediction_correct bool,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (module_key, source_id)
);

ALTER TABLE parser_risk_profiles ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_prp_module_key  ON parser_risk_profiles(module_key);
CREATE INDEX IF NOT EXISTS idx_prp_org_id      ON parser_risk_profiles(org_id);
CREATE INDEX IF NOT EXISTS idx_prp_risk_tier   ON parser_risk_profiles(risk_tier);
CREATE INDEX IF NOT EXISTS idx_prp_risk_score  ON parser_risk_profiles(risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_prp_created_at  ON parser_risk_profiles(created_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'parser_risk_profiles' AND policyname = 'Platform admins can select risk profiles') THEN
    CREATE POLICY "Platform admins can select risk profiles"
      ON parser_risk_profiles FOR SELECT TO authenticated
      USING (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'parser_risk_profiles' AND policyname = 'Platform admins can insert risk profiles') THEN
    CREATE POLICY "Platform admins can insert risk profiles"
      ON parser_risk_profiles FOR INSERT TO authenticated
      WITH CHECK (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'parser_risk_profiles' AND policyname = 'Platform admins can update risk profiles') THEN
    CREATE POLICY "Platform admins can update risk profiles"
      ON parser_risk_profiles FOR UPDATE TO authenticated
      USING (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true))
      WITH CHECK (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true));
  END IF;
END $$;

-- ─── parser_risk_events ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS parser_risk_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  module_key text NOT NULL,
  source_type text NOT NULL,
  source_id text NOT NULL,
  org_id text,
  run_id text,
  risk_score numeric(5,1) NOT NULL DEFAULT 0,
  risk_tier text NOT NULL DEFAULT 'low' CHECK (risk_tier IN ('low', 'medium', 'high', 'critical')),
  event_type text NOT NULL CHECK (event_type IN ('pre_parse', 'post_parse', 'route_decision')),
  risk_factors_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  routing_decision_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE parser_risk_events ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_pre_module_key  ON parser_risk_events(module_key);
CREATE INDEX IF NOT EXISTS idx_pre_source_id   ON parser_risk_events(source_id);
CREATE INDEX IF NOT EXISTS idx_pre_org_id      ON parser_risk_events(org_id);
CREATE INDEX IF NOT EXISTS idx_pre_risk_tier   ON parser_risk_events(risk_tier);
CREATE INDEX IF NOT EXISTS idx_pre_event_type  ON parser_risk_events(event_type);
CREATE INDEX IF NOT EXISTS idx_pre_created_at  ON parser_risk_events(created_at DESC);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'parser_risk_events' AND policyname = 'Platform admins can select risk events') THEN
    CREATE POLICY "Platform admins can select risk events"
      ON parser_risk_events FOR SELECT TO authenticated
      USING (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'parser_risk_events' AND policyname = 'Platform admins can insert risk events') THEN
    CREATE POLICY "Platform admins can insert risk events"
      ON parser_risk_events FOR INSERT TO authenticated
      WITH CHECK (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true));
  END IF;
END $$;

-- ─── parser_risk_policy ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS parser_risk_policy (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  module_key text NOT NULL,
  policy_name text NOT NULL,
  description text NOT NULL DEFAULT '',
  policy_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active bool NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid REFERENCES auth.users(id)
);

ALTER TABLE parser_risk_policy ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_prpol_module_key ON parser_risk_policy(module_key);
CREATE INDEX IF NOT EXISTS idx_prpol_is_active  ON parser_risk_policy(is_active);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'parser_risk_policy' AND policyname = 'Platform admins can select risk policies') THEN
    CREATE POLICY "Platform admins can select risk policies"
      ON parser_risk_policy FOR SELECT TO authenticated
      USING (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'parser_risk_policy' AND policyname = 'Platform admins can insert risk policies') THEN
    CREATE POLICY "Platform admins can insert risk policies"
      ON parser_risk_policy FOR INSERT TO authenticated
      WITH CHECK (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'parser_risk_policy' AND policyname = 'Platform admins can update risk policies') THEN
    CREATE POLICY "Platform admins can update risk policies"
      ON parser_risk_policy FOR UPDATE TO authenticated
      USING (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true))
      WITH CHECK (EXISTS (SELECT 1 FROM platform_admins WHERE platform_admins.user_id = auth.uid() AND platform_admins.is_active = true));
  END IF;
END $$;

-- ─── Seed default conservative policy ─────────────────────────────────────────

INSERT INTO parser_risk_policy (module_key, policy_name, description, policy_json, is_active)
SELECT
  'plumbing_parser',
  'Conservative Default Policy',
  'Log-only for all risk tiers. No automatic routing changes. Safe default.',
  '{
    "low":      { "action": "normal_live_path",          "log": true,  "shadowCompare": false, "reviewRequired": false },
    "medium":   { "action": "normal_live_path",          "log": true,  "shadowCompare": false, "reviewRequired": false },
    "high":     { "action": "shadow_compare_recommended","log": true,  "shadowCompare": false, "reviewRequired": false },
    "critical": { "action": "manual_review_recommended", "log": true,  "shadowCompare": false, "reviewRequired": false },
    "autoShadowRouteEnabled": false,
    "autoReviewQueueEnabled": false,
    "orgWatchlistEnabled": false,
    "version": "1.0.0"
  }'::jsonb,
  true
WHERE NOT EXISTS (
  SELECT 1 FROM parser_risk_policy WHERE module_key = 'plumbing_parser' AND is_active = true
);
